// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameSafeUtsInfo = "safe_uts_info"

// SafeUtsInfo 探针设备信息
type SafeUtsInfo struct {
	UtsID     uint           `gorm:"column:uts_id;type:int unsigned;primaryKey;comment:探针id" json:"uts_id"`   // 探针id
	CPU       datatypes.JSON `gorm:"column:cpu;type:json;not null;comment:cpu信息" json:"cpu"`                  // cpu信息
	RAM       datatypes.JSON `gorm:"column:ram;type:json;not null;comment:内存信息" json:"ram"`                   // 内存信息
	Disk      datatypes.JSON `gorm:"column:disk;type:json;not null;comment:磁盘信息" json:"disk"`                 // 磁盘信息
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;comment:修改时间" json:"updated_at"`          // 修改时间
}

// TableName SafeUtsInfo's table name
func (*SafeUtsInfo) TableName() string {
	return TableNameSafeUtsInfo
}
