// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSafeUtsStatus = "safe_uts_status"

// SafeUtsStatus 探针设备状态
type SafeUtsStatus struct {
	UtsID  uint  `gorm:"column:uts_id;type:int unsigned;primaryKey;comment:探针设备表ID" json:"uts_id"` // 探针设备表ID
	Online uint8 `gorm:"column:online;type:tinyint unsigned;not null;comment:在线状态" json:"online"`  // 在线状态
	/*
		采集状态
		1:normal (正常)
		2:warning (警告，但是可以正常工作)
		3:error (错误，无法正常工作)
	*/
	Status    uint8      `gorm:"column:status;type:tinyint unsigned;not null;comment:采集状态\n1:normal (正常)\n2:warning (警告，但是可以正常工作) \n3:error (错误，无法正常工作)" json:"status"`
	Total     uint64     `gorm:"column:total;type:bigint unsigned;not null;comment:总计流量" json:"total"`       // 总计流量
	Packet    int64      `gorm:"column:packet;type:bigint;not null;comment:总计数据包" json:"packet"`             // 总计数据包
	CPU       uint8      `gorm:"column:cpu;type:tinyint unsigned;not null;comment:CPU占用率" json:"cpu"`        // CPU占用率
	Memory    uint8      `gorm:"column:memory;type:tinyint unsigned;not null;comment:内存占用率" json:"memory"`   // 内存占用率
	Disk      uint8      `gorm:"column:disk;type:tinyint unsigned;not null;comment:磁盘信息" json:"disk"`        // 磁盘信息
	Runtime   uint64     `gorm:"column:runtime;type:bigint unsigned;not null;comment:系统运行时长" json:"runtime"` // 系统运行时长
	CreatedAt time.Time  `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`    // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;comment:修改时间" json:"updated_at"`             // 修改时间
	DeletedAt *time.Time `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`             // 删除时间
}

// TableName SafeUtsStatus's table name
func (*SafeUtsStatus) TableName() string {
	return TableNameSafeUtsStatus
}
