// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSafeIpaddress = "safe_ipaddress"

// SafeIpaddress 公司IP资源清单表
type SafeIpaddress struct {
	ID             uint64      `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                                                                    // 主键
	CompanyID      uint64      `gorm:"column:company_id;type:bigint unsigned;not null;uniqueIndex:uk_company_ip,priority:1;index:idx_company_active,priority:1;comment:关联company_info.id" json:"company_id"` // 关联company_info.id
	IPAddress      string      `gorm:"column:ip_address;type:varchar(45);not null;uniqueIndex:uk_company_ip,priority:2;comment:IP地址（兼容IPv4/IPv6）" json:"ip_address"`                                         // IP地址（兼容IPv4/IPv6）
	IPVersion      *uint8      `gorm:"column:ip_version;type:tinyint unsigned;not null;default:4;comment:4=IPv4, 6=IPv6" json:"ip_version"`                                                                  // 4=IPv4, 6=IPv6
	IPType         uint8       `gorm:"column:ip_type;type:tinyint unsigned;not null;comment:1=官网,2=API,3=办公出口,4=CDN,5=数据库" json:"ip_type"`                                                                   // 1=官网,2=API,3=办公出口,4=CDN,5=数据库
	Purpose        string      `gorm:"column:purpose;type:varchar(100);not null;comment:用途说明" json:"purpose"`                                                                                                // 用途说明
	IsActive       *uint8      `gorm:"column:is_active;type:tinyint unsigned;not null;index:idx_company_active,priority:2;default:1;comment:是否启用" json:"is_active"`                                          // 是否启用
	LastVerifiedAt time.Time   `gorm:"column:last_verified_at;type:datetime;not null;comment:最后验证时间" json:"last_verified_at"`                                                                                // 最后验证时间
	VerifiedBy     uint64      `gorm:"column:verified_by;type:bigint unsigned;not null;comment:验证人" json:"verified_by"`                                                                                      // 验证人
	CreatedAt      *time.Time  `gorm:"column:created_at;type:datetime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                                                    // 创建时间
	UpdatedAt      **time.Time `gorm:"column:updated_at;type:datetime;default:CURRENT_TIMESTAMP;comment:修改时间" json:"updated_at"`                                                                             // 修改时间
	DeletedAt      *time.Time  `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                                                                                                       // 删除时间
}

// TableName SafeIpaddress's table name
func (*SafeIpaddress) TableName() string {
	return TableNameSafeIpaddress
}
