// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSafeTodayThreat = "safe_today_threat"

// SafeTodayThreat 今日威胁等级数量
type SafeTodayThreat struct {
	ID        uint64     `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	Date      time.Time  `gorm:"column:date;type:date;not null;comment:日期" json:"date"`                             // 日期
	High      uint       `gorm:"column:high;type:int unsigned;not null;comment:高危事件数量" json:"high"`                 // 高危事件数量
	Medium    uint       `gorm:"column:medium;type:int unsigned;not null;comment:中危事件数量" json:"medium"`             // 中危事件数量
	Low       uint       `gorm:"column:low;type:int unsigned;not null;comment:低危事件数量" json:"low"`                   // 低危事件数量
	CreatedAt time.Time  `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`           // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;comment:修改时间" json:"updated_at"`                    // 修改时间
	DeletedAt *time.Time `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                    // 删除时间
}

// TableName SafeTodayThreat's table name
func (*SafeTodayThreat) TableName() string {
	return TableNameSafeTodayThreat
}
