// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSafeDictionary = "safe_dictionary"

// SafeDictionary 标准字典
type SafeDictionary struct {
	ID        uint       `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"` // 主键
	ParentID  uint       `gorm:"column:parent_id;type:int unsigned;not null;comment:上级告警事件ID" json:"parent_id"`  // 上级告警事件ID
	EventType string     `gorm:"column:event_type;type:char(16);not null;comment:告警事件编码" json:"event_type"`      // 告警事件编码
	EventName string     `gorm:"column:event_name;type:varchar(30);not null;comment:告警事件名称" json:"event_name"`   // 告警事件名称
	Disabled  uint8      `gorm:"column:disabled;type:tinyint unsigned;not null;comment:禁用状态" json:"disabled"`    // 禁用状态
	CreatedAt time.Time  `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`        // 创建时间
	UpdatedAt *time.Time `gorm:"column:updated_at;type:datetime;comment:修改时间" json:"updated_at"`                 // 修改时间
	DeletedAt *time.Time `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                 // 删除时间
}

// TableName SafeDictionary's table name
func (*SafeDictionary) TableName() string {
	return TableNameSafeDictionary
}
