// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameSysConfigValue = "sys_config_value"

// SysConfigValue 配置内容信息
type SysConfigValue struct {
	ID        uint           `gorm:"column:id;type:int unsigned;primaryKey;autoIncrement:true;comment:主键" json:"id"`  // 主键
	ConfigID  uint32         `gorm:"column:config_id;type:mediumint unsigned;not null;comment:配置ID" json:"config_id"` // 配置ID
	Title     string         `gorm:"column:title;type:varchar(50);not null;comment:配置标题" json:"title"`                // 配置标题
	Code      string         `gorm:"column:code;type:varchar(60);not null;comment:配置编码" json:"code"`                  // 配置编码
	Value     string         `gorm:"column:value;type:text;not null;comment:配置值" json:"value"`                        // 配置值
	Options   datatypes.JSON `gorm:"column:options;type:json;not null;comment:配置项" json:"options"`                    // 配置项
	Type      string         `gorm:"column:type;type:varchar(32);not null;comment:配置类型" json:"type"`                  // 配置类型
	Sort      uint           `gorm:"column:sort;type:int unsigned;not null;comment:排序" json:"sort"`                   // 排序
	Note      string         `gorm:"column:note;type:varchar(120);not null;comment:配置说明" json:"note"`                 // 配置说明
	Disabled  uint8          `gorm:"column:disabled;type:tinyint unsigned;not null;comment:锁定状态" json:"disabled"`     // 锁定状态
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime;not null;comment:创建时间" json:"created_at"`         // 创建时间
	UpdatedAt *time.Time     `gorm:"column:updated_at;type:datetime;comment:修改时间" json:"updated_at"`                  // 修改时间
	DeletedAt *time.Time     `gorm:"column:deleted_at;type:datetime;comment:删除时间" json:"deleted_at"`                  // 删除时间
}

// TableName SysConfigValue's table name
func (*SysConfigValue) TableName() string {
	return TableNameSysConfigValue
}
