// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRegion = "sys_region"

// SysRegion 城市地区表
type SysRegion struct {
	Code       uint32 `gorm:"column:code;type:mediumint unsigned;primaryKey;uniqueIndex:unique_region_code,priority:1;comment:城市编码" json:"code"` // 城市编码
	Name       string `gorm:"column:name;type:varchar(255);not null;comment:城市名称" json:"name"`                                                   // 城市名称
	ParentCode uint32 `gorm:"column:parent_code;type:mediumint unsigned;not null;comment:上级城市" json:"parent_code"`                               // 上级城市
	Level      uint8  `gorm:"column:level;type:tinyint unsigned;not null;comment:城市等级" json:"level"`                                             // 城市等级
}

// TableName SysRegion's table name
func (*SysRegion) TableName() string {
	return TableNameSysRegion
}
