// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSafeTodayAlarm = "safe_today_alarm"

// SafeTodayAlarm mapped from table <safe_today_alarm>
type SafeTodayAlarm struct {
	ID        int64        `gorm:"column:id;type:BIGINT;primaryKey;comment:主键" json:"id"`                                                 // 主键
	Date      time.Time    `gorm:"column:date;type:DATE;not null;index:INDEX33555728,priority:1;comment:日期" json:"date"`                  // 日期
	EventType string       `gorm:"column:event_type;type:VARCHAR;not null;index:INDEX33555728,priority:2;comment:事件ID" json:"event_type"` // 事件ID
	Total     int64        `gorm:"column:total;type:BIGINT;not null;comment:事件数量" json:"total"`                                           // 事件数量
	CreatedAt time.Time    `gorm:"column:created_at;type:TIMESTAMP;not null;comment:创建时间" json:"created_at"`                              // 创建时间
	UpdatedAt sql.NullTime `gorm:"column:updated_at;type:TIMESTAMP;comment:修改时间" json:"updated_at"`                                       // 修改时间
	DeletedAt sql.NullTime `gorm:"column:deleted_at;type:TIMESTAMP;comment:删除时间" json:"deleted_at"`                                       // 删除时间
}

// TableName SafeTodayAlarm's table name
func (*SafeTodayAlarm) TableName() string {
	return TableNameSafeTodayAlarm
}
