// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSafeUts = "safe_uts"

// SafeUts mapped from table <safe_uts>
type SafeUts struct {
	ID                 int32        `gorm:"column:id;type:INTEGER;primaryKey;comment:主键" json:"id"`                                                                      // 主键
	PlatformID         int16        `gorm:"column:platform_id;type:SMALLINT;not null;comment:来源平台" json:"platform_id"`                                                   // 来源平台
	Title              string       `gorm:"column:title;type:VARCHAR;not null;comment:探针设备标题" json:"title"`                                                              // 探针设备标题
	Address            string       `gorm:"column:address;type:VARCHAR;not null;index:INDEX33555657,priority:1;comment:IP地址" json:"address"`                             // IP地址
	DeviceID           string       `gorm:"column:device_id;type:VARCHAR;not null;index:INDEX33555658,priority:1;comment:探针设备ID" json:"device_id"`                       // 探针设备ID
	KafkaTopic         string       `gorm:"column:kafka_topic;type:VARCHAR;not null;index:INDEX33555659,priority:1;comment:kafka主题" json:"kafka_topic"`                  // kafka主题
	ElasticIndex       string       `gorm:"column:elastic_index;type:VARCHAR;not null;comment:es索引" json:"elastic_index"`                                                // es索引
	ElasticDetailIndex string       `gorm:"column:elastic_detail_index;type:VARCHAR;not null;index:INDEX33555660,priority:1;comment:对应详情索引" json:"elastic_detail_index"` // 对应详情索引
	Sort               int32        `gorm:"column:sort;type:INT;not null;comment:探针设备排序" json:"sort"`                                                                    // 探针设备排序
	Disabled           int8         `gorm:"column:disabled;type:TINYINT;not null;comment:禁用状态" json:"disabled"`                                                          // 禁用状态
	CreatedAt          time.Time    `gorm:"column:created_at;type:DATETIME;not null;comment:创建时间" json:"created_at"`                                                     // 创建时间
	UpdatedAt          sql.NullTime `gorm:"column:updated_at;type:DATETIME;comment:修改时间" json:"updated_at"`                                                              // 修改时间
	DeletedAt          sql.NullTime `gorm:"column:deleted_at;type:DATETIME;comment:删除时间" json:"deleted_at"`                                                              // 删除时间
}

// TableName SafeUts's table name
func (*SafeUts) TableName() string {
	return TableNameSafeUts
}
