// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSafeTaskPlanUts = "safe_task_plan_uts"

// SafeTaskPlanUts mapped from table <safe_task_plan_uts>
type SafeTaskPlanUts struct {
	ID        int32          `gorm:"column:id;type:INT;primaryKey;comment:主键" json:"id"`                      // 主键
	UtsID     int32          `gorm:"column:uts_id;type:INT;not null;comment:探针ID" json:"uts_id"`              // 探针ID
	TaskID    int32          `gorm:"column:task_id;type:INT;not null;comment:任务id" json:"task_id"`            // 任务id
	Stime     time.Time      `gorm:"column:stime;type:DATETIME;not null;comment:开始时间" json:"stime"`           // 开始时间
	Etime     time.Time      `gorm:"column:etime;type:DATETIME;not null;comment:结束时间" json:"etime"`           // 结束时间
	Issued    int16          `gorm:"column:issued;type:SMALLINT;not null;comment:下发状态" json:"issued"`         // 下发状态
	Pcap      sql.NullString `gorm:"column:pcap;type:VARCHAR;comment:文件名称" json:"pcap"`                       // 文件名称
	CreatedAt time.Time      `gorm:"column:created_at;type:DATETIME;not null;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt sql.NullTime   `gorm:"column:updated_at;type:DATETIME;comment:修改时间" json:"updated_at"`          // 修改时间
	DeletedAt sql.NullTime   `gorm:"column:deleted_at;type:DATETIME;comment:删除时间" json:"deleted_at"`          // 删除时间
}

// TableName SafeTaskPlanUts's table name
func (*SafeTaskPlanUts) TableName() string {
	return TableNameSafeTaskPlanUts
}
