// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSafeDisposal = "safe_disposal"

// SafeDisposal mapped from table <safe_disposal>
type SafeDisposal struct {
	ID        int64        `gorm:"column:id;type:BIGINT;primaryKey;comment:主键" json:"id"`                       // 主键
	EventID   string       `gorm:"column:event_id;type:VARCHAR;not null;comment:事件ID" json:"event_id"`          // 事件ID
	Note      string       `gorm:"column:note;type:VARCHAR;not null;comment:处置说明" json:"note"`                  // 处置说明
	AdminID   int64        `gorm:"column:admin_id;type:BIGINT;not null;comment:处置人" json:"admin_id"`            // 处置人
	Status    int32        `gorm:"column:status;type:INT;not null;comment:处置审核状态" json:"status"`                // 处置审核状态
	Type      *int32       `gorm:"column:type;type:INT;not null;default:1;comment:处置类型1:DDOS 2:信安" json:"type"` // 处置类型1:DDOS 2:信安
	CreatedAt time.Time    `gorm:"column:created_at;type:TIMESTAMP;not null;comment:创建时间" json:"created_at"`    // 创建时间
	UpdatedAt sql.NullTime `gorm:"column:updated_at;type:TIMESTAMP;comment:修改时间" json:"updated_at"`             // 修改时间
	DeletedAt sql.NullTime `gorm:"column:deleted_at;type:TIMESTAMP;comment:删除时间" json:"deleted_at"`             // 删除时间
}

// TableName SafeDisposal's table name
func (*SafeDisposal) TableName() string {
	return TableNameSafeDisposal
}
