// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSafeUtsDdos = "safe_uts_ddos"

// SafeUtsDdos mapped from table <safe_uts_ddos>
type SafeUtsDdos struct {
	ID         int32     `gorm:"column:id;type:INT;primaryKey;comment:主键" json:"id"`                       // 主键
	AddressID  int64     `gorm:"column:address_id;type:BIGINT;not null;comment:受攻击目标" json:"address_id"`   // 受攻击目标
	Sip        string    `gorm:"column:sip;type:CLOB;not null;comment:攻击来源IP" json:"sip"`                  // 攻击来源IP
	StartTime  int32     `gorm:"column:start_time;type:INT;not null;comment:开始攻击时间" json:"start_time"`     // 开始攻击时间
	StopTime   int32     `gorm:"column:stop_time;type:INT;not null;comment:结束攻击时间" json:"stop_time"`       // 结束攻击时间
	Domestic   int8      `gorm:"column:domestic;type:TINYINT;not null;comment:是否境内攻击" json:"domestic"`     // 是否境内攻击
	Duration   int32     `gorm:"column:duration;type:INT;not null;comment:攻击时长单位:秒" json:"duration"`       // 攻击时长单位:秒
	AttackType string    `gorm:"column:attack_type;type:VARCHAR;not null;comment:攻击类型" json:"attack_type"` // 攻击类型
	CreatedAt  time.Time `gorm:"column:created_at;type:DATETIME;not null;comment:创建时间" json:"created_at"`  // 创建时间
}

// TableName SafeUtsDdos's table name
func (*SafeUtsDdos) TableName() string {
	return TableNameSafeUtsDdos
}
