// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSafeEventLogs = "safe_event_logs"

// SafeEventLogs mapped from table <safe_event_logs>
type SafeEventLogs struct {
	ID         int64        `gorm:"column:id;type:BIGINT;primaryKey;comment:主键" json:"id"`                     // 主键
	Date       time.Time    `gorm:"column:date;type:DATE;not null;comment:日期" json:"date"`                     // 日期
	EventType  string       `gorm:"column:event_type;type:VARCHAR;not null;comment:所属事件" json:"event_type"`    // 所属事件
	PlatformID int64        `gorm:"column:platform_id;type:BIGINT;not null;comment:来源平台ID" json:"platform_id"` // 来源平台ID
	Total      int32        `gorm:"column:total;type:INT;not null;comment:总计数量" json:"total"`                  // 总计数量
	Successed  int32        `gorm:"column:successed;type:INT;not null;comment:成功数量" json:"successed"`          // 成功数量
	Failed     int32        `gorm:"column:failed;type:INT;not null;comment:失败数量" json:"failed"`                // 失败数量
	CreatedAt  time.Time    `gorm:"column:created_at;type:TIMESTAMP;not null;comment:创建时间" json:"created_at"`  // 创建时间
	UpdatedAt  sql.NullTime `gorm:"column:updated_at;type:TIMESTAMP;comment:修改时间" json:"updated_at"`           // 修改时间
	DeletedAt  sql.NullTime `gorm:"column:deleted_at;type:TIMESTAMP;comment:删除时间" json:"deleted_at"`           // 删除时间
}

// TableName SafeEventLogs's table name
func (*SafeEventLogs) TableName() string {
	return TableNameSafeEventLogs
}
