// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSafeDictionary = "safe_dictionary"

// SafeDictionary mapped from table <safe_dictionary>
type SafeDictionary struct {
	ID        int64        `gorm:"column:id;type:BIGINT;primaryKey;comment:主键" json:"id"`                    // 主键
	ParentID  int64        `gorm:"column:parent_id;type:BIGINT;not null;comment:上级告警事件ID" json:"parent_id"`  // 上级告警事件ID
	EventType string       `gorm:"column:event_type;type:VARCHAR;not null;comment:告警事件编码" json:"event_type"` // 告警事件编码
	EventName string       `gorm:"column:event_name;type:VARCHAR;not null;comment:告警事件名称" json:"event_name"` // 告警事件名称
	Disabled  int32        `gorm:"column:disabled;type:INT;not null;comment:禁用状态" json:"disabled"`           // 禁用状态
	CreatedAt time.Time    `gorm:"column:created_at;type:TIMESTAMP;not null;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt sql.NullTime `gorm:"column:updated_at;type:TIMESTAMP;comment:修改时间" json:"updated_at"`          // 修改时间
	DeletedAt sql.NullTime `gorm:"column:deleted_at;type:TIMESTAMP;comment:删除时间" json:"deleted_at"`          // 删除时间
}

// TableName SafeDictionary's table name
func (*SafeDictionary) TableName() string {
	return TableNameSafeDictionary
}
