// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSafeUtsInfo = "safe_uts_info"

// SafeUtsInfo mapped from table <safe_uts_info>
type SafeUtsInfo struct {
	UtsID     int32        `gorm:"column:uts_id;type:INTEGER;primaryKey;comment:探针id" json:"uts_id"`        // 探针id
	CPU       string       `gorm:"column:cpu;type:CLOB;not null;comment:cpu信息" json:"cpu"`                  // cpu信息
	RAM       string       `gorm:"column:ram;type:CLOB;not null;comment:内存信息" json:"ram"`                   // 内存信息
	Disk      string       `gorm:"column:disk;type:CLOB;not null;comment:磁盘信息" json:"disk"`                 // 磁盘信息
	CreatedAt time.Time    `gorm:"column:created_at;type:DATETIME;not null;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt sql.NullTime `gorm:"column:updated_at;type:DATETIME;comment:修改时间" json:"updated_at"`          // 修改时间
}

// TableName SafeUtsInfo's table name
func (*SafeUtsInfo) TableName() string {
	return TableNameSafeUtsInfo
}
