// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSysAdmin = "sys_admin"

// SysAdmin mapped from table <sys_admin>
type SysAdmin struct {
	ID        int64        `gorm:"column:id;type:BIGINT;primaryKey;comment:主键" json:"id"`                                           // 主键
	RoleID    int64        `gorm:"column:role_id;type:BIGINT;not null;comment:角色 id" json:"role_id"`                                // 角色 id
	Name      string       `gorm:"column:name;type:VARCHAR;not null;comment:用户姓名" json:"name"`                                      // 用户姓名
	Portrait  string       `gorm:"column:portrait;type:VARCHAR;not null;comment:用户头像" json:"portrait"`                              // 用户头像
	Account   string       `gorm:"column:account;type:VARCHAR;not null;index:INDEX33555516,priority:1;comment:登录账号" json:"account"` // 登录账号
	Password  string       `gorm:"column:password;type:VARCHAR;not null;comment:登录密码" json:"password"`                              // 登录密码
	Method    string       `gorm:"column:method;type:VARCHAR;not null;comment:密码加密方法" json:"method"`                                // 密码加密方法
	Salt      string       `gorm:"column:salt;type:VARCHAR;not null;comment:认证器密钥" json:"salt"`                                     // 认证器密钥
	Disabled  int32        `gorm:"column:disabled;type:INT;not null;comment:用户锁定状态" json:"disabled"`                                // 用户锁定状态
	CreatedAt time.Time    `gorm:"column:created_at;type:TIMESTAMP;not null;comment:创建时间" json:"created_at"`                        // 创建时间
	UpdatedAt time.Time    `gorm:"column:updated_at;type:TIMESTAMP;not null;comment:修改时间" json:"updated_at"`                        // 修改时间
	DeletedAt sql.NullTime `gorm:"column:deleted_at;type:TIMESTAMP;comment:删除时间" json:"deleted_at"`                                 // 删除时间
}

// TableName SysAdmin's table name
func (*SysAdmin) TableName() string {
	return TableNameSysAdmin
}
