// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSysRole = "sys_role"

// SysRole mapped from table <sys_role>
type SysRole struct {
	ID          int64        `gorm:"column:id;type:BIGINT;primaryKey;comment:主键" json:"id"`                                     // 主键
	Title       string       `gorm:"column:title;type:VARCHAR;not null;comment:角色名称" json:"title"`                              // 角色名称
	Name        string       `gorm:"column:name;type:VARCHAR;not null;index:INDEX33555515,priority:1;comment:调用名称" json:"name"` // 调用名称
	Description string       `gorm:"column:description;type:VARCHAR;not null;comment:描述信息" json:"description"`                  // 描述信息
	Rules       string       `gorm:"column:rules;type:VARCHAR;not null;comment:角色允许访问" json:"rules"`                            // 角色允许访问
	Sort        int64        `gorm:"column:sort;type:BIGINT;not null;comment:排序" json:"sort"`                                   // 排序
	Disabled    int32        `gorm:"column:disabled;type:INT;not null;comment:角色状态" json:"disabled"`                            // 角色状态
	CreatedAt   time.Time    `gorm:"column:created_at;type:TIMESTAMP;not null;comment:创建时间" json:"created_at"`                  // 创建时间
	UpdatedAt   sql.NullTime `gorm:"column:updated_at;type:TIMESTAMP;comment:修改时间" json:"updated_at"`                           // 修改时间
	DeletedAt   sql.NullTime `gorm:"column:deleted_at;type:TIMESTAMP;comment:删除时间" json:"deleted_at"`                           // 删除时间
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
