// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"database/sql"
	"time"
)

const TableNameSysAlbumCategory = "sys_album_category"

// SysAlbumCategory mapped from table <sys_album_category>
type SysAlbumCategory struct {
	ID        int64        `gorm:"column:id;type:BIGINT;not null;comment:主键ID" json:"id"`                           // 主键ID
	Pid       int64        `gorm:"column:pid;type:BIGINT;not null;comment:父级ID" json:"pid"`                         // 父级ID
	Type      *int32       `gorm:"column:type;type:INT;not null;default:10;comment:类型: [10=图片, 20=视频]" json:"type"` // 类型: [10=图片, 20=视频]
	Name      string       `gorm:"column:name;type:VARCHAR;not null;comment:分类名称" json:"name"`                      // 分类名称
	CreatedAt time.Time    `gorm:"column:created_at;type:TIMESTAMP;not null;comment:创建时间" json:"created_at"`        // 创建时间
	UpdatedAt sql.NullTime `gorm:"column:updated_at;type:TIMESTAMP;comment:更新时间" json:"updated_at"`                 // 更新时间
	DeletedAt sql.NullTime `gorm:"column:deleted_at;type:TIMESTAMP;comment:删除时间" json:"deleted_at"`                 // 删除时间
}

// TableName SysAlbumCategory's table name
func (*SysAlbumCategory) TableName() string {
	return TableNameSysAlbumCategory
}
