driver = 'mysql'
dsn = 'root:123.com@tcp(127.0.0.1:3306)/safes?charset=utf8mb4&parseTime=True&loc=Local'
out_dir = 'generated'
model_out = 'data-layer/models'
query_out = 'data-layer/query'
validator_out = 'data-layer/request'
validator_package = 'request'
tables = ['sys_action_log', 'sys_admin', 'sys_admin_profile', 'sys_album', 'sys_album_category', 'sys_config', 'sys_config_value', 'sys_dictionaries', 'sys_dictionary', 'sys_region', 'sys_role', 'sys_rule']
table_prefix = 'sys_'
ignore_fields = ['created_at', 'updated_at', 'deleted_at']
tags = ['json', 'form', 'xml', 'url']
insert_scene = 'insert'
update_scene = 'update'
delete_scene = 'delete'

[type_mappings]
[type_mappings.jsonb]
db_type = 'jsonb'
go_type = 'datatypes.JSON'
import_path = 'gorm.io/datatypes'

[type_mappings.uuid]
db_type = 'uuid'
go_type = 'uuid.UUID'
import_path = 'github.com/google/uuid'

[table_configs]
[table_configs.safe_company]
[table_configs.safe_company.fields]
[table_configs.safe_company.fields.created_at]
go_type = 'calendar.Datetime'
import_path = 'github.com/chaodoing/pkg/calendar'

[table_configs.safe_company.fields.deleted_at]
go_type = 'gorm.DeletedAt'
import_path = 'gorm.io/gorm'

[table_configs.safe_company.fields.updated_at]
go_type = '*calendar.Datetime'
import_path = 'github.com/chaodoing/pkg/calendar'

[table_configs.sys_admin]
[table_configs.sys_admin.fields]
[table_configs.sys_admin.fields.created_at]
go_type = 'calendar.Datetime'
import_path = 'github.com/chaodoing/pkg/calendar'

[table_configs.sys_admin.fields.deleted_at]
go_type = 'gorm.DeletedAt'
import_path = 'gorm.io/gorm'

[table_configs.sys_admin.fields.updated_at]
go_type = '*calendar.Datetime'
import_path = 'github.com/chaodoing/pkg/calendar'
