// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDepartmentOperators = "department_operators"

// DepartmentOperators mapped from table <department_operators>
type DepartmentOperators struct {
	DepartmentID int    `gorm:"column:department_id;type:integer;primaryKey;index:idx_department_operators_department_id,priority:1;comment:部门ID" json:"department_id"` // 部门ID
	Operator     string `gorm:"column:operator;type:character varying(50);primaryKey;comment:运营商" json:"operator"`                                                      // 运营商
}

// TableName DepartmentOperators's table name
func (*DepartmentOperators) TableName() string {
	return TableNameDepartmentOperators
}
