// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/datatypes"
)

const TableNameMassSpeeds = "mass_speeds"

// MassSpeeds mapped from table <mass_speeds>
type MassSpeeds struct {
	TestID   int64          `gorm:"column:test_id;type:bigint;primaryKey;index:idx_mass_speeds_test_id,priority:1;comment:众测ID" json:"test_id"` // 众测ID
	Upload   datatypes.JSON `gorm:"column:upload;type:jsonb;not null;comment:上传速率" json:"upload"`                                               // 上传速率
	Download datatypes.JSON `gorm:"column:download;type:jsonb;not null;comment:下载速率" json:"download"`                                           // 下载速率
}

// TableName MassSpeeds's table name
func (*MassSpeeds) TableName() string {
	return TableNameMassSpeeds
}
