// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMassServer = "mass_server"

// MassServer mapped from table <mass_server>
type MassServer struct {
	TestID      int64  `gorm:"column:test_id;type:bigint;primaryKey;index:idx_mass_server_test_id,priority:1;comment:众测ID" json:"test_id"` // 众测ID
	DlLoaded    int    `gorm:"column:dl_loaded;type:integer;not null;comment:下行已接收数据量" json:"dl_loaded"`                                   // 下行已接收数据量
	UlLoaded    int    `gorm:"column:ul_loaded;type:integer;not null;comment:上行已发送数据量" json:"ul_loaded"`                                   // 上行已发送数据量
	IPAddress   string `gorm:"column:ip_address;type:character varying(100);not null;comment:IP地址" json:"ip_address"`                      // IP地址
	VersionCode int16  `gorm:"column:version_code;type:smallint;not null;comment:App内部版本号" json:"version_code"`                            // App内部版本号
	VersionName string `gorm:"column:version_name;type:character varying(20);not null;comment:App展示版本号" json:"version_name"`               // App展示版本号
}

// TableName MassServer's table name
func (*MassServer) TableName() string {
	return TableNameMassServer
}
