// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameOperateLog = "operate_log"

// OperateLog mapped from table <operate_log>
type OperateLog struct {
	ID        int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"id"`                      // 主键
	Method    string         `gorm:"column:method;type:character varying(10);not null;comment:请求方式" json:"method"`                  // 请求方式
	Path      string         `gorm:"column:path;type:character varying(255);not null;comment:请求地址" json:"path"`                     // 请求地址
	Enctype   string         `gorm:"column:enctype;type:character varying(60);not null;comment:表单类型" json:"enctype"`                // 表单类型
	Query     string         `gorm:"column:query;type:character varying(255);not null;comment:请求url参数" json:"query"`                // 请求url参数
	Body      datatypes.JSON `gorm:"column:body;type:jsonb;not null;comment:请求内容" json:"body"`                                      // 请求内容
	Remote    string         `gorm:"column:remote;type:character varying(60);not null;comment:远程地址" json:"remote"`                  // 远程地址
	UID       int64          `gorm:"column:uid;type:bigint;not null;comment:用户id" json:"uid"`                                       // 用户id
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp(6) without time zone;not null;comment:创建时间" json:"created_at"` // 创建时间
}

// TableName OperateLog's table name
func (*OperateLog) TableName() string {
	return TableNameOperateLog
}
