// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePlaceContents = "place_contents"

// PlaceContents mapped from table <place_contents>
type PlaceContents struct {
	PlaceListID int   `gorm:"column:place_list_id;type:integer;primaryKey;index:idx_place_contents_place_list_id,priority:1;comment:清单ID" json:"place_list_id"` // 清单ID
	PlaceID     int64 `gorm:"column:place_id;type:bigint;primaryKey;index:idx_place_contents_place_id,priority:1;comment:场所ID" json:"place_id"`                 // 场所ID
}

// TableName PlaceContents's table name
func (*PlaceContents) TableName() string {
	return TableNamePlaceContents
}
