// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePlaces = "places"

// Places mapped from table <places>
type Places struct {
	ID          int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:主键" json:"id"`                                   // 主键
	ZoneCode    int        `gorm:"column:zone_code;type:integer;not null;index:idx_places_zone_code,priority:1;comment:地区编码" json:"zone_code"` // 地区编码
	SceneID     int        `gorm:"column:scene_id;type:integer;not null;index:idx_places_scene_id,priority:1;comment:地点场景ID" json:"scene_id"`  // 地点场景ID
	Name        string     `gorm:"column:name;type:character varying(50);not null;comment:场景名称" json:"name"`                                   // 场景名称
	Address     string     `gorm:"column:address;type:character varying(80);not null;comment:场景具体地址" json:"address"`                           // 场景具体地址
	Longitude   float64    `gorm:"column:longitude;type:double precision;not null;comment:经度" json:"longitude"`                                // 经度
	Latitude    float64    `gorm:"column:latitude;type:double precision;not null;comment:维度" json:"latitude"`                                  // 维度
	Description string     `gorm:"column:description;type:character varying(60);not null;comment:描述信息" json:"description"`                     // 描述信息
	Disabled    bool       `gorm:"column:disabled;type:boolean;not null;comment:禁用状态" json:"disabled"`                                         // 禁用状态
	PingCount   int16      `gorm:"column:ping_count;type:smallint;not null;comment:测试次数" json:"ping_count"`                                    // 测试次数
	CreatedAt   time.Time  `gorm:"column:created_at;type:timestamp(6) without time zone;not null;comment:创建时间" json:"created_at"`              // 创建时间
	UpdatedAt   time.Time  `gorm:"column:updated_at;type:timestamp(6) without time zone;not null;comment:修改时间" json:"updated_at"`              // 修改时间
	DeletedAt   *time.Time `gorm:"column:deleted_at;type:timestamp(6) without time zone;comment:删除时间" json:"deleted_at"`                       // 删除时间
}

// TableName Places's table name
func (*Places) TableName() string {
	return TableNamePlaces
}
