// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
)

const TableNameRoadSections = "road_sections"

// RoadSections mapped from table <road_sections>
type RoadSections struct {
	ID          int64          `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true;comment:道路路段" json:"id"`                                   // 道路路段
	RoadID      int64          `gorm:"column:road_id;type:bigint;not null;index:idx_road_sections_road_id,priority:1;comment:所属道路ID" json:"road_id"` // 所属道路ID
	Name        string         `gorm:"column:name;type:character varying(50);not null;comment:路段名称" json:"name"`                                     // 路段名称
	Sequence    int16          `gorm:"column:sequence;type:smallint;not null;comment:路段序号" json:"sequence"`                                          // 路段序号
	Routes      datatypes.JSON `gorm:"column:routes;type:jsonb;not null;comment:途径点" json:"routes"`                                                  // 途径点
	Length      float32        `gorm:"column:length;type:real;not null;comment:路段长度(km)" json:"length"`                                              // 路段长度(km)
	Description string         `gorm:"column:description;type:character varying(100);not null;comment:路段描述" json:"description"`                      // 路段描述
	CreatedAt   time.Time      `gorm:"column:created_at;type:timestamp(6) without time zone;not null;comment:创建时间" json:"created_at"`                // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;type:timestamp(6) without time zone;not null;comment:修改时间" json:"updated_at"`                // 修改时间
	DeletedAt   *time.Time     `gorm:"column:deleted_at;type:timestamp(6) without time zone;comment:删除时间" json:"deleted_at"`                         // 删除时间
}

// TableName RoadSections's table name
func (*RoadSections) TableName() string {
	return TableNameRoadSections
}
