// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameRoles = "roles"

// Roles mapped from table <roles>
type Roles struct {
	ID          int        `gorm:"column:id;type:integer;primaryKey;autoIncrement:true;comment:主键" json:"id"`                     // 主键
	Title       string     `gorm:"column:title;type:character varying(60);not null;comment:角色名称" json:"title"`                    // 角色名称
	Name        string     `gorm:"column:name;type:character varying(60);not null;comment:调用名称" json:"name"`                      // 调用名称
	Description string     `gorm:"column:description;type:character varying(120);not null;comment:描述信息" json:"description"`       // 描述信息
	Sort        int        `gorm:"column:sort;type:integer;not null;comment:排序" json:"sort"`                                      // 排序
	Disabled    int16      `gorm:"column:disabled;type:smallint;not null;comment:角色状态" json:"disabled"`                           // 角色状态
	CreatedAt   time.Time  `gorm:"column:created_at;type:timestamp(6) without time zone;not null;comment:创建时间" json:"created_at"` // 创建时间
	UpdatedAt   time.Time  `gorm:"column:updated_at;type:timestamp(6) without time zone;not null;comment:修改时间" json:"updated_at"` // 修改时间
	DeletedAt   *time.Time `gorm:"column:deleted_at;type:timestamp(6) without time zone;comment:删除时间" json:"deleted_at"`          // 删除时间
}

// TableName Roles's table name
func (*Roles) TableName() string {
	return TableNameRoles
}
