// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRolePermissions = "role_permissions"

// RolePermissions mapped from table <role_permissions>
type RolePermissions struct {
	RoleID int `gorm:"column:role_id;type:integer;primaryKey;index:idx_role_permissions_role_id,priority:1;comment:角色ID" json:"role_id"` // 角色ID
	RuleID int `gorm:"column:rule_id;type:integer;primaryKey;index:idx_role_permissions_rule_id,priority:1;comment:规则ID" json:"rule_id"` // 规则ID
}

// TableName RolePermissions's table name
func (*RolePermissions) TableName() string {
	return TableNameRolePermissions
}
