// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"gorm.io/datatypes"
)

const TableNameSpecializedSpeeds = "specialized_speeds"

// SpecializedSpeeds mapped from table <specialized_speeds>
type SpecializedSpeeds struct {
	TestID   int64          `gorm:"column:test_id;type:bigint;primaryKey;index:idx_specialized_speeds_test_id,priority:1;comment:专项测试ID" json:"test_id"` // 专项测试ID
	Upload   datatypes.JSON `gorm:"column:upload;type:jsonb;not null;comment:上传速率" json:"upload"`                                                        // 上传速率
	Download datatypes.JSON `gorm:"column:download;type:jsonb;not null;comment:下载速率" json:"download"`                                                    // 下载速率
}

// TableName SpecializedSpeeds's table name
func (*SpecializedSpeeds) TableName() string {
	return TableNameSpecializedSpeeds
}
