// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTaskPlaces = "task_places"

// TaskPlaces mapped from table <task_places>
type TaskPlaces struct {
	TaskID        int        `gorm:"column:task_id;type:integer;primaryKey;index:idx_task_places_task_id,priority:1;comment:任务ID" json:"task_id"`   // 任务ID
	PlaceID       int64      `gorm:"column:place_id;type:bigint;primaryKey;index:idx_task_places_place_id,priority:1;comment:场所ID" json:"place_id"` // 场所ID
	PingCount     int16      `gorm:"column:ping_count;type:smallint;not null;comment:场所测试次数" json:"ping_count"`                                     // 场所测试次数
	CompleteCount int16      `gorm:"column:complete_count;type:smallint;not null;comment:完成次数" json:"complete_count"`                               // 完成次数
	CompletedAt   *time.Time `gorm:"column:completed_at;type:timestamp(6) without time zone;comment:完成时间" json:"completed_at"`                      // 完成时间
	CreatedAt     time.Time  `gorm:"column:created_at;type:timestamp(6) without time zone;not null;comment:创建时间" json:"created_at"`                 // 创建时间
	UpdatedAt     time.Time  `gorm:"column:updated_at;type:timestamp(6) without time zone;not null;comment:修改时间" json:"updated_at"`                 // 修改时间
}

// TableName TaskPlaces's table name
func (*TaskPlaces) TableName() string {
	return TableNameTaskPlaces
}
