// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTaskNetworkTypes = "task_network_types"

// TaskNetworkTypes mapped from table <task_network_types>
type TaskNetworkTypes struct {
	TaskID      int    `gorm:"column:task_id;type:integer;primaryKey;index:idx_task_network_types_task_id,priority:1;comment:任务id" json:"task_id"` // 任务id
	NetworkType string `gorm:"column:network_type;type:character varying(50);primaryKey;comment:需要测试的网络类型" json:"network_type"`                    // 需要测试的网络类型
}

// TableName TaskNetworkTypes's table name
func (*TaskNetworkTypes) TableName() string {
	return TableNameTaskNetworkTypes
}
