// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newDepartments(db *gorm.DB, opts ...gen.DOOption) departments {
	_departments := departments{}

	_departments.departmentsDo.UseDB(db, opts...)
	_departments.departmentsDo.UseModel(&model.Departments{})

	tableName := _departments.departmentsDo.TableName()
	_departments.ALL = field.NewAsterisk(tableName)
	_departments.ID = field.NewInt(tableName, "id")
	_departments.ParentID = field.NewInt(tableName, "parent_id")
	_departments.LeaderAdminID = field.NewInt(tableName, "leader_admin_id")
	_departments.RoleID = field.NewInt(tableName, "role_id")
	_departments.Name = field.NewString(tableName, "name")
	_departments.Path = field.NewString(tableName, "path")
	_departments.Level = field.NewInt(tableName, "level")
	_departments.Sort = field.NewInt(tableName, "sort")
	_departments.Disabled = field.NewBool(tableName, "disabled")
	_departments.CreatedAt = field.NewTime(tableName, "created_at")
	_departments.UpdatedAt = field.NewTime(tableName, "updated_at")
	_departments.DeletedAt = field.NewTime(tableName, "deleted_at")

	_departments.fillFieldMap()

	return _departments
}

type departments struct {
	departmentsDo

	ALL           field.Asterisk
	ID            field.Int    // 部门ID
	ParentID      field.Int    // 上级部门ID
	LeaderAdminID field.Int    // 部门后台负责人
	RoleID        field.Int    // 角色id
	Name          field.String // 部门名称
	Path          field.String // 部门层级路径
	Level         field.Int    // 部门层级
	Sort          field.Int    // 部门排序
	Disabled      field.Bool   // 禁用状态
	CreatedAt     field.Time   // 创建时间
	UpdatedAt     field.Time   // 修改时间
	DeletedAt     field.Time   // 删除时间

	fieldMap map[string]field.Expr
}

func (d departments) Table(newTableName string) *departments {
	d.departmentsDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d departments) As(alias string) *departments {
	d.departmentsDo.DO = *(d.departmentsDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *departments) updateTableName(table string) *departments {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt(table, "id")
	d.ParentID = field.NewInt(table, "parent_id")
	d.LeaderAdminID = field.NewInt(table, "leader_admin_id")
	d.RoleID = field.NewInt(table, "role_id")
	d.Name = field.NewString(table, "name")
	d.Path = field.NewString(table, "path")
	d.Level = field.NewInt(table, "level")
	d.Sort = field.NewInt(table, "sort")
	d.Disabled = field.NewBool(table, "disabled")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DeletedAt = field.NewTime(table, "deleted_at")

	d.fillFieldMap()

	return d
}

func (d *departments) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *departments) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 12)
	d.fieldMap["id"] = d.ID
	d.fieldMap["parent_id"] = d.ParentID
	d.fieldMap["leader_admin_id"] = d.LeaderAdminID
	d.fieldMap["role_id"] = d.RoleID
	d.fieldMap["name"] = d.Name
	d.fieldMap["path"] = d.Path
	d.fieldMap["level"] = d.Level
	d.fieldMap["sort"] = d.Sort
	d.fieldMap["disabled"] = d.Disabled
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["deleted_at"] = d.DeletedAt
}

func (d departments) clone(db *gorm.DB) departments {
	d.departmentsDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d departments) replaceDB(db *gorm.DB) departments {
	d.departmentsDo.ReplaceDB(db)
	return d
}

type departmentsDo struct{ gen.DO }

type IDepartmentsDo interface {
	gen.SubQuery
	Debug() IDepartmentsDo
	WithContext(ctx context.Context) IDepartmentsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDepartmentsDo
	WriteDB() IDepartmentsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDepartmentsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDepartmentsDo
	Not(conds ...gen.Condition) IDepartmentsDo
	Or(conds ...gen.Condition) IDepartmentsDo
	Select(conds ...field.Expr) IDepartmentsDo
	Where(conds ...gen.Condition) IDepartmentsDo
	Order(conds ...field.Expr) IDepartmentsDo
	Distinct(cols ...field.Expr) IDepartmentsDo
	Omit(cols ...field.Expr) IDepartmentsDo
	Join(table schema.Tabler, on ...field.Expr) IDepartmentsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDepartmentsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDepartmentsDo
	Group(cols ...field.Expr) IDepartmentsDo
	Having(conds ...gen.Condition) IDepartmentsDo
	Limit(limit int) IDepartmentsDo
	Offset(offset int) IDepartmentsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDepartmentsDo
	Unscoped() IDepartmentsDo
	Create(values ...*model.Departments) error
	CreateInBatches(values []*model.Departments, batchSize int) error
	Save(values ...*model.Departments) error
	First() (*model.Departments, error)
	Take() (*model.Departments, error)
	Last() (*model.Departments, error)
	Find() ([]*model.Departments, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Departments, err error)
	FindInBatches(result *[]*model.Departments, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Departments) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDepartmentsDo
	Assign(attrs ...field.AssignExpr) IDepartmentsDo
	Joins(fields ...field.RelationField) IDepartmentsDo
	Preload(fields ...field.RelationField) IDepartmentsDo
	FirstOrInit() (*model.Departments, error)
	FirstOrCreate() (*model.Departments, error)
	FindByPage(offset int, limit int) (result []*model.Departments, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDepartmentsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d departmentsDo) Debug() IDepartmentsDo {
	return d.withDO(d.DO.Debug())
}

func (d departmentsDo) WithContext(ctx context.Context) IDepartmentsDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d departmentsDo) ReadDB() IDepartmentsDo {
	return d.Clauses(dbresolver.Read)
}

func (d departmentsDo) WriteDB() IDepartmentsDo {
	return d.Clauses(dbresolver.Write)
}

func (d departmentsDo) Session(config *gorm.Session) IDepartmentsDo {
	return d.withDO(d.DO.Session(config))
}

func (d departmentsDo) Clauses(conds ...clause.Expression) IDepartmentsDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d departmentsDo) Returning(value interface{}, columns ...string) IDepartmentsDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d departmentsDo) Not(conds ...gen.Condition) IDepartmentsDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d departmentsDo) Or(conds ...gen.Condition) IDepartmentsDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d departmentsDo) Select(conds ...field.Expr) IDepartmentsDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d departmentsDo) Where(conds ...gen.Condition) IDepartmentsDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d departmentsDo) Order(conds ...field.Expr) IDepartmentsDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d departmentsDo) Distinct(cols ...field.Expr) IDepartmentsDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d departmentsDo) Omit(cols ...field.Expr) IDepartmentsDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d departmentsDo) Join(table schema.Tabler, on ...field.Expr) IDepartmentsDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d departmentsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDepartmentsDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d departmentsDo) RightJoin(table schema.Tabler, on ...field.Expr) IDepartmentsDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d departmentsDo) Group(cols ...field.Expr) IDepartmentsDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d departmentsDo) Having(conds ...gen.Condition) IDepartmentsDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d departmentsDo) Limit(limit int) IDepartmentsDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d departmentsDo) Offset(offset int) IDepartmentsDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d departmentsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDepartmentsDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d departmentsDo) Unscoped() IDepartmentsDo {
	return d.withDO(d.DO.Unscoped())
}

func (d departmentsDo) Create(values ...*model.Departments) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d departmentsDo) CreateInBatches(values []*model.Departments, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d departmentsDo) Save(values ...*model.Departments) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d departmentsDo) First() (*model.Departments, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Departments), nil
	}
}

func (d departmentsDo) Take() (*model.Departments, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Departments), nil
	}
}

func (d departmentsDo) Last() (*model.Departments, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Departments), nil
	}
}

func (d departmentsDo) Find() ([]*model.Departments, error) {
	result, err := d.DO.Find()
	return result.([]*model.Departments), err
}

func (d departmentsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Departments, err error) {
	buf := make([]*model.Departments, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d departmentsDo) FindInBatches(result *[]*model.Departments, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d departmentsDo) Attrs(attrs ...field.AssignExpr) IDepartmentsDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d departmentsDo) Assign(attrs ...field.AssignExpr) IDepartmentsDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d departmentsDo) Joins(fields ...field.RelationField) IDepartmentsDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d departmentsDo) Preload(fields ...field.RelationField) IDepartmentsDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d departmentsDo) FirstOrInit() (*model.Departments, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Departments), nil
	}
}

func (d departmentsDo) FirstOrCreate() (*model.Departments, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Departments), nil
	}
}

func (d departmentsDo) FindByPage(offset int, limit int) (result []*model.Departments, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d departmentsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d departmentsDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d departmentsDo) Delete(models ...*model.Departments) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *departmentsDo) withDO(do gen.Dao) *departmentsDo {
	d.DO = *do.(*gen.DO)
	return d
}
