// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newDictOptions(db *gorm.DB, opts ...gen.DOOption) dictOptions {
	_dictOptions := dictOptions{}

	_dictOptions.dictOptionsDo.UseDB(db, opts...)
	_dictOptions.dictOptionsDo.UseModel(&model.DictOptions{})

	tableName := _dictOptions.dictOptionsDo.TableName()
	_dictOptions.ALL = field.NewAsterisk(tableName)
	_dictOptions.ID = field.NewInt(tableName, "id")
	_dictOptions.DictID = field.NewInt(tableName, "dict_id")
	_dictOptions.Title = field.NewString(tableName, "title")
	_dictOptions.Value = field.NewString(tableName, "value")
	_dictOptions.Sort = field.NewInt(tableName, "sort")
	_dictOptions.Disabled = field.NewInt16(tableName, "disabled")
	_dictOptions.CreatedAt = field.NewTime(tableName, "created_at")
	_dictOptions.UpdatedAt = field.NewTime(tableName, "updated_at")
	_dictOptions.DeletedAt = field.NewTime(tableName, "deleted_at")

	_dictOptions.fillFieldMap()

	return _dictOptions
}

type dictOptions struct {
	dictOptionsDo

	ALL       field.Asterisk
	ID        field.Int    // 主键
	DictID    field.Int    // 字典类型id
	Title     field.String // 字典名称
	Value     field.String // 字典内容
	Sort      field.Int    // 显示顺序
	Disabled  field.Int16  // 禁用状态
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 修改时间
	DeletedAt field.Time   // 删除时间

	fieldMap map[string]field.Expr
}

func (d dictOptions) Table(newTableName string) *dictOptions {
	d.dictOptionsDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d dictOptions) As(alias string) *dictOptions {
	d.dictOptionsDo.DO = *(d.dictOptionsDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *dictOptions) updateTableName(table string) *dictOptions {
	d.ALL = field.NewAsterisk(table)
	d.ID = field.NewInt(table, "id")
	d.DictID = field.NewInt(table, "dict_id")
	d.Title = field.NewString(table, "title")
	d.Value = field.NewString(table, "value")
	d.Sort = field.NewInt(table, "sort")
	d.Disabled = field.NewInt16(table, "disabled")
	d.CreatedAt = field.NewTime(table, "created_at")
	d.UpdatedAt = field.NewTime(table, "updated_at")
	d.DeletedAt = field.NewTime(table, "deleted_at")

	d.fillFieldMap()

	return d
}

func (d *dictOptions) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *dictOptions) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 9)
	d.fieldMap["id"] = d.ID
	d.fieldMap["dict_id"] = d.DictID
	d.fieldMap["title"] = d.Title
	d.fieldMap["value"] = d.Value
	d.fieldMap["sort"] = d.Sort
	d.fieldMap["disabled"] = d.Disabled
	d.fieldMap["created_at"] = d.CreatedAt
	d.fieldMap["updated_at"] = d.UpdatedAt
	d.fieldMap["deleted_at"] = d.DeletedAt
}

func (d dictOptions) clone(db *gorm.DB) dictOptions {
	d.dictOptionsDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d dictOptions) replaceDB(db *gorm.DB) dictOptions {
	d.dictOptionsDo.ReplaceDB(db)
	return d
}

type dictOptionsDo struct{ gen.DO }

type IDictOptionsDo interface {
	gen.SubQuery
	Debug() IDictOptionsDo
	WithContext(ctx context.Context) IDictOptionsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IDictOptionsDo
	WriteDB() IDictOptionsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IDictOptionsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IDictOptionsDo
	Not(conds ...gen.Condition) IDictOptionsDo
	Or(conds ...gen.Condition) IDictOptionsDo
	Select(conds ...field.Expr) IDictOptionsDo
	Where(conds ...gen.Condition) IDictOptionsDo
	Order(conds ...field.Expr) IDictOptionsDo
	Distinct(cols ...field.Expr) IDictOptionsDo
	Omit(cols ...field.Expr) IDictOptionsDo
	Join(table schema.Tabler, on ...field.Expr) IDictOptionsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IDictOptionsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IDictOptionsDo
	Group(cols ...field.Expr) IDictOptionsDo
	Having(conds ...gen.Condition) IDictOptionsDo
	Limit(limit int) IDictOptionsDo
	Offset(offset int) IDictOptionsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IDictOptionsDo
	Unscoped() IDictOptionsDo
	Create(values ...*model.DictOptions) error
	CreateInBatches(values []*model.DictOptions, batchSize int) error
	Save(values ...*model.DictOptions) error
	First() (*model.DictOptions, error)
	Take() (*model.DictOptions, error)
	Last() (*model.DictOptions, error)
	Find() ([]*model.DictOptions, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DictOptions, err error)
	FindInBatches(result *[]*model.DictOptions, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.DictOptions) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IDictOptionsDo
	Assign(attrs ...field.AssignExpr) IDictOptionsDo
	Joins(fields ...field.RelationField) IDictOptionsDo
	Preload(fields ...field.RelationField) IDictOptionsDo
	FirstOrInit() (*model.DictOptions, error)
	FirstOrCreate() (*model.DictOptions, error)
	FindByPage(offset int, limit int) (result []*model.DictOptions, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IDictOptionsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (d dictOptionsDo) Debug() IDictOptionsDo {
	return d.withDO(d.DO.Debug())
}

func (d dictOptionsDo) WithContext(ctx context.Context) IDictOptionsDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d dictOptionsDo) ReadDB() IDictOptionsDo {
	return d.Clauses(dbresolver.Read)
}

func (d dictOptionsDo) WriteDB() IDictOptionsDo {
	return d.Clauses(dbresolver.Write)
}

func (d dictOptionsDo) Session(config *gorm.Session) IDictOptionsDo {
	return d.withDO(d.DO.Session(config))
}

func (d dictOptionsDo) Clauses(conds ...clause.Expression) IDictOptionsDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d dictOptionsDo) Returning(value interface{}, columns ...string) IDictOptionsDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d dictOptionsDo) Not(conds ...gen.Condition) IDictOptionsDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d dictOptionsDo) Or(conds ...gen.Condition) IDictOptionsDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d dictOptionsDo) Select(conds ...field.Expr) IDictOptionsDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d dictOptionsDo) Where(conds ...gen.Condition) IDictOptionsDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d dictOptionsDo) Order(conds ...field.Expr) IDictOptionsDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d dictOptionsDo) Distinct(cols ...field.Expr) IDictOptionsDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d dictOptionsDo) Omit(cols ...field.Expr) IDictOptionsDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d dictOptionsDo) Join(table schema.Tabler, on ...field.Expr) IDictOptionsDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d dictOptionsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IDictOptionsDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d dictOptionsDo) RightJoin(table schema.Tabler, on ...field.Expr) IDictOptionsDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d dictOptionsDo) Group(cols ...field.Expr) IDictOptionsDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d dictOptionsDo) Having(conds ...gen.Condition) IDictOptionsDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d dictOptionsDo) Limit(limit int) IDictOptionsDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d dictOptionsDo) Offset(offset int) IDictOptionsDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d dictOptionsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IDictOptionsDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d dictOptionsDo) Unscoped() IDictOptionsDo {
	return d.withDO(d.DO.Unscoped())
}

func (d dictOptionsDo) Create(values ...*model.DictOptions) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d dictOptionsDo) CreateInBatches(values []*model.DictOptions, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d dictOptionsDo) Save(values ...*model.DictOptions) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d dictOptionsDo) First() (*model.DictOptions, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictOptions), nil
	}
}

func (d dictOptionsDo) Take() (*model.DictOptions, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictOptions), nil
	}
}

func (d dictOptionsDo) Last() (*model.DictOptions, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictOptions), nil
	}
}

func (d dictOptionsDo) Find() ([]*model.DictOptions, error) {
	result, err := d.DO.Find()
	return result.([]*model.DictOptions), err
}

func (d dictOptionsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DictOptions, err error) {
	buf := make([]*model.DictOptions, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d dictOptionsDo) FindInBatches(result *[]*model.DictOptions, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d dictOptionsDo) Attrs(attrs ...field.AssignExpr) IDictOptionsDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d dictOptionsDo) Assign(attrs ...field.AssignExpr) IDictOptionsDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d dictOptionsDo) Joins(fields ...field.RelationField) IDictOptionsDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d dictOptionsDo) Preload(fields ...field.RelationField) IDictOptionsDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d dictOptionsDo) FirstOrInit() (*model.DictOptions, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictOptions), nil
	}
}

func (d dictOptionsDo) FirstOrCreate() (*model.DictOptions, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DictOptions), nil
	}
}

func (d dictOptionsDo) FindByPage(offset int, limit int) (result []*model.DictOptions, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d dictOptionsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d dictOptionsDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d dictOptionsDo) Delete(models ...*model.DictOptions) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *dictOptionsDo) withDO(do gen.Dao) *dictOptionsDo {
	d.DO = *do.(*gen.DO)
	return d
}
