// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                              = new(Query)
	AbnormalPlaces                 *abnormalPlaces
	Admin                          *admin
	AdminProfile                   *adminProfile
	Album                          *album
	AlbumPhotos                    *albumPhotos
	DepartmentOperators            *departmentOperators
	DepartmentZones                *departmentZones
	Departments                    *departments
	Dict                           *dict
	DictOptions                    *dictOptions
	ExportFiles                    *exportFiles
	MassServer                     *massServer
	MassSignals                    *massSignals
	MassSpeeds                     *massSpeeds
	MassTest                       *massTest
	OperateLog                     *operateLog
	PlaceContents                  *placeContents
	PlaceLists                     *placeLists
	PlaceScenes                    *placeScenes
	Places                         *places
	Road                           *road
	RoadCommit                     *roadCommit
	RoadCommitIndicatorSignals     *roadCommitIndicatorSignals
	RoadCommitIndicators           *roadCommitIndicators
	RoadCommitServer               *roadCommitServer
	RoadCommitSpeedDetails         *roadCommitSpeedDetails
	RoadCommitSpeeds               *roadCommitSpeeds
	RoadMassCommit                 *roadMassCommit
	RoadMassCommitIndicatorSignals *roadMassCommitIndicatorSignals
	RoadMassCommitIndicators       *roadMassCommitIndicators
	RoadMassCommitServer           *roadMassCommitServer
	RoadMassCommitSpeedDetails     *roadMassCommitSpeedDetails
	RoadMassCommitSpeeds           *roadMassCommitSpeeds
	RoadRoutes                     *roadRoutes
	RoadSections                   *roadSections
	RoadTask                       *roadTask
	RolePermissions                *rolePermissions
	Roles                          *roles
	Rules                          *rules
	SettingOptions                 *settingOptions
	Settings                       *settings
	SpecializedServer              *specializedServer
	SpecializedSignals             *specializedSignals
	SpecializedSpeeds              *specializedSpeeds
	SpecializedTest                *specializedTest
	TaskNetworkTypes               *taskNetworkTypes
	TaskOperators                  *taskOperators
	TaskPlaces                     *taskPlaces
	TaskZones                      *taskZones
	Tasks                          *tasks
	Users                          *users
	Zone                           *zone
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	AbnormalPlaces = &Q.AbnormalPlaces
	Admin = &Q.Admin
	AdminProfile = &Q.AdminProfile
	Album = &Q.Album
	AlbumPhotos = &Q.AlbumPhotos
	DepartmentOperators = &Q.DepartmentOperators
	DepartmentZones = &Q.DepartmentZones
	Departments = &Q.Departments
	Dict = &Q.Dict
	DictOptions = &Q.DictOptions
	ExportFiles = &Q.ExportFiles
	MassServer = &Q.MassServer
	MassSignals = &Q.MassSignals
	MassSpeeds = &Q.MassSpeeds
	MassTest = &Q.MassTest
	OperateLog = &Q.OperateLog
	PlaceContents = &Q.PlaceContents
	PlaceLists = &Q.PlaceLists
	PlaceScenes = &Q.PlaceScenes
	Places = &Q.Places
	Road = &Q.Road
	RoadCommit = &Q.RoadCommit
	RoadCommitIndicatorSignals = &Q.RoadCommitIndicatorSignals
	RoadCommitIndicators = &Q.RoadCommitIndicators
	RoadCommitServer = &Q.RoadCommitServer
	RoadCommitSpeedDetails = &Q.RoadCommitSpeedDetails
	RoadCommitSpeeds = &Q.RoadCommitSpeeds
	RoadMassCommit = &Q.RoadMassCommit
	RoadMassCommitIndicatorSignals = &Q.RoadMassCommitIndicatorSignals
	RoadMassCommitIndicators = &Q.RoadMassCommitIndicators
	RoadMassCommitServer = &Q.RoadMassCommitServer
	RoadMassCommitSpeedDetails = &Q.RoadMassCommitSpeedDetails
	RoadMassCommitSpeeds = &Q.RoadMassCommitSpeeds
	RoadRoutes = &Q.RoadRoutes
	RoadSections = &Q.RoadSections
	RoadTask = &Q.RoadTask
	RolePermissions = &Q.RolePermissions
	Roles = &Q.Roles
	Rules = &Q.Rules
	SettingOptions = &Q.SettingOptions
	Settings = &Q.Settings
	SpecializedServer = &Q.SpecializedServer
	SpecializedSignals = &Q.SpecializedSignals
	SpecializedSpeeds = &Q.SpecializedSpeeds
	SpecializedTest = &Q.SpecializedTest
	TaskNetworkTypes = &Q.TaskNetworkTypes
	TaskOperators = &Q.TaskOperators
	TaskPlaces = &Q.TaskPlaces
	TaskZones = &Q.TaskZones
	Tasks = &Q.Tasks
	Users = &Q.Users
	Zone = &Q.Zone
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                             db,
		AbnormalPlaces:                 newAbnormalPlaces(db, opts...),
		Admin:                          newAdmin(db, opts...),
		AdminProfile:                   newAdminProfile(db, opts...),
		Album:                          newAlbum(db, opts...),
		AlbumPhotos:                    newAlbumPhotos(db, opts...),
		DepartmentOperators:            newDepartmentOperators(db, opts...),
		DepartmentZones:                newDepartmentZones(db, opts...),
		Departments:                    newDepartments(db, opts...),
		Dict:                           newDict(db, opts...),
		DictOptions:                    newDictOptions(db, opts...),
		ExportFiles:                    newExportFiles(db, opts...),
		MassServer:                     newMassServer(db, opts...),
		MassSignals:                    newMassSignals(db, opts...),
		MassSpeeds:                     newMassSpeeds(db, opts...),
		MassTest:                       newMassTest(db, opts...),
		OperateLog:                     newOperateLog(db, opts...),
		PlaceContents:                  newPlaceContents(db, opts...),
		PlaceLists:                     newPlaceLists(db, opts...),
		PlaceScenes:                    newPlaceScenes(db, opts...),
		Places:                         newPlaces(db, opts...),
		Road:                           newRoad(db, opts...),
		RoadCommit:                     newRoadCommit(db, opts...),
		RoadCommitIndicatorSignals:     newRoadCommitIndicatorSignals(db, opts...),
		RoadCommitIndicators:           newRoadCommitIndicators(db, opts...),
		RoadCommitServer:               newRoadCommitServer(db, opts...),
		RoadCommitSpeedDetails:         newRoadCommitSpeedDetails(db, opts...),
		RoadCommitSpeeds:               newRoadCommitSpeeds(db, opts...),
		RoadMassCommit:                 newRoadMassCommit(db, opts...),
		RoadMassCommitIndicatorSignals: newRoadMassCommitIndicatorSignals(db, opts...),
		RoadMassCommitIndicators:       newRoadMassCommitIndicators(db, opts...),
		RoadMassCommitServer:           newRoadMassCommitServer(db, opts...),
		RoadMassCommitSpeedDetails:     newRoadMassCommitSpeedDetails(db, opts...),
		RoadMassCommitSpeeds:           newRoadMassCommitSpeeds(db, opts...),
		RoadRoutes:                     newRoadRoutes(db, opts...),
		RoadSections:                   newRoadSections(db, opts...),
		RoadTask:                       newRoadTask(db, opts...),
		RolePermissions:                newRolePermissions(db, opts...),
		Roles:                          newRoles(db, opts...),
		Rules:                          newRules(db, opts...),
		SettingOptions:                 newSettingOptions(db, opts...),
		Settings:                       newSettings(db, opts...),
		SpecializedServer:              newSpecializedServer(db, opts...),
		SpecializedSignals:             newSpecializedSignals(db, opts...),
		SpecializedSpeeds:              newSpecializedSpeeds(db, opts...),
		SpecializedTest:                newSpecializedTest(db, opts...),
		TaskNetworkTypes:               newTaskNetworkTypes(db, opts...),
		TaskOperators:                  newTaskOperators(db, opts...),
		TaskPlaces:                     newTaskPlaces(db, opts...),
		TaskZones:                      newTaskZones(db, opts...),
		Tasks:                          newTasks(db, opts...),
		Users:                          newUsers(db, opts...),
		Zone:                           newZone(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	AbnormalPlaces                 abnormalPlaces
	Admin                          admin
	AdminProfile                   adminProfile
	Album                          album
	AlbumPhotos                    albumPhotos
	DepartmentOperators            departmentOperators
	DepartmentZones                departmentZones
	Departments                    departments
	Dict                           dict
	DictOptions                    dictOptions
	ExportFiles                    exportFiles
	MassServer                     massServer
	MassSignals                    massSignals
	MassSpeeds                     massSpeeds
	MassTest                       massTest
	OperateLog                     operateLog
	PlaceContents                  placeContents
	PlaceLists                     placeLists
	PlaceScenes                    placeScenes
	Places                         places
	Road                           road
	RoadCommit                     roadCommit
	RoadCommitIndicatorSignals     roadCommitIndicatorSignals
	RoadCommitIndicators           roadCommitIndicators
	RoadCommitServer               roadCommitServer
	RoadCommitSpeedDetails         roadCommitSpeedDetails
	RoadCommitSpeeds               roadCommitSpeeds
	RoadMassCommit                 roadMassCommit
	RoadMassCommitIndicatorSignals roadMassCommitIndicatorSignals
	RoadMassCommitIndicators       roadMassCommitIndicators
	RoadMassCommitServer           roadMassCommitServer
	RoadMassCommitSpeedDetails     roadMassCommitSpeedDetails
	RoadMassCommitSpeeds           roadMassCommitSpeeds
	RoadRoutes                     roadRoutes
	RoadSections                   roadSections
	RoadTask                       roadTask
	RolePermissions                rolePermissions
	Roles                          roles
	Rules                          rules
	SettingOptions                 settingOptions
	Settings                       settings
	SpecializedServer              specializedServer
	SpecializedSignals             specializedSignals
	SpecializedSpeeds              specializedSpeeds
	SpecializedTest                specializedTest
	TaskNetworkTypes               taskNetworkTypes
	TaskOperators                  taskOperators
	TaskPlaces                     taskPlaces
	TaskZones                      taskZones
	Tasks                          tasks
	Users                          users
	Zone                           zone
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                             db,
		AbnormalPlaces:                 q.AbnormalPlaces.clone(db),
		Admin:                          q.Admin.clone(db),
		AdminProfile:                   q.AdminProfile.clone(db),
		Album:                          q.Album.clone(db),
		AlbumPhotos:                    q.AlbumPhotos.clone(db),
		DepartmentOperators:            q.DepartmentOperators.clone(db),
		DepartmentZones:                q.DepartmentZones.clone(db),
		Departments:                    q.Departments.clone(db),
		Dict:                           q.Dict.clone(db),
		DictOptions:                    q.DictOptions.clone(db),
		ExportFiles:                    q.ExportFiles.clone(db),
		MassServer:                     q.MassServer.clone(db),
		MassSignals:                    q.MassSignals.clone(db),
		MassSpeeds:                     q.MassSpeeds.clone(db),
		MassTest:                       q.MassTest.clone(db),
		OperateLog:                     q.OperateLog.clone(db),
		PlaceContents:                  q.PlaceContents.clone(db),
		PlaceLists:                     q.PlaceLists.clone(db),
		PlaceScenes:                    q.PlaceScenes.clone(db),
		Places:                         q.Places.clone(db),
		Road:                           q.Road.clone(db),
		RoadCommit:                     q.RoadCommit.clone(db),
		RoadCommitIndicatorSignals:     q.RoadCommitIndicatorSignals.clone(db),
		RoadCommitIndicators:           q.RoadCommitIndicators.clone(db),
		RoadCommitServer:               q.RoadCommitServer.clone(db),
		RoadCommitSpeedDetails:         q.RoadCommitSpeedDetails.clone(db),
		RoadCommitSpeeds:               q.RoadCommitSpeeds.clone(db),
		RoadMassCommit:                 q.RoadMassCommit.clone(db),
		RoadMassCommitIndicatorSignals: q.RoadMassCommitIndicatorSignals.clone(db),
		RoadMassCommitIndicators:       q.RoadMassCommitIndicators.clone(db),
		RoadMassCommitServer:           q.RoadMassCommitServer.clone(db),
		RoadMassCommitSpeedDetails:     q.RoadMassCommitSpeedDetails.clone(db),
		RoadMassCommitSpeeds:           q.RoadMassCommitSpeeds.clone(db),
		RoadRoutes:                     q.RoadRoutes.clone(db),
		RoadSections:                   q.RoadSections.clone(db),
		RoadTask:                       q.RoadTask.clone(db),
		RolePermissions:                q.RolePermissions.clone(db),
		Roles:                          q.Roles.clone(db),
		Rules:                          q.Rules.clone(db),
		SettingOptions:                 q.SettingOptions.clone(db),
		Settings:                       q.Settings.clone(db),
		SpecializedServer:              q.SpecializedServer.clone(db),
		SpecializedSignals:             q.SpecializedSignals.clone(db),
		SpecializedSpeeds:              q.SpecializedSpeeds.clone(db),
		SpecializedTest:                q.SpecializedTest.clone(db),
		TaskNetworkTypes:               q.TaskNetworkTypes.clone(db),
		TaskOperators:                  q.TaskOperators.clone(db),
		TaskPlaces:                     q.TaskPlaces.clone(db),
		TaskZones:                      q.TaskZones.clone(db),
		Tasks:                          q.Tasks.clone(db),
		Users:                          q.Users.clone(db),
		Zone:                           q.Zone.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                             db,
		AbnormalPlaces:                 q.AbnormalPlaces.replaceDB(db),
		Admin:                          q.Admin.replaceDB(db),
		AdminProfile:                   q.AdminProfile.replaceDB(db),
		Album:                          q.Album.replaceDB(db),
		AlbumPhotos:                    q.AlbumPhotos.replaceDB(db),
		DepartmentOperators:            q.DepartmentOperators.replaceDB(db),
		DepartmentZones:                q.DepartmentZones.replaceDB(db),
		Departments:                    q.Departments.replaceDB(db),
		Dict:                           q.Dict.replaceDB(db),
		DictOptions:                    q.DictOptions.replaceDB(db),
		ExportFiles:                    q.ExportFiles.replaceDB(db),
		MassServer:                     q.MassServer.replaceDB(db),
		MassSignals:                    q.MassSignals.replaceDB(db),
		MassSpeeds:                     q.MassSpeeds.replaceDB(db),
		MassTest:                       q.MassTest.replaceDB(db),
		OperateLog:                     q.OperateLog.replaceDB(db),
		PlaceContents:                  q.PlaceContents.replaceDB(db),
		PlaceLists:                     q.PlaceLists.replaceDB(db),
		PlaceScenes:                    q.PlaceScenes.replaceDB(db),
		Places:                         q.Places.replaceDB(db),
		Road:                           q.Road.replaceDB(db),
		RoadCommit:                     q.RoadCommit.replaceDB(db),
		RoadCommitIndicatorSignals:     q.RoadCommitIndicatorSignals.replaceDB(db),
		RoadCommitIndicators:           q.RoadCommitIndicators.replaceDB(db),
		RoadCommitServer:               q.RoadCommitServer.replaceDB(db),
		RoadCommitSpeedDetails:         q.RoadCommitSpeedDetails.replaceDB(db),
		RoadCommitSpeeds:               q.RoadCommitSpeeds.replaceDB(db),
		RoadMassCommit:                 q.RoadMassCommit.replaceDB(db),
		RoadMassCommitIndicatorSignals: q.RoadMassCommitIndicatorSignals.replaceDB(db),
		RoadMassCommitIndicators:       q.RoadMassCommitIndicators.replaceDB(db),
		RoadMassCommitServer:           q.RoadMassCommitServer.replaceDB(db),
		RoadMassCommitSpeedDetails:     q.RoadMassCommitSpeedDetails.replaceDB(db),
		RoadMassCommitSpeeds:           q.RoadMassCommitSpeeds.replaceDB(db),
		RoadRoutes:                     q.RoadRoutes.replaceDB(db),
		RoadSections:                   q.RoadSections.replaceDB(db),
		RoadTask:                       q.RoadTask.replaceDB(db),
		RolePermissions:                q.RolePermissions.replaceDB(db),
		Roles:                          q.Roles.replaceDB(db),
		Rules:                          q.Rules.replaceDB(db),
		SettingOptions:                 q.SettingOptions.replaceDB(db),
		Settings:                       q.Settings.replaceDB(db),
		SpecializedServer:              q.SpecializedServer.replaceDB(db),
		SpecializedSignals:             q.SpecializedSignals.replaceDB(db),
		SpecializedSpeeds:              q.SpecializedSpeeds.replaceDB(db),
		SpecializedTest:                q.SpecializedTest.replaceDB(db),
		TaskNetworkTypes:               q.TaskNetworkTypes.replaceDB(db),
		TaskOperators:                  q.TaskOperators.replaceDB(db),
		TaskPlaces:                     q.TaskPlaces.replaceDB(db),
		TaskZones:                      q.TaskZones.replaceDB(db),
		Tasks:                          q.Tasks.replaceDB(db),
		Users:                          q.Users.replaceDB(db),
		Zone:                           q.Zone.replaceDB(db),
	}
}

type queryCtx struct {
	AbnormalPlaces                 IAbnormalPlacesDo
	Admin                          IAdminDo
	AdminProfile                   IAdminProfileDo
	Album                          IAlbumDo
	AlbumPhotos                    IAlbumPhotosDo
	DepartmentOperators            IDepartmentOperatorsDo
	DepartmentZones                IDepartmentZonesDo
	Departments                    IDepartmentsDo
	Dict                           IDictDo
	DictOptions                    IDictOptionsDo
	ExportFiles                    IExportFilesDo
	MassServer                     IMassServerDo
	MassSignals                    IMassSignalsDo
	MassSpeeds                     IMassSpeedsDo
	MassTest                       IMassTestDo
	OperateLog                     IOperateLogDo
	PlaceContents                  IPlaceContentsDo
	PlaceLists                     IPlaceListsDo
	PlaceScenes                    IPlaceScenesDo
	Places                         IPlacesDo
	Road                           IRoadDo
	RoadCommit                     IRoadCommitDo
	RoadCommitIndicatorSignals     IRoadCommitIndicatorSignalsDo
	RoadCommitIndicators           IRoadCommitIndicatorsDo
	RoadCommitServer               IRoadCommitServerDo
	RoadCommitSpeedDetails         IRoadCommitSpeedDetailsDo
	RoadCommitSpeeds               IRoadCommitSpeedsDo
	RoadMassCommit                 IRoadMassCommitDo
	RoadMassCommitIndicatorSignals IRoadMassCommitIndicatorSignalsDo
	RoadMassCommitIndicators       IRoadMassCommitIndicatorsDo
	RoadMassCommitServer           IRoadMassCommitServerDo
	RoadMassCommitSpeedDetails     IRoadMassCommitSpeedDetailsDo
	RoadMassCommitSpeeds           IRoadMassCommitSpeedsDo
	RoadRoutes                     IRoadRoutesDo
	RoadSections                   IRoadSectionsDo
	RoadTask                       IRoadTaskDo
	RolePermissions                IRolePermissionsDo
	Roles                          IRolesDo
	Rules                          IRulesDo
	SettingOptions                 ISettingOptionsDo
	Settings                       ISettingsDo
	SpecializedServer              ISpecializedServerDo
	SpecializedSignals             ISpecializedSignalsDo
	SpecializedSpeeds              ISpecializedSpeedsDo
	SpecializedTest                ISpecializedTestDo
	TaskNetworkTypes               ITaskNetworkTypesDo
	TaskOperators                  ITaskOperatorsDo
	TaskPlaces                     ITaskPlacesDo
	TaskZones                      ITaskZonesDo
	Tasks                          ITasksDo
	Users                          IUsersDo
	Zone                           IZoneDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		AbnormalPlaces:                 q.AbnormalPlaces.WithContext(ctx),
		Admin:                          q.Admin.WithContext(ctx),
		AdminProfile:                   q.AdminProfile.WithContext(ctx),
		Album:                          q.Album.WithContext(ctx),
		AlbumPhotos:                    q.AlbumPhotos.WithContext(ctx),
		DepartmentOperators:            q.DepartmentOperators.WithContext(ctx),
		DepartmentZones:                q.DepartmentZones.WithContext(ctx),
		Departments:                    q.Departments.WithContext(ctx),
		Dict:                           q.Dict.WithContext(ctx),
		DictOptions:                    q.DictOptions.WithContext(ctx),
		ExportFiles:                    q.ExportFiles.WithContext(ctx),
		MassServer:                     q.MassServer.WithContext(ctx),
		MassSignals:                    q.MassSignals.WithContext(ctx),
		MassSpeeds:                     q.MassSpeeds.WithContext(ctx),
		MassTest:                       q.MassTest.WithContext(ctx),
		OperateLog:                     q.OperateLog.WithContext(ctx),
		PlaceContents:                  q.PlaceContents.WithContext(ctx),
		PlaceLists:                     q.PlaceLists.WithContext(ctx),
		PlaceScenes:                    q.PlaceScenes.WithContext(ctx),
		Places:                         q.Places.WithContext(ctx),
		Road:                           q.Road.WithContext(ctx),
		RoadCommit:                     q.RoadCommit.WithContext(ctx),
		RoadCommitIndicatorSignals:     q.RoadCommitIndicatorSignals.WithContext(ctx),
		RoadCommitIndicators:           q.RoadCommitIndicators.WithContext(ctx),
		RoadCommitServer:               q.RoadCommitServer.WithContext(ctx),
		RoadCommitSpeedDetails:         q.RoadCommitSpeedDetails.WithContext(ctx),
		RoadCommitSpeeds:               q.RoadCommitSpeeds.WithContext(ctx),
		RoadMassCommit:                 q.RoadMassCommit.WithContext(ctx),
		RoadMassCommitIndicatorSignals: q.RoadMassCommitIndicatorSignals.WithContext(ctx),
		RoadMassCommitIndicators:       q.RoadMassCommitIndicators.WithContext(ctx),
		RoadMassCommitServer:           q.RoadMassCommitServer.WithContext(ctx),
		RoadMassCommitSpeedDetails:     q.RoadMassCommitSpeedDetails.WithContext(ctx),
		RoadMassCommitSpeeds:           q.RoadMassCommitSpeeds.WithContext(ctx),
		RoadRoutes:                     q.RoadRoutes.WithContext(ctx),
		RoadSections:                   q.RoadSections.WithContext(ctx),
		RoadTask:                       q.RoadTask.WithContext(ctx),
		RolePermissions:                q.RolePermissions.WithContext(ctx),
		Roles:                          q.Roles.WithContext(ctx),
		Rules:                          q.Rules.WithContext(ctx),
		SettingOptions:                 q.SettingOptions.WithContext(ctx),
		Settings:                       q.Settings.WithContext(ctx),
		SpecializedServer:              q.SpecializedServer.WithContext(ctx),
		SpecializedSignals:             q.SpecializedSignals.WithContext(ctx),
		SpecializedSpeeds:              q.SpecializedSpeeds.WithContext(ctx),
		SpecializedTest:                q.SpecializedTest.WithContext(ctx),
		TaskNetworkTypes:               q.TaskNetworkTypes.WithContext(ctx),
		TaskOperators:                  q.TaskOperators.WithContext(ctx),
		TaskPlaces:                     q.TaskPlaces.WithContext(ctx),
		TaskZones:                      q.TaskZones.WithContext(ctx),
		Tasks:                          q.Tasks.WithContext(ctx),
		Users:                          q.Users.WithContext(ctx),
		Zone:                           q.Zone.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
