// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newMassSignals(db *gorm.DB, opts ...gen.DOOption) massSignals {
	_massSignals := massSignals{}

	_massSignals.massSignalsDo.UseDB(db, opts...)
	_massSignals.massSignalsDo.UseModel(&model.MassSignals{})

	tableName := _massSignals.massSignalsDo.TableName()
	_massSignals.ALL = field.NewAsterisk(tableName)
	_massSignals.ID = field.NewInt64(tableName, "id")
	_massSignals.TestID = field.NewInt64(tableName, "test_id")
	_massSignals.Type = field.NewString(tableName, "type")
	_massSignals.T = field.NewInt64(tableName, "t")
	_massSignals.Timestamp = field.NewInt64(tableName, "timestamp")
	_massSignals.Band = field.NewString(tableName, "band")
	_massSignals.Freq = field.NewField(tableName, "freq")
	_massSignals.Level = field.NewInt16(tableName, "level")
	_massSignals.Sinr = field.NewInt16(tableName, "sinr")
	_massSignals.Rsrp = field.NewInt16(tableName, "rsrp")
	_massSignals.Rsrq = field.NewInt16(tableName, "rsrq")
	_massSignals.Arfcn = field.NewInt16(tableName, "arfcn")

	_massSignals.fillFieldMap()

	return _massSignals
}

type massSignals struct {
	massSignalsDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键ID
	TestID    field.Int64  // 众测ID
	Type      field.String // 网络类型
	T         field.Int64  // 采集时间
	Timestamp field.Int64  // 记录生成时间
	Band      field.String // 频段信息
	Freq      field.Field  // 频率[下行频率 MHz, 上行频率 MHz]
	Level     field.Int16  // 信号等级
	Sinr      field.Int16  // 信噪比
	Rsrp      field.Int16  // 信号接收功率
	Rsrq      field.Int16  // 信号质量
	Arfcn     field.Int16  // 频点编号

	fieldMap map[string]field.Expr
}

func (m massSignals) Table(newTableName string) *massSignals {
	m.massSignalsDo.UseTable(newTableName)
	return m.updateTableName(newTableName)
}

func (m massSignals) As(alias string) *massSignals {
	m.massSignalsDo.DO = *(m.massSignalsDo.As(alias).(*gen.DO))
	return m.updateTableName(alias)
}

func (m *massSignals) updateTableName(table string) *massSignals {
	m.ALL = field.NewAsterisk(table)
	m.ID = field.NewInt64(table, "id")
	m.TestID = field.NewInt64(table, "test_id")
	m.Type = field.NewString(table, "type")
	m.T = field.NewInt64(table, "t")
	m.Timestamp = field.NewInt64(table, "timestamp")
	m.Band = field.NewString(table, "band")
	m.Freq = field.NewField(table, "freq")
	m.Level = field.NewInt16(table, "level")
	m.Sinr = field.NewInt16(table, "sinr")
	m.Rsrp = field.NewInt16(table, "rsrp")
	m.Rsrq = field.NewInt16(table, "rsrq")
	m.Arfcn = field.NewInt16(table, "arfcn")

	m.fillFieldMap()

	return m
}

func (m *massSignals) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := m.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (m *massSignals) fillFieldMap() {
	m.fieldMap = make(map[string]field.Expr, 12)
	m.fieldMap["id"] = m.ID
	m.fieldMap["test_id"] = m.TestID
	m.fieldMap["type"] = m.Type
	m.fieldMap["t"] = m.T
	m.fieldMap["timestamp"] = m.Timestamp
	m.fieldMap["band"] = m.Band
	m.fieldMap["freq"] = m.Freq
	m.fieldMap["level"] = m.Level
	m.fieldMap["sinr"] = m.Sinr
	m.fieldMap["rsrp"] = m.Rsrp
	m.fieldMap["rsrq"] = m.Rsrq
	m.fieldMap["arfcn"] = m.Arfcn
}

func (m massSignals) clone(db *gorm.DB) massSignals {
	m.massSignalsDo.ReplaceConnPool(db.Statement.ConnPool)
	return m
}

func (m massSignals) replaceDB(db *gorm.DB) massSignals {
	m.massSignalsDo.ReplaceDB(db)
	return m
}

type massSignalsDo struct{ gen.DO }

type IMassSignalsDo interface {
	gen.SubQuery
	Debug() IMassSignalsDo
	WithContext(ctx context.Context) IMassSignalsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IMassSignalsDo
	WriteDB() IMassSignalsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IMassSignalsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IMassSignalsDo
	Not(conds ...gen.Condition) IMassSignalsDo
	Or(conds ...gen.Condition) IMassSignalsDo
	Select(conds ...field.Expr) IMassSignalsDo
	Where(conds ...gen.Condition) IMassSignalsDo
	Order(conds ...field.Expr) IMassSignalsDo
	Distinct(cols ...field.Expr) IMassSignalsDo
	Omit(cols ...field.Expr) IMassSignalsDo
	Join(table schema.Tabler, on ...field.Expr) IMassSignalsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IMassSignalsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IMassSignalsDo
	Group(cols ...field.Expr) IMassSignalsDo
	Having(conds ...gen.Condition) IMassSignalsDo
	Limit(limit int) IMassSignalsDo
	Offset(offset int) IMassSignalsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IMassSignalsDo
	Unscoped() IMassSignalsDo
	Create(values ...*model.MassSignals) error
	CreateInBatches(values []*model.MassSignals, batchSize int) error
	Save(values ...*model.MassSignals) error
	First() (*model.MassSignals, error)
	Take() (*model.MassSignals, error)
	Last() (*model.MassSignals, error)
	Find() ([]*model.MassSignals, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MassSignals, err error)
	FindInBatches(result *[]*model.MassSignals, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.MassSignals) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IMassSignalsDo
	Assign(attrs ...field.AssignExpr) IMassSignalsDo
	Joins(fields ...field.RelationField) IMassSignalsDo
	Preload(fields ...field.RelationField) IMassSignalsDo
	FirstOrInit() (*model.MassSignals, error)
	FirstOrCreate() (*model.MassSignals, error)
	FindByPage(offset int, limit int) (result []*model.MassSignals, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IMassSignalsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (m massSignalsDo) Debug() IMassSignalsDo {
	return m.withDO(m.DO.Debug())
}

func (m massSignalsDo) WithContext(ctx context.Context) IMassSignalsDo {
	return m.withDO(m.DO.WithContext(ctx))
}

func (m massSignalsDo) ReadDB() IMassSignalsDo {
	return m.Clauses(dbresolver.Read)
}

func (m massSignalsDo) WriteDB() IMassSignalsDo {
	return m.Clauses(dbresolver.Write)
}

func (m massSignalsDo) Session(config *gorm.Session) IMassSignalsDo {
	return m.withDO(m.DO.Session(config))
}

func (m massSignalsDo) Clauses(conds ...clause.Expression) IMassSignalsDo {
	return m.withDO(m.DO.Clauses(conds...))
}

func (m massSignalsDo) Returning(value interface{}, columns ...string) IMassSignalsDo {
	return m.withDO(m.DO.Returning(value, columns...))
}

func (m massSignalsDo) Not(conds ...gen.Condition) IMassSignalsDo {
	return m.withDO(m.DO.Not(conds...))
}

func (m massSignalsDo) Or(conds ...gen.Condition) IMassSignalsDo {
	return m.withDO(m.DO.Or(conds...))
}

func (m massSignalsDo) Select(conds ...field.Expr) IMassSignalsDo {
	return m.withDO(m.DO.Select(conds...))
}

func (m massSignalsDo) Where(conds ...gen.Condition) IMassSignalsDo {
	return m.withDO(m.DO.Where(conds...))
}

func (m massSignalsDo) Order(conds ...field.Expr) IMassSignalsDo {
	return m.withDO(m.DO.Order(conds...))
}

func (m massSignalsDo) Distinct(cols ...field.Expr) IMassSignalsDo {
	return m.withDO(m.DO.Distinct(cols...))
}

func (m massSignalsDo) Omit(cols ...field.Expr) IMassSignalsDo {
	return m.withDO(m.DO.Omit(cols...))
}

func (m massSignalsDo) Join(table schema.Tabler, on ...field.Expr) IMassSignalsDo {
	return m.withDO(m.DO.Join(table, on...))
}

func (m massSignalsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IMassSignalsDo {
	return m.withDO(m.DO.LeftJoin(table, on...))
}

func (m massSignalsDo) RightJoin(table schema.Tabler, on ...field.Expr) IMassSignalsDo {
	return m.withDO(m.DO.RightJoin(table, on...))
}

func (m massSignalsDo) Group(cols ...field.Expr) IMassSignalsDo {
	return m.withDO(m.DO.Group(cols...))
}

func (m massSignalsDo) Having(conds ...gen.Condition) IMassSignalsDo {
	return m.withDO(m.DO.Having(conds...))
}

func (m massSignalsDo) Limit(limit int) IMassSignalsDo {
	return m.withDO(m.DO.Limit(limit))
}

func (m massSignalsDo) Offset(offset int) IMassSignalsDo {
	return m.withDO(m.DO.Offset(offset))
}

func (m massSignalsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IMassSignalsDo {
	return m.withDO(m.DO.Scopes(funcs...))
}

func (m massSignalsDo) Unscoped() IMassSignalsDo {
	return m.withDO(m.DO.Unscoped())
}

func (m massSignalsDo) Create(values ...*model.MassSignals) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Create(values)
}

func (m massSignalsDo) CreateInBatches(values []*model.MassSignals, batchSize int) error {
	return m.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (m massSignalsDo) Save(values ...*model.MassSignals) error {
	if len(values) == 0 {
		return nil
	}
	return m.DO.Save(values)
}

func (m massSignalsDo) First() (*model.MassSignals, error) {
	if result, err := m.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.MassSignals), nil
	}
}

func (m massSignalsDo) Take() (*model.MassSignals, error) {
	if result, err := m.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.MassSignals), nil
	}
}

func (m massSignalsDo) Last() (*model.MassSignals, error) {
	if result, err := m.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.MassSignals), nil
	}
}

func (m massSignalsDo) Find() ([]*model.MassSignals, error) {
	result, err := m.DO.Find()
	return result.([]*model.MassSignals), err
}

func (m massSignalsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.MassSignals, err error) {
	buf := make([]*model.MassSignals, 0, batchSize)
	err = m.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (m massSignalsDo) FindInBatches(result *[]*model.MassSignals, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return m.DO.FindInBatches(result, batchSize, fc)
}

func (m massSignalsDo) Attrs(attrs ...field.AssignExpr) IMassSignalsDo {
	return m.withDO(m.DO.Attrs(attrs...))
}

func (m massSignalsDo) Assign(attrs ...field.AssignExpr) IMassSignalsDo {
	return m.withDO(m.DO.Assign(attrs...))
}

func (m massSignalsDo) Joins(fields ...field.RelationField) IMassSignalsDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Joins(_f))
	}
	return &m
}

func (m massSignalsDo) Preload(fields ...field.RelationField) IMassSignalsDo {
	for _, _f := range fields {
		m = *m.withDO(m.DO.Preload(_f))
	}
	return &m
}

func (m massSignalsDo) FirstOrInit() (*model.MassSignals, error) {
	if result, err := m.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.MassSignals), nil
	}
}

func (m massSignalsDo) FirstOrCreate() (*model.MassSignals, error) {
	if result, err := m.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.MassSignals), nil
	}
}

func (m massSignalsDo) FindByPage(offset int, limit int) (result []*model.MassSignals, count int64, err error) {
	result, err = m.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = m.Offset(-1).Limit(-1).Count()
	return
}

func (m massSignalsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = m.Count()
	if err != nil {
		return
	}

	err = m.Offset(offset).Limit(limit).Scan(result)
	return
}

func (m massSignalsDo) Scan(result interface{}) (err error) {
	return m.DO.Scan(result)
}

func (m massSignalsDo) Delete(models ...*model.MassSignals) (result gen.ResultInfo, err error) {
	return m.DO.Delete(models)
}

func (m *massSignalsDo) withDO(do gen.Dao) *massSignalsDo {
	m.DO = *do.(*gen.DO)
	return m
}
