// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newPlaces(db *gorm.DB, opts ...gen.DOOption) places {
	_places := places{}

	_places.placesDo.UseDB(db, opts...)
	_places.placesDo.UseModel(&model.Places{})

	tableName := _places.placesDo.TableName()
	_places.ALL = field.NewAsterisk(tableName)
	_places.ID = field.NewInt64(tableName, "id")
	_places.ZoneCode = field.NewInt(tableName, "zone_code")
	_places.SceneID = field.NewInt(tableName, "scene_id")
	_places.Name = field.NewString(tableName, "name")
	_places.Address = field.NewString(tableName, "address")
	_places.Longitude = field.NewFloat64(tableName, "longitude")
	_places.Latitude = field.NewFloat64(tableName, "latitude")
	_places.Description = field.NewString(tableName, "description")
	_places.Disabled = field.NewBool(tableName, "disabled")
	_places.PingCount = field.NewInt16(tableName, "ping_count")
	_places.CreatedAt = field.NewTime(tableName, "created_at")
	_places.UpdatedAt = field.NewTime(tableName, "updated_at")
	_places.DeletedAt = field.NewTime(tableName, "deleted_at")

	_places.fillFieldMap()

	return _places
}

type places struct {
	placesDo

	ALL         field.Asterisk
	ID          field.Int64   // 主键
	ZoneCode    field.Int     // 地区编码
	SceneID     field.Int     // 地点场景ID
	Name        field.String  // 场景名称
	Address     field.String  // 场景具体地址
	Longitude   field.Float64 // 经度
	Latitude    field.Float64 // 维度
	Description field.String  // 描述信息
	Disabled    field.Bool    // 禁用状态
	PingCount   field.Int16   // 测试次数
	CreatedAt   field.Time    // 创建时间
	UpdatedAt   field.Time    // 修改时间
	DeletedAt   field.Time    // 删除时间

	fieldMap map[string]field.Expr
}

func (p places) Table(newTableName string) *places {
	p.placesDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p places) As(alias string) *places {
	p.placesDo.DO = *(p.placesDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *places) updateTableName(table string) *places {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt64(table, "id")
	p.ZoneCode = field.NewInt(table, "zone_code")
	p.SceneID = field.NewInt(table, "scene_id")
	p.Name = field.NewString(table, "name")
	p.Address = field.NewString(table, "address")
	p.Longitude = field.NewFloat64(table, "longitude")
	p.Latitude = field.NewFloat64(table, "latitude")
	p.Description = field.NewString(table, "description")
	p.Disabled = field.NewBool(table, "disabled")
	p.PingCount = field.NewInt16(table, "ping_count")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewTime(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *places) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *places) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 13)
	p.fieldMap["id"] = p.ID
	p.fieldMap["zone_code"] = p.ZoneCode
	p.fieldMap["scene_id"] = p.SceneID
	p.fieldMap["name"] = p.Name
	p.fieldMap["address"] = p.Address
	p.fieldMap["longitude"] = p.Longitude
	p.fieldMap["latitude"] = p.Latitude
	p.fieldMap["description"] = p.Description
	p.fieldMap["disabled"] = p.Disabled
	p.fieldMap["ping_count"] = p.PingCount
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
}

func (p places) clone(db *gorm.DB) places {
	p.placesDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p places) replaceDB(db *gorm.DB) places {
	p.placesDo.ReplaceDB(db)
	return p
}

type placesDo struct{ gen.DO }

type IPlacesDo interface {
	gen.SubQuery
	Debug() IPlacesDo
	WithContext(ctx context.Context) IPlacesDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlacesDo
	WriteDB() IPlacesDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlacesDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlacesDo
	Not(conds ...gen.Condition) IPlacesDo
	Or(conds ...gen.Condition) IPlacesDo
	Select(conds ...field.Expr) IPlacesDo
	Where(conds ...gen.Condition) IPlacesDo
	Order(conds ...field.Expr) IPlacesDo
	Distinct(cols ...field.Expr) IPlacesDo
	Omit(cols ...field.Expr) IPlacesDo
	Join(table schema.Tabler, on ...field.Expr) IPlacesDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlacesDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlacesDo
	Group(cols ...field.Expr) IPlacesDo
	Having(conds ...gen.Condition) IPlacesDo
	Limit(limit int) IPlacesDo
	Offset(offset int) IPlacesDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlacesDo
	Unscoped() IPlacesDo
	Create(values ...*model.Places) error
	CreateInBatches(values []*model.Places, batchSize int) error
	Save(values ...*model.Places) error
	First() (*model.Places, error)
	Take() (*model.Places, error)
	Last() (*model.Places, error)
	Find() ([]*model.Places, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Places, err error)
	FindInBatches(result *[]*model.Places, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Places) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlacesDo
	Assign(attrs ...field.AssignExpr) IPlacesDo
	Joins(fields ...field.RelationField) IPlacesDo
	Preload(fields ...field.RelationField) IPlacesDo
	FirstOrInit() (*model.Places, error)
	FirstOrCreate() (*model.Places, error)
	FindByPage(offset int, limit int) (result []*model.Places, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlacesDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p placesDo) Debug() IPlacesDo {
	return p.withDO(p.DO.Debug())
}

func (p placesDo) WithContext(ctx context.Context) IPlacesDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p placesDo) ReadDB() IPlacesDo {
	return p.Clauses(dbresolver.Read)
}

func (p placesDo) WriteDB() IPlacesDo {
	return p.Clauses(dbresolver.Write)
}

func (p placesDo) Session(config *gorm.Session) IPlacesDo {
	return p.withDO(p.DO.Session(config))
}

func (p placesDo) Clauses(conds ...clause.Expression) IPlacesDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p placesDo) Returning(value interface{}, columns ...string) IPlacesDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p placesDo) Not(conds ...gen.Condition) IPlacesDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p placesDo) Or(conds ...gen.Condition) IPlacesDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p placesDo) Select(conds ...field.Expr) IPlacesDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p placesDo) Where(conds ...gen.Condition) IPlacesDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p placesDo) Order(conds ...field.Expr) IPlacesDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p placesDo) Distinct(cols ...field.Expr) IPlacesDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p placesDo) Omit(cols ...field.Expr) IPlacesDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p placesDo) Join(table schema.Tabler, on ...field.Expr) IPlacesDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p placesDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlacesDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p placesDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlacesDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p placesDo) Group(cols ...field.Expr) IPlacesDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p placesDo) Having(conds ...gen.Condition) IPlacesDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p placesDo) Limit(limit int) IPlacesDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p placesDo) Offset(offset int) IPlacesDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p placesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlacesDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p placesDo) Unscoped() IPlacesDo {
	return p.withDO(p.DO.Unscoped())
}

func (p placesDo) Create(values ...*model.Places) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p placesDo) CreateInBatches(values []*model.Places, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p placesDo) Save(values ...*model.Places) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p placesDo) First() (*model.Places, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Places), nil
	}
}

func (p placesDo) Take() (*model.Places, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Places), nil
	}
}

func (p placesDo) Last() (*model.Places, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Places), nil
	}
}

func (p placesDo) Find() ([]*model.Places, error) {
	result, err := p.DO.Find()
	return result.([]*model.Places), err
}

func (p placesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Places, err error) {
	buf := make([]*model.Places, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p placesDo) FindInBatches(result *[]*model.Places, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p placesDo) Attrs(attrs ...field.AssignExpr) IPlacesDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p placesDo) Assign(attrs ...field.AssignExpr) IPlacesDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p placesDo) Joins(fields ...field.RelationField) IPlacesDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p placesDo) Preload(fields ...field.RelationField) IPlacesDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p placesDo) FirstOrInit() (*model.Places, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Places), nil
	}
}

func (p placesDo) FirstOrCreate() (*model.Places, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Places), nil
	}
}

func (p placesDo) FindByPage(offset int, limit int) (result []*model.Places, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p placesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p placesDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p placesDo) Delete(models ...*model.Places) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *placesDo) withDO(do gen.Dao) *placesDo {
	p.DO = *do.(*gen.DO)
	return p
}
