// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newPlaceLists(db *gorm.DB, opts ...gen.DOOption) placeLists {
	_placeLists := placeLists{}

	_placeLists.placeListsDo.UseDB(db, opts...)
	_placeLists.placeListsDo.UseModel(&model.PlaceLists{})

	tableName := _placeLists.placeListsDo.TableName()
	_placeLists.ALL = field.NewAsterisk(tableName)
	_placeLists.ID = field.NewInt(tableName, "id")
	_placeLists.Name = field.NewString(tableName, "name")
	_placeLists.Disabled = field.NewBool(tableName, "disabled")
	_placeLists.CreatedAt = field.NewTime(tableName, "created_at")
	_placeLists.UpdatedAt = field.NewTime(tableName, "updated_at")
	_placeLists.DeletedAt = field.NewTime(tableName, "deleted_at")

	_placeLists.fillFieldMap()

	return _placeLists
}

type placeLists struct {
	placeListsDo

	ALL       field.Asterisk
	ID        field.Int    // 主键
	Name      field.String // 清单名称
	Disabled  field.Bool   // 禁用状态
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 修改时间
	DeletedAt field.Time   // 删除时间

	fieldMap map[string]field.Expr
}

func (p placeLists) Table(newTableName string) *placeLists {
	p.placeListsDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p placeLists) As(alias string) *placeLists {
	p.placeListsDo.DO = *(p.placeListsDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *placeLists) updateTableName(table string) *placeLists {
	p.ALL = field.NewAsterisk(table)
	p.ID = field.NewInt(table, "id")
	p.Name = field.NewString(table, "name")
	p.Disabled = field.NewBool(table, "disabled")
	p.CreatedAt = field.NewTime(table, "created_at")
	p.UpdatedAt = field.NewTime(table, "updated_at")
	p.DeletedAt = field.NewTime(table, "deleted_at")

	p.fillFieldMap()

	return p
}

func (p *placeLists) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *placeLists) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 6)
	p.fieldMap["id"] = p.ID
	p.fieldMap["name"] = p.Name
	p.fieldMap["disabled"] = p.Disabled
	p.fieldMap["created_at"] = p.CreatedAt
	p.fieldMap["updated_at"] = p.UpdatedAt
	p.fieldMap["deleted_at"] = p.DeletedAt
}

func (p placeLists) clone(db *gorm.DB) placeLists {
	p.placeListsDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p placeLists) replaceDB(db *gorm.DB) placeLists {
	p.placeListsDo.ReplaceDB(db)
	return p
}

type placeListsDo struct{ gen.DO }

type IPlaceListsDo interface {
	gen.SubQuery
	Debug() IPlaceListsDo
	WithContext(ctx context.Context) IPlaceListsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IPlaceListsDo
	WriteDB() IPlaceListsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IPlaceListsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IPlaceListsDo
	Not(conds ...gen.Condition) IPlaceListsDo
	Or(conds ...gen.Condition) IPlaceListsDo
	Select(conds ...field.Expr) IPlaceListsDo
	Where(conds ...gen.Condition) IPlaceListsDo
	Order(conds ...field.Expr) IPlaceListsDo
	Distinct(cols ...field.Expr) IPlaceListsDo
	Omit(cols ...field.Expr) IPlaceListsDo
	Join(table schema.Tabler, on ...field.Expr) IPlaceListsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IPlaceListsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IPlaceListsDo
	Group(cols ...field.Expr) IPlaceListsDo
	Having(conds ...gen.Condition) IPlaceListsDo
	Limit(limit int) IPlaceListsDo
	Offset(offset int) IPlaceListsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IPlaceListsDo
	Unscoped() IPlaceListsDo
	Create(values ...*model.PlaceLists) error
	CreateInBatches(values []*model.PlaceLists, batchSize int) error
	Save(values ...*model.PlaceLists) error
	First() (*model.PlaceLists, error)
	Take() (*model.PlaceLists, error)
	Last() (*model.PlaceLists, error)
	Find() ([]*model.PlaceLists, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlaceLists, err error)
	FindInBatches(result *[]*model.PlaceLists, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.PlaceLists) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IPlaceListsDo
	Assign(attrs ...field.AssignExpr) IPlaceListsDo
	Joins(fields ...field.RelationField) IPlaceListsDo
	Preload(fields ...field.RelationField) IPlaceListsDo
	FirstOrInit() (*model.PlaceLists, error)
	FirstOrCreate() (*model.PlaceLists, error)
	FindByPage(offset int, limit int) (result []*model.PlaceLists, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IPlaceListsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (p placeListsDo) Debug() IPlaceListsDo {
	return p.withDO(p.DO.Debug())
}

func (p placeListsDo) WithContext(ctx context.Context) IPlaceListsDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p placeListsDo) ReadDB() IPlaceListsDo {
	return p.Clauses(dbresolver.Read)
}

func (p placeListsDo) WriteDB() IPlaceListsDo {
	return p.Clauses(dbresolver.Write)
}

func (p placeListsDo) Session(config *gorm.Session) IPlaceListsDo {
	return p.withDO(p.DO.Session(config))
}

func (p placeListsDo) Clauses(conds ...clause.Expression) IPlaceListsDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p placeListsDo) Returning(value interface{}, columns ...string) IPlaceListsDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p placeListsDo) Not(conds ...gen.Condition) IPlaceListsDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p placeListsDo) Or(conds ...gen.Condition) IPlaceListsDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p placeListsDo) Select(conds ...field.Expr) IPlaceListsDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p placeListsDo) Where(conds ...gen.Condition) IPlaceListsDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p placeListsDo) Order(conds ...field.Expr) IPlaceListsDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p placeListsDo) Distinct(cols ...field.Expr) IPlaceListsDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p placeListsDo) Omit(cols ...field.Expr) IPlaceListsDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p placeListsDo) Join(table schema.Tabler, on ...field.Expr) IPlaceListsDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p placeListsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IPlaceListsDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p placeListsDo) RightJoin(table schema.Tabler, on ...field.Expr) IPlaceListsDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p placeListsDo) Group(cols ...field.Expr) IPlaceListsDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p placeListsDo) Having(conds ...gen.Condition) IPlaceListsDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p placeListsDo) Limit(limit int) IPlaceListsDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p placeListsDo) Offset(offset int) IPlaceListsDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p placeListsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IPlaceListsDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p placeListsDo) Unscoped() IPlaceListsDo {
	return p.withDO(p.DO.Unscoped())
}

func (p placeListsDo) Create(values ...*model.PlaceLists) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p placeListsDo) CreateInBatches(values []*model.PlaceLists, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p placeListsDo) Save(values ...*model.PlaceLists) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p placeListsDo) First() (*model.PlaceLists, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaceLists), nil
	}
}

func (p placeListsDo) Take() (*model.PlaceLists, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaceLists), nil
	}
}

func (p placeListsDo) Last() (*model.PlaceLists, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaceLists), nil
	}
}

func (p placeListsDo) Find() ([]*model.PlaceLists, error) {
	result, err := p.DO.Find()
	return result.([]*model.PlaceLists), err
}

func (p placeListsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.PlaceLists, err error) {
	buf := make([]*model.PlaceLists, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p placeListsDo) FindInBatches(result *[]*model.PlaceLists, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p placeListsDo) Attrs(attrs ...field.AssignExpr) IPlaceListsDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p placeListsDo) Assign(attrs ...field.AssignExpr) IPlaceListsDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p placeListsDo) Joins(fields ...field.RelationField) IPlaceListsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p placeListsDo) Preload(fields ...field.RelationField) IPlaceListsDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p placeListsDo) FirstOrInit() (*model.PlaceLists, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaceLists), nil
	}
}

func (p placeListsDo) FirstOrCreate() (*model.PlaceLists, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.PlaceLists), nil
	}
}

func (p placeListsDo) FindByPage(offset int, limit int) (result []*model.PlaceLists, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p placeListsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p placeListsDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p placeListsDo) Delete(models ...*model.PlaceLists) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *placeListsDo) withDO(do gen.Dao) *placeListsDo {
	p.DO = *do.(*gen.DO)
	return p
}
