// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newRoadRoutes(db *gorm.DB, opts ...gen.DOOption) roadRoutes {
	_roadRoutes := roadRoutes{}

	_roadRoutes.roadRoutesDo.UseDB(db, opts...)
	_roadRoutes.roadRoutesDo.UseModel(&model.RoadRoutes{})

	tableName := _roadRoutes.roadRoutesDo.TableName()
	_roadRoutes.ALL = field.NewAsterisk(tableName)
	_roadRoutes.RoadSectionID = field.NewInt64(tableName, "road_section_id")
	_roadRoutes.RoadID = field.NewInt64(tableName, "road_id")
	_roadRoutes.Longitude = field.NewFloat64(tableName, "longitude")
	_roadRoutes.Latitude = field.NewFloat64(tableName, "latitude")

	_roadRoutes.fillFieldMap()

	return _roadRoutes
}

type roadRoutes struct {
	roadRoutesDo

	ALL           field.Asterisk
	RoadSectionID field.Int64   // 路段信息ID
	RoadID        field.Int64   // 道路ID
	Longitude     field.Float64 // 经度
	Latitude      field.Float64 // 纬度

	fieldMap map[string]field.Expr
}

func (r roadRoutes) Table(newTableName string) *roadRoutes {
	r.roadRoutesDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roadRoutes) As(alias string) *roadRoutes {
	r.roadRoutesDo.DO = *(r.roadRoutesDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roadRoutes) updateTableName(table string) *roadRoutes {
	r.ALL = field.NewAsterisk(table)
	r.RoadSectionID = field.NewInt64(table, "road_section_id")
	r.RoadID = field.NewInt64(table, "road_id")
	r.Longitude = field.NewFloat64(table, "longitude")
	r.Latitude = field.NewFloat64(table, "latitude")

	r.fillFieldMap()

	return r
}

func (r *roadRoutes) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roadRoutes) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 4)
	r.fieldMap["road_section_id"] = r.RoadSectionID
	r.fieldMap["road_id"] = r.RoadID
	r.fieldMap["longitude"] = r.Longitude
	r.fieldMap["latitude"] = r.Latitude
}

func (r roadRoutes) clone(db *gorm.DB) roadRoutes {
	r.roadRoutesDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roadRoutes) replaceDB(db *gorm.DB) roadRoutes {
	r.roadRoutesDo.ReplaceDB(db)
	return r
}

type roadRoutesDo struct{ gen.DO }

type IRoadRoutesDo interface {
	gen.SubQuery
	Debug() IRoadRoutesDo
	WithContext(ctx context.Context) IRoadRoutesDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoadRoutesDo
	WriteDB() IRoadRoutesDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoadRoutesDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoadRoutesDo
	Not(conds ...gen.Condition) IRoadRoutesDo
	Or(conds ...gen.Condition) IRoadRoutesDo
	Select(conds ...field.Expr) IRoadRoutesDo
	Where(conds ...gen.Condition) IRoadRoutesDo
	Order(conds ...field.Expr) IRoadRoutesDo
	Distinct(cols ...field.Expr) IRoadRoutesDo
	Omit(cols ...field.Expr) IRoadRoutesDo
	Join(table schema.Tabler, on ...field.Expr) IRoadRoutesDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoadRoutesDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoadRoutesDo
	Group(cols ...field.Expr) IRoadRoutesDo
	Having(conds ...gen.Condition) IRoadRoutesDo
	Limit(limit int) IRoadRoutesDo
	Offset(offset int) IRoadRoutesDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadRoutesDo
	Unscoped() IRoadRoutesDo
	Create(values ...*model.RoadRoutes) error
	CreateInBatches(values []*model.RoadRoutes, batchSize int) error
	Save(values ...*model.RoadRoutes) error
	First() (*model.RoadRoutes, error)
	Take() (*model.RoadRoutes, error)
	Last() (*model.RoadRoutes, error)
	Find() ([]*model.RoadRoutes, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadRoutes, err error)
	FindInBatches(result *[]*model.RoadRoutes, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RoadRoutes) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoadRoutesDo
	Assign(attrs ...field.AssignExpr) IRoadRoutesDo
	Joins(fields ...field.RelationField) IRoadRoutesDo
	Preload(fields ...field.RelationField) IRoadRoutesDo
	FirstOrInit() (*model.RoadRoutes, error)
	FirstOrCreate() (*model.RoadRoutes, error)
	FindByPage(offset int, limit int) (result []*model.RoadRoutes, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoadRoutesDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roadRoutesDo) Debug() IRoadRoutesDo {
	return r.withDO(r.DO.Debug())
}

func (r roadRoutesDo) WithContext(ctx context.Context) IRoadRoutesDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roadRoutesDo) ReadDB() IRoadRoutesDo {
	return r.Clauses(dbresolver.Read)
}

func (r roadRoutesDo) WriteDB() IRoadRoutesDo {
	return r.Clauses(dbresolver.Write)
}

func (r roadRoutesDo) Session(config *gorm.Session) IRoadRoutesDo {
	return r.withDO(r.DO.Session(config))
}

func (r roadRoutesDo) Clauses(conds ...clause.Expression) IRoadRoutesDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roadRoutesDo) Returning(value interface{}, columns ...string) IRoadRoutesDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roadRoutesDo) Not(conds ...gen.Condition) IRoadRoutesDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roadRoutesDo) Or(conds ...gen.Condition) IRoadRoutesDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roadRoutesDo) Select(conds ...field.Expr) IRoadRoutesDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roadRoutesDo) Where(conds ...gen.Condition) IRoadRoutesDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roadRoutesDo) Order(conds ...field.Expr) IRoadRoutesDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roadRoutesDo) Distinct(cols ...field.Expr) IRoadRoutesDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roadRoutesDo) Omit(cols ...field.Expr) IRoadRoutesDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roadRoutesDo) Join(table schema.Tabler, on ...field.Expr) IRoadRoutesDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roadRoutesDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoadRoutesDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roadRoutesDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoadRoutesDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roadRoutesDo) Group(cols ...field.Expr) IRoadRoutesDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roadRoutesDo) Having(conds ...gen.Condition) IRoadRoutesDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roadRoutesDo) Limit(limit int) IRoadRoutesDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roadRoutesDo) Offset(offset int) IRoadRoutesDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roadRoutesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadRoutesDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roadRoutesDo) Unscoped() IRoadRoutesDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roadRoutesDo) Create(values ...*model.RoadRoutes) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roadRoutesDo) CreateInBatches(values []*model.RoadRoutes, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roadRoutesDo) Save(values ...*model.RoadRoutes) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roadRoutesDo) First() (*model.RoadRoutes, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadRoutes), nil
	}
}

func (r roadRoutesDo) Take() (*model.RoadRoutes, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadRoutes), nil
	}
}

func (r roadRoutesDo) Last() (*model.RoadRoutes, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadRoutes), nil
	}
}

func (r roadRoutesDo) Find() ([]*model.RoadRoutes, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoadRoutes), err
}

func (r roadRoutesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadRoutes, err error) {
	buf := make([]*model.RoadRoutes, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roadRoutesDo) FindInBatches(result *[]*model.RoadRoutes, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roadRoutesDo) Attrs(attrs ...field.AssignExpr) IRoadRoutesDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roadRoutesDo) Assign(attrs ...field.AssignExpr) IRoadRoutesDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roadRoutesDo) Joins(fields ...field.RelationField) IRoadRoutesDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roadRoutesDo) Preload(fields ...field.RelationField) IRoadRoutesDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roadRoutesDo) FirstOrInit() (*model.RoadRoutes, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadRoutes), nil
	}
}

func (r roadRoutesDo) FirstOrCreate() (*model.RoadRoutes, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadRoutes), nil
	}
}

func (r roadRoutesDo) FindByPage(offset int, limit int) (result []*model.RoadRoutes, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roadRoutesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roadRoutesDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roadRoutesDo) Delete(models ...*model.RoadRoutes) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roadRoutesDo) withDO(do gen.Dao) *roadRoutesDo {
	r.DO = *do.(*gen.DO)
	return r
}
