// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newRoadMassCommitIndicators(db *gorm.DB, opts ...gen.DOOption) roadMassCommitIndicators {
	_roadMassCommitIndicators := roadMassCommitIndicators{}

	_roadMassCommitIndicators.roadMassCommitIndicatorsDo.UseDB(db, opts...)
	_roadMassCommitIndicators.roadMassCommitIndicatorsDo.UseModel(&model.RoadMassCommitIndicators{})

	tableName := _roadMassCommitIndicators.roadMassCommitIndicatorsDo.TableName()
	_roadMassCommitIndicators.ALL = field.NewAsterisk(tableName)
	_roadMassCommitIndicators.ID = field.NewInt64(tableName, "id")
	_roadMassCommitIndicators.UID = field.NewInt(tableName, "uid")
	_roadMassCommitIndicators.CommitID = field.NewInt64(tableName, "commit_id")
	_roadMassCommitIndicators.Longitude = field.NewFloat64(tableName, "longitude")
	_roadMassCommitIndicators.Latitude = field.NewFloat64(tableName, "latitude")
	_roadMassCommitIndicators.ZoneCode = field.NewInt(tableName, "zone_code")
	_roadMassCommitIndicators.Location = field.NewString(tableName, "location")
	_roadMassCommitIndicators.Sinr = field.NewFloat32(tableName, "sinr")
	_roadMassCommitIndicators.Signal = field.NewFloat32(tableName, "signal")
	_roadMassCommitIndicators.Delay = field.NewFloat32(tableName, "delay")
	_roadMassCommitIndicators.Ping = field.NewFloat32(tableName, "ping")
	_roadMassCommitIndicators.Jitter = field.NewFloat32(tableName, "jitter")
	_roadMassCommitIndicators.PacketLoss = field.NewFloat32(tableName, "packet_loss")
	_roadMassCommitIndicators.CreatedAt = field.NewTime(tableName, "created_at")
	_roadMassCommitIndicators.UpdatedAt = field.NewTime(tableName, "updated_at")
	_roadMassCommitIndicators.DeletedAt = field.NewTime(tableName, "deleted_at")

	_roadMassCommitIndicators.fillFieldMap()

	return _roadMassCommitIndicators
}

type roadMassCommitIndicators struct {
	roadMassCommitIndicatorsDo

	ALL        field.Asterisk
	ID         field.Int64   // 主键ID
	UID        field.Int     // 前台用户ID
	CommitID   field.Int64   // 提交ID
	Longitude  field.Float64 // 经度
	Latitude   field.Float64 // 纬度
	ZoneCode   field.Int     // 地区代码
	Location   field.String  // 提交位置
	Sinr       field.Float32 // 平均信噪比
	Signal     field.Float32 // 平均信号值
	Delay      field.Float32 // 平均延迟
	Ping       field.Float32 // ping延时(ms)
	Jitter     field.Float32 // 平均抖动(ms)
	PacketLoss field.Float32 // 平均丢包率
	CreatedAt  field.Time    // 创建时间
	UpdatedAt  field.Time    // 修改时间
	DeletedAt  field.Time    // 删除时间

	fieldMap map[string]field.Expr
}

func (r roadMassCommitIndicators) Table(newTableName string) *roadMassCommitIndicators {
	r.roadMassCommitIndicatorsDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roadMassCommitIndicators) As(alias string) *roadMassCommitIndicators {
	r.roadMassCommitIndicatorsDo.DO = *(r.roadMassCommitIndicatorsDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roadMassCommitIndicators) updateTableName(table string) *roadMassCommitIndicators {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.UID = field.NewInt(table, "uid")
	r.CommitID = field.NewInt64(table, "commit_id")
	r.Longitude = field.NewFloat64(table, "longitude")
	r.Latitude = field.NewFloat64(table, "latitude")
	r.ZoneCode = field.NewInt(table, "zone_code")
	r.Location = field.NewString(table, "location")
	r.Sinr = field.NewFloat32(table, "sinr")
	r.Signal = field.NewFloat32(table, "signal")
	r.Delay = field.NewFloat32(table, "delay")
	r.Ping = field.NewFloat32(table, "ping")
	r.Jitter = field.NewFloat32(table, "jitter")
	r.PacketLoss = field.NewFloat32(table, "packet_loss")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewTime(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *roadMassCommitIndicators) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roadMassCommitIndicators) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 16)
	r.fieldMap["id"] = r.ID
	r.fieldMap["uid"] = r.UID
	r.fieldMap["commit_id"] = r.CommitID
	r.fieldMap["longitude"] = r.Longitude
	r.fieldMap["latitude"] = r.Latitude
	r.fieldMap["zone_code"] = r.ZoneCode
	r.fieldMap["location"] = r.Location
	r.fieldMap["sinr"] = r.Sinr
	r.fieldMap["signal"] = r.Signal
	r.fieldMap["delay"] = r.Delay
	r.fieldMap["ping"] = r.Ping
	r.fieldMap["jitter"] = r.Jitter
	r.fieldMap["packet_loss"] = r.PacketLoss
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r roadMassCommitIndicators) clone(db *gorm.DB) roadMassCommitIndicators {
	r.roadMassCommitIndicatorsDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roadMassCommitIndicators) replaceDB(db *gorm.DB) roadMassCommitIndicators {
	r.roadMassCommitIndicatorsDo.ReplaceDB(db)
	return r
}

type roadMassCommitIndicatorsDo struct{ gen.DO }

type IRoadMassCommitIndicatorsDo interface {
	gen.SubQuery
	Debug() IRoadMassCommitIndicatorsDo
	WithContext(ctx context.Context) IRoadMassCommitIndicatorsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoadMassCommitIndicatorsDo
	WriteDB() IRoadMassCommitIndicatorsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoadMassCommitIndicatorsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoadMassCommitIndicatorsDo
	Not(conds ...gen.Condition) IRoadMassCommitIndicatorsDo
	Or(conds ...gen.Condition) IRoadMassCommitIndicatorsDo
	Select(conds ...field.Expr) IRoadMassCommitIndicatorsDo
	Where(conds ...gen.Condition) IRoadMassCommitIndicatorsDo
	Order(conds ...field.Expr) IRoadMassCommitIndicatorsDo
	Distinct(cols ...field.Expr) IRoadMassCommitIndicatorsDo
	Omit(cols ...field.Expr) IRoadMassCommitIndicatorsDo
	Join(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorsDo
	Group(cols ...field.Expr) IRoadMassCommitIndicatorsDo
	Having(conds ...gen.Condition) IRoadMassCommitIndicatorsDo
	Limit(limit int) IRoadMassCommitIndicatorsDo
	Offset(offset int) IRoadMassCommitIndicatorsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadMassCommitIndicatorsDo
	Unscoped() IRoadMassCommitIndicatorsDo
	Create(values ...*model.RoadMassCommitIndicators) error
	CreateInBatches(values []*model.RoadMassCommitIndicators, batchSize int) error
	Save(values ...*model.RoadMassCommitIndicators) error
	First() (*model.RoadMassCommitIndicators, error)
	Take() (*model.RoadMassCommitIndicators, error)
	Last() (*model.RoadMassCommitIndicators, error)
	Find() ([]*model.RoadMassCommitIndicators, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadMassCommitIndicators, err error)
	FindInBatches(result *[]*model.RoadMassCommitIndicators, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RoadMassCommitIndicators) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoadMassCommitIndicatorsDo
	Assign(attrs ...field.AssignExpr) IRoadMassCommitIndicatorsDo
	Joins(fields ...field.RelationField) IRoadMassCommitIndicatorsDo
	Preload(fields ...field.RelationField) IRoadMassCommitIndicatorsDo
	FirstOrInit() (*model.RoadMassCommitIndicators, error)
	FirstOrCreate() (*model.RoadMassCommitIndicators, error)
	FindByPage(offset int, limit int) (result []*model.RoadMassCommitIndicators, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoadMassCommitIndicatorsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roadMassCommitIndicatorsDo) Debug() IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Debug())
}

func (r roadMassCommitIndicatorsDo) WithContext(ctx context.Context) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roadMassCommitIndicatorsDo) ReadDB() IRoadMassCommitIndicatorsDo {
	return r.Clauses(dbresolver.Read)
}

func (r roadMassCommitIndicatorsDo) WriteDB() IRoadMassCommitIndicatorsDo {
	return r.Clauses(dbresolver.Write)
}

func (r roadMassCommitIndicatorsDo) Session(config *gorm.Session) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Session(config))
}

func (r roadMassCommitIndicatorsDo) Clauses(conds ...clause.Expression) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roadMassCommitIndicatorsDo) Returning(value interface{}, columns ...string) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roadMassCommitIndicatorsDo) Not(conds ...gen.Condition) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roadMassCommitIndicatorsDo) Or(conds ...gen.Condition) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roadMassCommitIndicatorsDo) Select(conds ...field.Expr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roadMassCommitIndicatorsDo) Where(conds ...gen.Condition) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roadMassCommitIndicatorsDo) Order(conds ...field.Expr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roadMassCommitIndicatorsDo) Distinct(cols ...field.Expr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roadMassCommitIndicatorsDo) Omit(cols ...field.Expr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roadMassCommitIndicatorsDo) Join(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roadMassCommitIndicatorsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roadMassCommitIndicatorsDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roadMassCommitIndicatorsDo) Group(cols ...field.Expr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roadMassCommitIndicatorsDo) Having(conds ...gen.Condition) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roadMassCommitIndicatorsDo) Limit(limit int) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roadMassCommitIndicatorsDo) Offset(offset int) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roadMassCommitIndicatorsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roadMassCommitIndicatorsDo) Unscoped() IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roadMassCommitIndicatorsDo) Create(values ...*model.RoadMassCommitIndicators) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roadMassCommitIndicatorsDo) CreateInBatches(values []*model.RoadMassCommitIndicators, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roadMassCommitIndicatorsDo) Save(values ...*model.RoadMassCommitIndicators) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roadMassCommitIndicatorsDo) First() (*model.RoadMassCommitIndicators, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicators), nil
	}
}

func (r roadMassCommitIndicatorsDo) Take() (*model.RoadMassCommitIndicators, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicators), nil
	}
}

func (r roadMassCommitIndicatorsDo) Last() (*model.RoadMassCommitIndicators, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicators), nil
	}
}

func (r roadMassCommitIndicatorsDo) Find() ([]*model.RoadMassCommitIndicators, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoadMassCommitIndicators), err
}

func (r roadMassCommitIndicatorsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadMassCommitIndicators, err error) {
	buf := make([]*model.RoadMassCommitIndicators, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roadMassCommitIndicatorsDo) FindInBatches(result *[]*model.RoadMassCommitIndicators, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roadMassCommitIndicatorsDo) Attrs(attrs ...field.AssignExpr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roadMassCommitIndicatorsDo) Assign(attrs ...field.AssignExpr) IRoadMassCommitIndicatorsDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roadMassCommitIndicatorsDo) Joins(fields ...field.RelationField) IRoadMassCommitIndicatorsDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roadMassCommitIndicatorsDo) Preload(fields ...field.RelationField) IRoadMassCommitIndicatorsDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roadMassCommitIndicatorsDo) FirstOrInit() (*model.RoadMassCommitIndicators, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicators), nil
	}
}

func (r roadMassCommitIndicatorsDo) FirstOrCreate() (*model.RoadMassCommitIndicators, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicators), nil
	}
}

func (r roadMassCommitIndicatorsDo) FindByPage(offset int, limit int) (result []*model.RoadMassCommitIndicators, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roadMassCommitIndicatorsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roadMassCommitIndicatorsDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roadMassCommitIndicatorsDo) Delete(models ...*model.RoadMassCommitIndicators) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roadMassCommitIndicatorsDo) withDO(do gen.Dao) *roadMassCommitIndicatorsDo {
	r.DO = *do.(*gen.DO)
	return r
}
