// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newRoadMassCommit(db *gorm.DB, opts ...gen.DOOption) roadMassCommit {
	_roadMassCommit := roadMassCommit{}

	_roadMassCommit.roadMassCommitDo.UseDB(db, opts...)
	_roadMassCommit.roadMassCommitDo.UseModel(&model.RoadMassCommit{})

	tableName := _roadMassCommit.roadMassCommitDo.TableName()
	_roadMassCommit.ALL = field.NewAsterisk(tableName)
	_roadMassCommit.ID = field.NewInt64(tableName, "id")
	_roadMassCommit.UID = field.NewInt(tableName, "uid")
	_roadMassCommit.StartTime = field.NewTime(tableName, "start_time")
	_roadMassCommit.DoneTime = field.NewTime(tableName, "done_time")
	_roadMassCommit.StartLongitude = field.NewFloat64(tableName, "start_longitude")
	_roadMassCommit.StartLatitude = field.NewFloat64(tableName, "start_latitude")
	_roadMassCommit.DoneLongitude = field.NewFloat64(tableName, "done_longitude")
	_roadMassCommit.DoneLatitude = field.NewFloat64(tableName, "done_latitude")
	_roadMassCommit.SignalCount = field.NewInt(tableName, "signal_count")
	_roadMassCommit.SpeedCount = field.NewInt(tableName, "speed_count")
	_roadMassCommit.Terminal = field.NewString(tableName, "terminal")
	_roadMassCommit.Operator = field.NewString(tableName, "operator")
	_roadMassCommit.NetworkType = field.NewString(tableName, "network_type")
	_roadMassCommit.AvgUpload = field.NewFloat32(tableName, "avg_upload")
	_roadMassCommit.AvgDownload = field.NewFloat32(tableName, "avg_download")
	_roadMassCommit.PeakUpload = field.NewFloat32(tableName, "peak_upload")
	_roadMassCommit.PeakDownload = field.NewFloat32(tableName, "peak_download")
	_roadMassCommit.Ping = field.NewFloat32(tableName, "ping")
	_roadMassCommit.Jitter = field.NewFloat32(tableName, "jitter")
	_roadMassCommit.PacketLoss = field.NewFloat32(tableName, "packet_loss")
	_roadMassCommit.Delay = field.NewFloat32(tableName, "delay")
	_roadMassCommit.Signal = field.NewFloat32(tableName, "signal")
	_roadMassCommit.Sinr = field.NewFloat32(tableName, "sinr")
	_roadMassCommit.ImagePhotoIds = field.NewField(tableName, "image_photo_ids")
	_roadMassCommit.VideoPhotoIds = field.NewField(tableName, "video_photo_ids")
	_roadMassCommit.Status = field.NewInt16(tableName, "status")
	_roadMassCommit.CreatedAt = field.NewTime(tableName, "created_at")
	_roadMassCommit.UpdatedAt = field.NewTime(tableName, "updated_at")
	_roadMassCommit.DeletedAt = field.NewTime(tableName, "deleted_at")

	_roadMassCommit.fillFieldMap()

	return _roadMassCommit
}

type roadMassCommit struct {
	roadMassCommitDo

	ALL            field.Asterisk
	ID             field.Int64   // 主键ID
	UID            field.Int     // 后台用户ID
	StartTime      field.Time    // 开始时间
	DoneTime       field.Time    // 完成时间
	StartLongitude field.Float64 // 开始经度
	StartLatitude  field.Float64 // 开始维度
	DoneLongitude  field.Float64 // 完成经度
	DoneLatitude   field.Float64 // 完成维度
	SignalCount    field.Int     // 信号路测众测指标上传次数
	SpeedCount     field.Int     // 测试数据上传次数
	Terminal       field.String  // 终端设备信息
	Operator       field.String  // 运营商
	NetworkType    field.String  // 网络类型
	AvgUpload      field.Float32 // 平均上传速度(Mbps)
	AvgDownload    field.Float32 // 平均下载速度(Mbps)
	PeakUpload     field.Float32 // 峰值上传速度(Mbps)
	PeakDownload   field.Float32 // 峰值下载速度(Mbps)
	Ping           field.Float32 // ping延时(ms)
	Jitter         field.Float32 // 抖动(ms)
	PacketLoss     field.Float32 // 丢包率(%)
	Delay          field.Float32 // 平均延时(ms)
	Signal         field.Float32 // 信号强度
	Sinr           field.Float32 // 信噪比
	ImagePhotoIds  field.Field   // 图片[开始ID,结束ID]
	VideoPhotoIds  field.Field   // 视频[开始ID,结束ID]
	Status         field.Int16   // 提交数据状态 -1:已失效 0:进行中 1:已完成
	CreatedAt      field.Time    // 创建时间
	UpdatedAt      field.Time    // 修改时间
	DeletedAt      field.Time    // 删除时间

	fieldMap map[string]field.Expr
}

func (r roadMassCommit) Table(newTableName string) *roadMassCommit {
	r.roadMassCommitDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roadMassCommit) As(alias string) *roadMassCommit {
	r.roadMassCommitDo.DO = *(r.roadMassCommitDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roadMassCommit) updateTableName(table string) *roadMassCommit {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.UID = field.NewInt(table, "uid")
	r.StartTime = field.NewTime(table, "start_time")
	r.DoneTime = field.NewTime(table, "done_time")
	r.StartLongitude = field.NewFloat64(table, "start_longitude")
	r.StartLatitude = field.NewFloat64(table, "start_latitude")
	r.DoneLongitude = field.NewFloat64(table, "done_longitude")
	r.DoneLatitude = field.NewFloat64(table, "done_latitude")
	r.SignalCount = field.NewInt(table, "signal_count")
	r.SpeedCount = field.NewInt(table, "speed_count")
	r.Terminal = field.NewString(table, "terminal")
	r.Operator = field.NewString(table, "operator")
	r.NetworkType = field.NewString(table, "network_type")
	r.AvgUpload = field.NewFloat32(table, "avg_upload")
	r.AvgDownload = field.NewFloat32(table, "avg_download")
	r.PeakUpload = field.NewFloat32(table, "peak_upload")
	r.PeakDownload = field.NewFloat32(table, "peak_download")
	r.Ping = field.NewFloat32(table, "ping")
	r.Jitter = field.NewFloat32(table, "jitter")
	r.PacketLoss = field.NewFloat32(table, "packet_loss")
	r.Delay = field.NewFloat32(table, "delay")
	r.Signal = field.NewFloat32(table, "signal")
	r.Sinr = field.NewFloat32(table, "sinr")
	r.ImagePhotoIds = field.NewField(table, "image_photo_ids")
	r.VideoPhotoIds = field.NewField(table, "video_photo_ids")
	r.Status = field.NewInt16(table, "status")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewTime(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *roadMassCommit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roadMassCommit) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 29)
	r.fieldMap["id"] = r.ID
	r.fieldMap["uid"] = r.UID
	r.fieldMap["start_time"] = r.StartTime
	r.fieldMap["done_time"] = r.DoneTime
	r.fieldMap["start_longitude"] = r.StartLongitude
	r.fieldMap["start_latitude"] = r.StartLatitude
	r.fieldMap["done_longitude"] = r.DoneLongitude
	r.fieldMap["done_latitude"] = r.DoneLatitude
	r.fieldMap["signal_count"] = r.SignalCount
	r.fieldMap["speed_count"] = r.SpeedCount
	r.fieldMap["terminal"] = r.Terminal
	r.fieldMap["operator"] = r.Operator
	r.fieldMap["network_type"] = r.NetworkType
	r.fieldMap["avg_upload"] = r.AvgUpload
	r.fieldMap["avg_download"] = r.AvgDownload
	r.fieldMap["peak_upload"] = r.PeakUpload
	r.fieldMap["peak_download"] = r.PeakDownload
	r.fieldMap["ping"] = r.Ping
	r.fieldMap["jitter"] = r.Jitter
	r.fieldMap["packet_loss"] = r.PacketLoss
	r.fieldMap["delay"] = r.Delay
	r.fieldMap["signal"] = r.Signal
	r.fieldMap["sinr"] = r.Sinr
	r.fieldMap["image_photo_ids"] = r.ImagePhotoIds
	r.fieldMap["video_photo_ids"] = r.VideoPhotoIds
	r.fieldMap["status"] = r.Status
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r roadMassCommit) clone(db *gorm.DB) roadMassCommit {
	r.roadMassCommitDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roadMassCommit) replaceDB(db *gorm.DB) roadMassCommit {
	r.roadMassCommitDo.ReplaceDB(db)
	return r
}

type roadMassCommitDo struct{ gen.DO }

type IRoadMassCommitDo interface {
	gen.SubQuery
	Debug() IRoadMassCommitDo
	WithContext(ctx context.Context) IRoadMassCommitDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoadMassCommitDo
	WriteDB() IRoadMassCommitDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoadMassCommitDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoadMassCommitDo
	Not(conds ...gen.Condition) IRoadMassCommitDo
	Or(conds ...gen.Condition) IRoadMassCommitDo
	Select(conds ...field.Expr) IRoadMassCommitDo
	Where(conds ...gen.Condition) IRoadMassCommitDo
	Order(conds ...field.Expr) IRoadMassCommitDo
	Distinct(cols ...field.Expr) IRoadMassCommitDo
	Omit(cols ...field.Expr) IRoadMassCommitDo
	Join(table schema.Tabler, on ...field.Expr) IRoadMassCommitDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitDo
	Group(cols ...field.Expr) IRoadMassCommitDo
	Having(conds ...gen.Condition) IRoadMassCommitDo
	Limit(limit int) IRoadMassCommitDo
	Offset(offset int) IRoadMassCommitDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadMassCommitDo
	Unscoped() IRoadMassCommitDo
	Create(values ...*model.RoadMassCommit) error
	CreateInBatches(values []*model.RoadMassCommit, batchSize int) error
	Save(values ...*model.RoadMassCommit) error
	First() (*model.RoadMassCommit, error)
	Take() (*model.RoadMassCommit, error)
	Last() (*model.RoadMassCommit, error)
	Find() ([]*model.RoadMassCommit, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadMassCommit, err error)
	FindInBatches(result *[]*model.RoadMassCommit, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RoadMassCommit) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoadMassCommitDo
	Assign(attrs ...field.AssignExpr) IRoadMassCommitDo
	Joins(fields ...field.RelationField) IRoadMassCommitDo
	Preload(fields ...field.RelationField) IRoadMassCommitDo
	FirstOrInit() (*model.RoadMassCommit, error)
	FirstOrCreate() (*model.RoadMassCommit, error)
	FindByPage(offset int, limit int) (result []*model.RoadMassCommit, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoadMassCommitDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roadMassCommitDo) Debug() IRoadMassCommitDo {
	return r.withDO(r.DO.Debug())
}

func (r roadMassCommitDo) WithContext(ctx context.Context) IRoadMassCommitDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roadMassCommitDo) ReadDB() IRoadMassCommitDo {
	return r.Clauses(dbresolver.Read)
}

func (r roadMassCommitDo) WriteDB() IRoadMassCommitDo {
	return r.Clauses(dbresolver.Write)
}

func (r roadMassCommitDo) Session(config *gorm.Session) IRoadMassCommitDo {
	return r.withDO(r.DO.Session(config))
}

func (r roadMassCommitDo) Clauses(conds ...clause.Expression) IRoadMassCommitDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roadMassCommitDo) Returning(value interface{}, columns ...string) IRoadMassCommitDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roadMassCommitDo) Not(conds ...gen.Condition) IRoadMassCommitDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roadMassCommitDo) Or(conds ...gen.Condition) IRoadMassCommitDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roadMassCommitDo) Select(conds ...field.Expr) IRoadMassCommitDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roadMassCommitDo) Where(conds ...gen.Condition) IRoadMassCommitDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roadMassCommitDo) Order(conds ...field.Expr) IRoadMassCommitDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roadMassCommitDo) Distinct(cols ...field.Expr) IRoadMassCommitDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roadMassCommitDo) Omit(cols ...field.Expr) IRoadMassCommitDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roadMassCommitDo) Join(table schema.Tabler, on ...field.Expr) IRoadMassCommitDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roadMassCommitDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roadMassCommitDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roadMassCommitDo) Group(cols ...field.Expr) IRoadMassCommitDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roadMassCommitDo) Having(conds ...gen.Condition) IRoadMassCommitDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roadMassCommitDo) Limit(limit int) IRoadMassCommitDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roadMassCommitDo) Offset(offset int) IRoadMassCommitDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roadMassCommitDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadMassCommitDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roadMassCommitDo) Unscoped() IRoadMassCommitDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roadMassCommitDo) Create(values ...*model.RoadMassCommit) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roadMassCommitDo) CreateInBatches(values []*model.RoadMassCommit, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roadMassCommitDo) Save(values ...*model.RoadMassCommit) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roadMassCommitDo) First() (*model.RoadMassCommit, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommit), nil
	}
}

func (r roadMassCommitDo) Take() (*model.RoadMassCommit, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommit), nil
	}
}

func (r roadMassCommitDo) Last() (*model.RoadMassCommit, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommit), nil
	}
}

func (r roadMassCommitDo) Find() ([]*model.RoadMassCommit, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoadMassCommit), err
}

func (r roadMassCommitDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadMassCommit, err error) {
	buf := make([]*model.RoadMassCommit, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roadMassCommitDo) FindInBatches(result *[]*model.RoadMassCommit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roadMassCommitDo) Attrs(attrs ...field.AssignExpr) IRoadMassCommitDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roadMassCommitDo) Assign(attrs ...field.AssignExpr) IRoadMassCommitDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roadMassCommitDo) Joins(fields ...field.RelationField) IRoadMassCommitDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roadMassCommitDo) Preload(fields ...field.RelationField) IRoadMassCommitDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roadMassCommitDo) FirstOrInit() (*model.RoadMassCommit, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommit), nil
	}
}

func (r roadMassCommitDo) FirstOrCreate() (*model.RoadMassCommit, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommit), nil
	}
}

func (r roadMassCommitDo) FindByPage(offset int, limit int) (result []*model.RoadMassCommit, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roadMassCommitDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roadMassCommitDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roadMassCommitDo) Delete(models ...*model.RoadMassCommit) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roadMassCommitDo) withDO(do gen.Dao) *roadMassCommitDo {
	r.DO = *do.(*gen.DO)
	return r
}
