// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newRoadMassCommitIndicatorSignals(db *gorm.DB, opts ...gen.DOOption) roadMassCommitIndicatorSignals {
	_roadMassCommitIndicatorSignals := roadMassCommitIndicatorSignals{}

	_roadMassCommitIndicatorSignals.roadMassCommitIndicatorSignalsDo.UseDB(db, opts...)
	_roadMassCommitIndicatorSignals.roadMassCommitIndicatorSignalsDo.UseModel(&model.RoadMassCommitIndicatorSignals{})

	tableName := _roadMassCommitIndicatorSignals.roadMassCommitIndicatorSignalsDo.TableName()
	_roadMassCommitIndicatorSignals.ALL = field.NewAsterisk(tableName)
	_roadMassCommitIndicatorSignals.ID = field.NewInt64(tableName, "id")
	_roadMassCommitIndicatorSignals.IndicatorID = field.NewInt64(tableName, "indicator_id")
	_roadMassCommitIndicatorSignals.Type = field.NewString(tableName, "type")
	_roadMassCommitIndicatorSignals.T = field.NewInt64(tableName, "t")
	_roadMassCommitIndicatorSignals.Timestamp = field.NewInt64(tableName, "timestamp")
	_roadMassCommitIndicatorSignals.Band = field.NewString(tableName, "band")
	_roadMassCommitIndicatorSignals.Freq = field.NewField(tableName, "freq")
	_roadMassCommitIndicatorSignals.Level = field.NewInt16(tableName, "level")
	_roadMassCommitIndicatorSignals.Sinr = field.NewInt16(tableName, "sinr")
	_roadMassCommitIndicatorSignals.Rsrp = field.NewInt16(tableName, "rsrp")
	_roadMassCommitIndicatorSignals.Rsrq = field.NewInt16(tableName, "rsrq")
	_roadMassCommitIndicatorSignals.Arfcn = field.NewInt16(tableName, "arfcn")

	_roadMassCommitIndicatorSignals.fillFieldMap()

	return _roadMassCommitIndicatorSignals
}

type roadMassCommitIndicatorSignals struct {
	roadMassCommitIndicatorSignalsDo

	ALL         field.Asterisk
	ID          field.Int64  // 主键ID
	IndicatorID field.Int64  // 路测众测指标数据ID
	Type        field.String // 网络类型
	T           field.Int64  // 采集时间
	Timestamp   field.Int64  // 记录生成时间
	Band        field.String // 频段信息
	Freq        field.Field  // 频率[下行频率 MHz, 上行频率 MHz]
	Level       field.Int16  // 信号等级
	Sinr        field.Int16  // 信噪比
	Rsrp        field.Int16  // 信号接收功率
	Rsrq        field.Int16  // 信号质量
	Arfcn       field.Int16  // 频点编号

	fieldMap map[string]field.Expr
}

func (r roadMassCommitIndicatorSignals) Table(newTableName string) *roadMassCommitIndicatorSignals {
	r.roadMassCommitIndicatorSignalsDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roadMassCommitIndicatorSignals) As(alias string) *roadMassCommitIndicatorSignals {
	r.roadMassCommitIndicatorSignalsDo.DO = *(r.roadMassCommitIndicatorSignalsDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roadMassCommitIndicatorSignals) updateTableName(table string) *roadMassCommitIndicatorSignals {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.IndicatorID = field.NewInt64(table, "indicator_id")
	r.Type = field.NewString(table, "type")
	r.T = field.NewInt64(table, "t")
	r.Timestamp = field.NewInt64(table, "timestamp")
	r.Band = field.NewString(table, "band")
	r.Freq = field.NewField(table, "freq")
	r.Level = field.NewInt16(table, "level")
	r.Sinr = field.NewInt16(table, "sinr")
	r.Rsrp = field.NewInt16(table, "rsrp")
	r.Rsrq = field.NewInt16(table, "rsrq")
	r.Arfcn = field.NewInt16(table, "arfcn")

	r.fillFieldMap()

	return r
}

func (r *roadMassCommitIndicatorSignals) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roadMassCommitIndicatorSignals) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 12)
	r.fieldMap["id"] = r.ID
	r.fieldMap["indicator_id"] = r.IndicatorID
	r.fieldMap["type"] = r.Type
	r.fieldMap["t"] = r.T
	r.fieldMap["timestamp"] = r.Timestamp
	r.fieldMap["band"] = r.Band
	r.fieldMap["freq"] = r.Freq
	r.fieldMap["level"] = r.Level
	r.fieldMap["sinr"] = r.Sinr
	r.fieldMap["rsrp"] = r.Rsrp
	r.fieldMap["rsrq"] = r.Rsrq
	r.fieldMap["arfcn"] = r.Arfcn
}

func (r roadMassCommitIndicatorSignals) clone(db *gorm.DB) roadMassCommitIndicatorSignals {
	r.roadMassCommitIndicatorSignalsDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roadMassCommitIndicatorSignals) replaceDB(db *gorm.DB) roadMassCommitIndicatorSignals {
	r.roadMassCommitIndicatorSignalsDo.ReplaceDB(db)
	return r
}

type roadMassCommitIndicatorSignalsDo struct{ gen.DO }

type IRoadMassCommitIndicatorSignalsDo interface {
	gen.SubQuery
	Debug() IRoadMassCommitIndicatorSignalsDo
	WithContext(ctx context.Context) IRoadMassCommitIndicatorSignalsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoadMassCommitIndicatorSignalsDo
	WriteDB() IRoadMassCommitIndicatorSignalsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoadMassCommitIndicatorSignalsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoadMassCommitIndicatorSignalsDo
	Not(conds ...gen.Condition) IRoadMassCommitIndicatorSignalsDo
	Or(conds ...gen.Condition) IRoadMassCommitIndicatorSignalsDo
	Select(conds ...field.Expr) IRoadMassCommitIndicatorSignalsDo
	Where(conds ...gen.Condition) IRoadMassCommitIndicatorSignalsDo
	Order(conds ...field.Expr) IRoadMassCommitIndicatorSignalsDo
	Distinct(cols ...field.Expr) IRoadMassCommitIndicatorSignalsDo
	Omit(cols ...field.Expr) IRoadMassCommitIndicatorSignalsDo
	Join(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorSignalsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorSignalsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorSignalsDo
	Group(cols ...field.Expr) IRoadMassCommitIndicatorSignalsDo
	Having(conds ...gen.Condition) IRoadMassCommitIndicatorSignalsDo
	Limit(limit int) IRoadMassCommitIndicatorSignalsDo
	Offset(offset int) IRoadMassCommitIndicatorSignalsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadMassCommitIndicatorSignalsDo
	Unscoped() IRoadMassCommitIndicatorSignalsDo
	Create(values ...*model.RoadMassCommitIndicatorSignals) error
	CreateInBatches(values []*model.RoadMassCommitIndicatorSignals, batchSize int) error
	Save(values ...*model.RoadMassCommitIndicatorSignals) error
	First() (*model.RoadMassCommitIndicatorSignals, error)
	Take() (*model.RoadMassCommitIndicatorSignals, error)
	Last() (*model.RoadMassCommitIndicatorSignals, error)
	Find() ([]*model.RoadMassCommitIndicatorSignals, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadMassCommitIndicatorSignals, err error)
	FindInBatches(result *[]*model.RoadMassCommitIndicatorSignals, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RoadMassCommitIndicatorSignals) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoadMassCommitIndicatorSignalsDo
	Assign(attrs ...field.AssignExpr) IRoadMassCommitIndicatorSignalsDo
	Joins(fields ...field.RelationField) IRoadMassCommitIndicatorSignalsDo
	Preload(fields ...field.RelationField) IRoadMassCommitIndicatorSignalsDo
	FirstOrInit() (*model.RoadMassCommitIndicatorSignals, error)
	FirstOrCreate() (*model.RoadMassCommitIndicatorSignals, error)
	FindByPage(offset int, limit int) (result []*model.RoadMassCommitIndicatorSignals, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoadMassCommitIndicatorSignalsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roadMassCommitIndicatorSignalsDo) Debug() IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Debug())
}

func (r roadMassCommitIndicatorSignalsDo) WithContext(ctx context.Context) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roadMassCommitIndicatorSignalsDo) ReadDB() IRoadMassCommitIndicatorSignalsDo {
	return r.Clauses(dbresolver.Read)
}

func (r roadMassCommitIndicatorSignalsDo) WriteDB() IRoadMassCommitIndicatorSignalsDo {
	return r.Clauses(dbresolver.Write)
}

func (r roadMassCommitIndicatorSignalsDo) Session(config *gorm.Session) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Session(config))
}

func (r roadMassCommitIndicatorSignalsDo) Clauses(conds ...clause.Expression) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roadMassCommitIndicatorSignalsDo) Returning(value interface{}, columns ...string) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roadMassCommitIndicatorSignalsDo) Not(conds ...gen.Condition) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roadMassCommitIndicatorSignalsDo) Or(conds ...gen.Condition) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roadMassCommitIndicatorSignalsDo) Select(conds ...field.Expr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roadMassCommitIndicatorSignalsDo) Where(conds ...gen.Condition) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roadMassCommitIndicatorSignalsDo) Order(conds ...field.Expr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roadMassCommitIndicatorSignalsDo) Distinct(cols ...field.Expr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roadMassCommitIndicatorSignalsDo) Omit(cols ...field.Expr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roadMassCommitIndicatorSignalsDo) Join(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roadMassCommitIndicatorSignalsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roadMassCommitIndicatorSignalsDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roadMassCommitIndicatorSignalsDo) Group(cols ...field.Expr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roadMassCommitIndicatorSignalsDo) Having(conds ...gen.Condition) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roadMassCommitIndicatorSignalsDo) Limit(limit int) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roadMassCommitIndicatorSignalsDo) Offset(offset int) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roadMassCommitIndicatorSignalsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roadMassCommitIndicatorSignalsDo) Unscoped() IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roadMassCommitIndicatorSignalsDo) Create(values ...*model.RoadMassCommitIndicatorSignals) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roadMassCommitIndicatorSignalsDo) CreateInBatches(values []*model.RoadMassCommitIndicatorSignals, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roadMassCommitIndicatorSignalsDo) Save(values ...*model.RoadMassCommitIndicatorSignals) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roadMassCommitIndicatorSignalsDo) First() (*model.RoadMassCommitIndicatorSignals, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicatorSignals), nil
	}
}

func (r roadMassCommitIndicatorSignalsDo) Take() (*model.RoadMassCommitIndicatorSignals, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicatorSignals), nil
	}
}

func (r roadMassCommitIndicatorSignalsDo) Last() (*model.RoadMassCommitIndicatorSignals, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicatorSignals), nil
	}
}

func (r roadMassCommitIndicatorSignalsDo) Find() ([]*model.RoadMassCommitIndicatorSignals, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoadMassCommitIndicatorSignals), err
}

func (r roadMassCommitIndicatorSignalsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadMassCommitIndicatorSignals, err error) {
	buf := make([]*model.RoadMassCommitIndicatorSignals, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roadMassCommitIndicatorSignalsDo) FindInBatches(result *[]*model.RoadMassCommitIndicatorSignals, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roadMassCommitIndicatorSignalsDo) Attrs(attrs ...field.AssignExpr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roadMassCommitIndicatorSignalsDo) Assign(attrs ...field.AssignExpr) IRoadMassCommitIndicatorSignalsDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roadMassCommitIndicatorSignalsDo) Joins(fields ...field.RelationField) IRoadMassCommitIndicatorSignalsDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roadMassCommitIndicatorSignalsDo) Preload(fields ...field.RelationField) IRoadMassCommitIndicatorSignalsDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roadMassCommitIndicatorSignalsDo) FirstOrInit() (*model.RoadMassCommitIndicatorSignals, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicatorSignals), nil
	}
}

func (r roadMassCommitIndicatorSignalsDo) FirstOrCreate() (*model.RoadMassCommitIndicatorSignals, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitIndicatorSignals), nil
	}
}

func (r roadMassCommitIndicatorSignalsDo) FindByPage(offset int, limit int) (result []*model.RoadMassCommitIndicatorSignals, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roadMassCommitIndicatorSignalsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roadMassCommitIndicatorSignalsDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roadMassCommitIndicatorSignalsDo) Delete(models ...*model.RoadMassCommitIndicatorSignals) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roadMassCommitIndicatorSignalsDo) withDO(do gen.Dao) *roadMassCommitIndicatorSignalsDo {
	r.DO = *do.(*gen.DO)
	return r
}
