// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newRoad(db *gorm.DB, opts ...gen.DOOption) road {
	_road := road{}

	_road.roadDo.UseDB(db, opts...)
	_road.roadDo.UseModel(&model.Road{})

	tableName := _road.roadDo.TableName()
	_road.ALL = field.NewAsterisk(tableName)
	_road.ID = field.NewInt64(tableName, "id")
	_road.Name = field.NewString(tableName, "name")
	_road.Code = field.NewString(tableName, "code")
	_road.Type = field.NewInt16(tableName, "type")
	_road.Distance = field.NewFloat32(tableName, "distance")
	_road.UID = field.NewInt(tableName, "uid")
	_road.Status = field.NewInt16(tableName, "status")
	_road.Description = field.NewString(tableName, "description")
	_road.CreatedAt = field.NewTime(tableName, "created_at")
	_road.UpdatedAt = field.NewTime(tableName, "updated_at")
	_road.DeletedAt = field.NewTime(tableName, "deleted_at")

	_road.fillFieldMap()

	return _road
}

type road struct {
	roadDo

	ALL         field.Asterisk
	ID          field.Int64   // 道路ID
	Name        field.String  // 道路名称
	Code        field.String  // 道路编码
	Type        field.Int16   // 道路类型 1国道 2 省道 3 高铁
	Distance    field.Float32 // 道路总长度(公里)
	UID         field.Int     // 创建后台用户ID
	Status      field.Int16   // 状态(1:正常,2:维护,3:禁用)
	Description field.String  // 描述信息
	CreatedAt   field.Time    // 创建时间
	UpdatedAt   field.Time    // 修改时间
	DeletedAt   field.Time    // 删除时间

	fieldMap map[string]field.Expr
}

func (r road) Table(newTableName string) *road {
	r.roadDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r road) As(alias string) *road {
	r.roadDo.DO = *(r.roadDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *road) updateTableName(table string) *road {
	r.ALL = field.NewAsterisk(table)
	r.ID = field.NewInt64(table, "id")
	r.Name = field.NewString(table, "name")
	r.Code = field.NewString(table, "code")
	r.Type = field.NewInt16(table, "type")
	r.Distance = field.NewFloat32(table, "distance")
	r.UID = field.NewInt(table, "uid")
	r.Status = field.NewInt16(table, "status")
	r.Description = field.NewString(table, "description")
	r.CreatedAt = field.NewTime(table, "created_at")
	r.UpdatedAt = field.NewTime(table, "updated_at")
	r.DeletedAt = field.NewTime(table, "deleted_at")

	r.fillFieldMap()

	return r
}

func (r *road) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *road) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 11)
	r.fieldMap["id"] = r.ID
	r.fieldMap["name"] = r.Name
	r.fieldMap["code"] = r.Code
	r.fieldMap["type"] = r.Type
	r.fieldMap["distance"] = r.Distance
	r.fieldMap["uid"] = r.UID
	r.fieldMap["status"] = r.Status
	r.fieldMap["description"] = r.Description
	r.fieldMap["created_at"] = r.CreatedAt
	r.fieldMap["updated_at"] = r.UpdatedAt
	r.fieldMap["deleted_at"] = r.DeletedAt
}

func (r road) clone(db *gorm.DB) road {
	r.roadDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r road) replaceDB(db *gorm.DB) road {
	r.roadDo.ReplaceDB(db)
	return r
}

type roadDo struct{ gen.DO }

type IRoadDo interface {
	gen.SubQuery
	Debug() IRoadDo
	WithContext(ctx context.Context) IRoadDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoadDo
	WriteDB() IRoadDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoadDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoadDo
	Not(conds ...gen.Condition) IRoadDo
	Or(conds ...gen.Condition) IRoadDo
	Select(conds ...field.Expr) IRoadDo
	Where(conds ...gen.Condition) IRoadDo
	Order(conds ...field.Expr) IRoadDo
	Distinct(cols ...field.Expr) IRoadDo
	Omit(cols ...field.Expr) IRoadDo
	Join(table schema.Tabler, on ...field.Expr) IRoadDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoadDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoadDo
	Group(cols ...field.Expr) IRoadDo
	Having(conds ...gen.Condition) IRoadDo
	Limit(limit int) IRoadDo
	Offset(offset int) IRoadDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadDo
	Unscoped() IRoadDo
	Create(values ...*model.Road) error
	CreateInBatches(values []*model.Road, batchSize int) error
	Save(values ...*model.Road) error
	First() (*model.Road, error)
	Take() (*model.Road, error)
	Last() (*model.Road, error)
	Find() ([]*model.Road, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Road, err error)
	FindInBatches(result *[]*model.Road, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Road) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoadDo
	Assign(attrs ...field.AssignExpr) IRoadDo
	Joins(fields ...field.RelationField) IRoadDo
	Preload(fields ...field.RelationField) IRoadDo
	FirstOrInit() (*model.Road, error)
	FirstOrCreate() (*model.Road, error)
	FindByPage(offset int, limit int) (result []*model.Road, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoadDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roadDo) Debug() IRoadDo {
	return r.withDO(r.DO.Debug())
}

func (r roadDo) WithContext(ctx context.Context) IRoadDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roadDo) ReadDB() IRoadDo {
	return r.Clauses(dbresolver.Read)
}

func (r roadDo) WriteDB() IRoadDo {
	return r.Clauses(dbresolver.Write)
}

func (r roadDo) Session(config *gorm.Session) IRoadDo {
	return r.withDO(r.DO.Session(config))
}

func (r roadDo) Clauses(conds ...clause.Expression) IRoadDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roadDo) Returning(value interface{}, columns ...string) IRoadDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roadDo) Not(conds ...gen.Condition) IRoadDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roadDo) Or(conds ...gen.Condition) IRoadDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roadDo) Select(conds ...field.Expr) IRoadDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roadDo) Where(conds ...gen.Condition) IRoadDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roadDo) Order(conds ...field.Expr) IRoadDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roadDo) Distinct(cols ...field.Expr) IRoadDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roadDo) Omit(cols ...field.Expr) IRoadDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roadDo) Join(table schema.Tabler, on ...field.Expr) IRoadDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roadDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoadDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roadDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoadDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roadDo) Group(cols ...field.Expr) IRoadDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roadDo) Having(conds ...gen.Condition) IRoadDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roadDo) Limit(limit int) IRoadDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roadDo) Offset(offset int) IRoadDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roadDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roadDo) Unscoped() IRoadDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roadDo) Create(values ...*model.Road) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roadDo) CreateInBatches(values []*model.Road, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roadDo) Save(values ...*model.Road) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roadDo) First() (*model.Road, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Road), nil
	}
}

func (r roadDo) Take() (*model.Road, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Road), nil
	}
}

func (r roadDo) Last() (*model.Road, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Road), nil
	}
}

func (r roadDo) Find() ([]*model.Road, error) {
	result, err := r.DO.Find()
	return result.([]*model.Road), err
}

func (r roadDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Road, err error) {
	buf := make([]*model.Road, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roadDo) FindInBatches(result *[]*model.Road, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roadDo) Attrs(attrs ...field.AssignExpr) IRoadDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roadDo) Assign(attrs ...field.AssignExpr) IRoadDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roadDo) Joins(fields ...field.RelationField) IRoadDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roadDo) Preload(fields ...field.RelationField) IRoadDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roadDo) FirstOrInit() (*model.Road, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Road), nil
	}
}

func (r roadDo) FirstOrCreate() (*model.Road, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Road), nil
	}
}

func (r roadDo) FindByPage(offset int, limit int) (result []*model.Road, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roadDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roadDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roadDo) Delete(models ...*model.Road) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roadDo) withDO(do gen.Dao) *roadDo {
	r.DO = *do.(*gen.DO)
	return r
}
