// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newRoadCommitServer(db *gorm.DB, opts ...gen.DOOption) roadCommitServer {
	_roadCommitServer := roadCommitServer{}

	_roadCommitServer.roadCommitServerDo.UseDB(db, opts...)
	_roadCommitServer.roadCommitServerDo.UseModel(&model.RoadCommitServer{})

	tableName := _roadCommitServer.roadCommitServerDo.TableName()
	_roadCommitServer.ALL = field.NewAsterisk(tableName)
	_roadCommitServer.RoadCommitID = field.NewInt64(tableName, "road_commit_id")
	_roadCommitServer.DlLoaded = field.NewInt(tableName, "dl_loaded")
	_roadCommitServer.UlLoaded = field.NewInt(tableName, "ul_loaded")
	_roadCommitServer.IPAddress = field.NewString(tableName, "ip_address")
	_roadCommitServer.VersionCode = field.NewInt16(tableName, "version_code")
	_roadCommitServer.VersionName = field.NewString(tableName, "version_name")

	_roadCommitServer.fillFieldMap()

	return _roadCommitServer
}

type roadCommitServer struct {
	roadCommitServerDo

	ALL          field.Asterisk
	RoadCommitID field.Int64  // 路测提交ID
	DlLoaded     field.Int    // 下行已接收数据量
	UlLoaded     field.Int    // 上行已发送数据量
	IPAddress    field.String // IP地址
	VersionCode  field.Int16  // App内部版本号
	VersionName  field.String // App展示版本号

	fieldMap map[string]field.Expr
}

func (r roadCommitServer) Table(newTableName string) *roadCommitServer {
	r.roadCommitServerDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roadCommitServer) As(alias string) *roadCommitServer {
	r.roadCommitServerDo.DO = *(r.roadCommitServerDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roadCommitServer) updateTableName(table string) *roadCommitServer {
	r.ALL = field.NewAsterisk(table)
	r.RoadCommitID = field.NewInt64(table, "road_commit_id")
	r.DlLoaded = field.NewInt(table, "dl_loaded")
	r.UlLoaded = field.NewInt(table, "ul_loaded")
	r.IPAddress = field.NewString(table, "ip_address")
	r.VersionCode = field.NewInt16(table, "version_code")
	r.VersionName = field.NewString(table, "version_name")

	r.fillFieldMap()

	return r
}

func (r *roadCommitServer) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roadCommitServer) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 6)
	r.fieldMap["road_commit_id"] = r.RoadCommitID
	r.fieldMap["dl_loaded"] = r.DlLoaded
	r.fieldMap["ul_loaded"] = r.UlLoaded
	r.fieldMap["ip_address"] = r.IPAddress
	r.fieldMap["version_code"] = r.VersionCode
	r.fieldMap["version_name"] = r.VersionName
}

func (r roadCommitServer) clone(db *gorm.DB) roadCommitServer {
	r.roadCommitServerDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roadCommitServer) replaceDB(db *gorm.DB) roadCommitServer {
	r.roadCommitServerDo.ReplaceDB(db)
	return r
}

type roadCommitServerDo struct{ gen.DO }

type IRoadCommitServerDo interface {
	gen.SubQuery
	Debug() IRoadCommitServerDo
	WithContext(ctx context.Context) IRoadCommitServerDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoadCommitServerDo
	WriteDB() IRoadCommitServerDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoadCommitServerDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoadCommitServerDo
	Not(conds ...gen.Condition) IRoadCommitServerDo
	Or(conds ...gen.Condition) IRoadCommitServerDo
	Select(conds ...field.Expr) IRoadCommitServerDo
	Where(conds ...gen.Condition) IRoadCommitServerDo
	Order(conds ...field.Expr) IRoadCommitServerDo
	Distinct(cols ...field.Expr) IRoadCommitServerDo
	Omit(cols ...field.Expr) IRoadCommitServerDo
	Join(table schema.Tabler, on ...field.Expr) IRoadCommitServerDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoadCommitServerDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoadCommitServerDo
	Group(cols ...field.Expr) IRoadCommitServerDo
	Having(conds ...gen.Condition) IRoadCommitServerDo
	Limit(limit int) IRoadCommitServerDo
	Offset(offset int) IRoadCommitServerDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadCommitServerDo
	Unscoped() IRoadCommitServerDo
	Create(values ...*model.RoadCommitServer) error
	CreateInBatches(values []*model.RoadCommitServer, batchSize int) error
	Save(values ...*model.RoadCommitServer) error
	First() (*model.RoadCommitServer, error)
	Take() (*model.RoadCommitServer, error)
	Last() (*model.RoadCommitServer, error)
	Find() ([]*model.RoadCommitServer, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadCommitServer, err error)
	FindInBatches(result *[]*model.RoadCommitServer, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RoadCommitServer) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoadCommitServerDo
	Assign(attrs ...field.AssignExpr) IRoadCommitServerDo
	Joins(fields ...field.RelationField) IRoadCommitServerDo
	Preload(fields ...field.RelationField) IRoadCommitServerDo
	FirstOrInit() (*model.RoadCommitServer, error)
	FirstOrCreate() (*model.RoadCommitServer, error)
	FindByPage(offset int, limit int) (result []*model.RoadCommitServer, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoadCommitServerDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roadCommitServerDo) Debug() IRoadCommitServerDo {
	return r.withDO(r.DO.Debug())
}

func (r roadCommitServerDo) WithContext(ctx context.Context) IRoadCommitServerDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roadCommitServerDo) ReadDB() IRoadCommitServerDo {
	return r.Clauses(dbresolver.Read)
}

func (r roadCommitServerDo) WriteDB() IRoadCommitServerDo {
	return r.Clauses(dbresolver.Write)
}

func (r roadCommitServerDo) Session(config *gorm.Session) IRoadCommitServerDo {
	return r.withDO(r.DO.Session(config))
}

func (r roadCommitServerDo) Clauses(conds ...clause.Expression) IRoadCommitServerDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roadCommitServerDo) Returning(value interface{}, columns ...string) IRoadCommitServerDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roadCommitServerDo) Not(conds ...gen.Condition) IRoadCommitServerDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roadCommitServerDo) Or(conds ...gen.Condition) IRoadCommitServerDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roadCommitServerDo) Select(conds ...field.Expr) IRoadCommitServerDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roadCommitServerDo) Where(conds ...gen.Condition) IRoadCommitServerDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roadCommitServerDo) Order(conds ...field.Expr) IRoadCommitServerDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roadCommitServerDo) Distinct(cols ...field.Expr) IRoadCommitServerDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roadCommitServerDo) Omit(cols ...field.Expr) IRoadCommitServerDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roadCommitServerDo) Join(table schema.Tabler, on ...field.Expr) IRoadCommitServerDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roadCommitServerDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoadCommitServerDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roadCommitServerDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoadCommitServerDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roadCommitServerDo) Group(cols ...field.Expr) IRoadCommitServerDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roadCommitServerDo) Having(conds ...gen.Condition) IRoadCommitServerDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roadCommitServerDo) Limit(limit int) IRoadCommitServerDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roadCommitServerDo) Offset(offset int) IRoadCommitServerDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roadCommitServerDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadCommitServerDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roadCommitServerDo) Unscoped() IRoadCommitServerDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roadCommitServerDo) Create(values ...*model.RoadCommitServer) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roadCommitServerDo) CreateInBatches(values []*model.RoadCommitServer, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roadCommitServerDo) Save(values ...*model.RoadCommitServer) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roadCommitServerDo) First() (*model.RoadCommitServer, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadCommitServer), nil
	}
}

func (r roadCommitServerDo) Take() (*model.RoadCommitServer, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadCommitServer), nil
	}
}

func (r roadCommitServerDo) Last() (*model.RoadCommitServer, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadCommitServer), nil
	}
}

func (r roadCommitServerDo) Find() ([]*model.RoadCommitServer, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoadCommitServer), err
}

func (r roadCommitServerDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadCommitServer, err error) {
	buf := make([]*model.RoadCommitServer, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roadCommitServerDo) FindInBatches(result *[]*model.RoadCommitServer, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roadCommitServerDo) Attrs(attrs ...field.AssignExpr) IRoadCommitServerDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roadCommitServerDo) Assign(attrs ...field.AssignExpr) IRoadCommitServerDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roadCommitServerDo) Joins(fields ...field.RelationField) IRoadCommitServerDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roadCommitServerDo) Preload(fields ...field.RelationField) IRoadCommitServerDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roadCommitServerDo) FirstOrInit() (*model.RoadCommitServer, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadCommitServer), nil
	}
}

func (r roadCommitServerDo) FirstOrCreate() (*model.RoadCommitServer, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadCommitServer), nil
	}
}

func (r roadCommitServerDo) FindByPage(offset int, limit int) (result []*model.RoadCommitServer, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roadCommitServerDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roadCommitServerDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roadCommitServerDo) Delete(models ...*model.RoadCommitServer) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roadCommitServerDo) withDO(do gen.Dao) *roadCommitServerDo {
	r.DO = *do.(*gen.DO)
	return r
}
