// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newRoadMassCommitSpeedDetails(db *gorm.DB, opts ...gen.DOOption) roadMassCommitSpeedDetails {
	_roadMassCommitSpeedDetails := roadMassCommitSpeedDetails{}

	_roadMassCommitSpeedDetails.roadMassCommitSpeedDetailsDo.UseDB(db, opts...)
	_roadMassCommitSpeedDetails.roadMassCommitSpeedDetailsDo.UseModel(&model.RoadMassCommitSpeedDetails{})

	tableName := _roadMassCommitSpeedDetails.roadMassCommitSpeedDetailsDo.TableName()
	_roadMassCommitSpeedDetails.ALL = field.NewAsterisk(tableName)
	_roadMassCommitSpeedDetails.CommitSpeedID = field.NewInt64(tableName, "commit_speed_id")
	_roadMassCommitSpeedDetails.Upload = field.NewField(tableName, "upload")
	_roadMassCommitSpeedDetails.Download = field.NewField(tableName, "download")

	_roadMassCommitSpeedDetails.fillFieldMap()

	return _roadMassCommitSpeedDetails
}

type roadMassCommitSpeedDetails struct {
	roadMassCommitSpeedDetailsDo

	ALL           field.Asterisk
	CommitSpeedID field.Int64 // 路测众测提交上下行速率ID
	Upload        field.Field // 上传速率
	Download      field.Field // 下载速率

	fieldMap map[string]field.Expr
}

func (r roadMassCommitSpeedDetails) Table(newTableName string) *roadMassCommitSpeedDetails {
	r.roadMassCommitSpeedDetailsDo.UseTable(newTableName)
	return r.updateTableName(newTableName)
}

func (r roadMassCommitSpeedDetails) As(alias string) *roadMassCommitSpeedDetails {
	r.roadMassCommitSpeedDetailsDo.DO = *(r.roadMassCommitSpeedDetailsDo.As(alias).(*gen.DO))
	return r.updateTableName(alias)
}

func (r *roadMassCommitSpeedDetails) updateTableName(table string) *roadMassCommitSpeedDetails {
	r.ALL = field.NewAsterisk(table)
	r.CommitSpeedID = field.NewInt64(table, "commit_speed_id")
	r.Upload = field.NewField(table, "upload")
	r.Download = field.NewField(table, "download")

	r.fillFieldMap()

	return r
}

func (r *roadMassCommitSpeedDetails) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := r.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (r *roadMassCommitSpeedDetails) fillFieldMap() {
	r.fieldMap = make(map[string]field.Expr, 3)
	r.fieldMap["commit_speed_id"] = r.CommitSpeedID
	r.fieldMap["upload"] = r.Upload
	r.fieldMap["download"] = r.Download
}

func (r roadMassCommitSpeedDetails) clone(db *gorm.DB) roadMassCommitSpeedDetails {
	r.roadMassCommitSpeedDetailsDo.ReplaceConnPool(db.Statement.ConnPool)
	return r
}

func (r roadMassCommitSpeedDetails) replaceDB(db *gorm.DB) roadMassCommitSpeedDetails {
	r.roadMassCommitSpeedDetailsDo.ReplaceDB(db)
	return r
}

type roadMassCommitSpeedDetailsDo struct{ gen.DO }

type IRoadMassCommitSpeedDetailsDo interface {
	gen.SubQuery
	Debug() IRoadMassCommitSpeedDetailsDo
	WithContext(ctx context.Context) IRoadMassCommitSpeedDetailsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IRoadMassCommitSpeedDetailsDo
	WriteDB() IRoadMassCommitSpeedDetailsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IRoadMassCommitSpeedDetailsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IRoadMassCommitSpeedDetailsDo
	Not(conds ...gen.Condition) IRoadMassCommitSpeedDetailsDo
	Or(conds ...gen.Condition) IRoadMassCommitSpeedDetailsDo
	Select(conds ...field.Expr) IRoadMassCommitSpeedDetailsDo
	Where(conds ...gen.Condition) IRoadMassCommitSpeedDetailsDo
	Order(conds ...field.Expr) IRoadMassCommitSpeedDetailsDo
	Distinct(cols ...field.Expr) IRoadMassCommitSpeedDetailsDo
	Omit(cols ...field.Expr) IRoadMassCommitSpeedDetailsDo
	Join(table schema.Tabler, on ...field.Expr) IRoadMassCommitSpeedDetailsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitSpeedDetailsDo
	RightJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitSpeedDetailsDo
	Group(cols ...field.Expr) IRoadMassCommitSpeedDetailsDo
	Having(conds ...gen.Condition) IRoadMassCommitSpeedDetailsDo
	Limit(limit int) IRoadMassCommitSpeedDetailsDo
	Offset(offset int) IRoadMassCommitSpeedDetailsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadMassCommitSpeedDetailsDo
	Unscoped() IRoadMassCommitSpeedDetailsDo
	Create(values ...*model.RoadMassCommitSpeedDetails) error
	CreateInBatches(values []*model.RoadMassCommitSpeedDetails, batchSize int) error
	Save(values ...*model.RoadMassCommitSpeedDetails) error
	First() (*model.RoadMassCommitSpeedDetails, error)
	Take() (*model.RoadMassCommitSpeedDetails, error)
	Last() (*model.RoadMassCommitSpeedDetails, error)
	Find() ([]*model.RoadMassCommitSpeedDetails, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadMassCommitSpeedDetails, err error)
	FindInBatches(result *[]*model.RoadMassCommitSpeedDetails, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.RoadMassCommitSpeedDetails) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IRoadMassCommitSpeedDetailsDo
	Assign(attrs ...field.AssignExpr) IRoadMassCommitSpeedDetailsDo
	Joins(fields ...field.RelationField) IRoadMassCommitSpeedDetailsDo
	Preload(fields ...field.RelationField) IRoadMassCommitSpeedDetailsDo
	FirstOrInit() (*model.RoadMassCommitSpeedDetails, error)
	FirstOrCreate() (*model.RoadMassCommitSpeedDetails, error)
	FindByPage(offset int, limit int) (result []*model.RoadMassCommitSpeedDetails, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IRoadMassCommitSpeedDetailsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (r roadMassCommitSpeedDetailsDo) Debug() IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Debug())
}

func (r roadMassCommitSpeedDetailsDo) WithContext(ctx context.Context) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.WithContext(ctx))
}

func (r roadMassCommitSpeedDetailsDo) ReadDB() IRoadMassCommitSpeedDetailsDo {
	return r.Clauses(dbresolver.Read)
}

func (r roadMassCommitSpeedDetailsDo) WriteDB() IRoadMassCommitSpeedDetailsDo {
	return r.Clauses(dbresolver.Write)
}

func (r roadMassCommitSpeedDetailsDo) Session(config *gorm.Session) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Session(config))
}

func (r roadMassCommitSpeedDetailsDo) Clauses(conds ...clause.Expression) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Clauses(conds...))
}

func (r roadMassCommitSpeedDetailsDo) Returning(value interface{}, columns ...string) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Returning(value, columns...))
}

func (r roadMassCommitSpeedDetailsDo) Not(conds ...gen.Condition) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Not(conds...))
}

func (r roadMassCommitSpeedDetailsDo) Or(conds ...gen.Condition) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Or(conds...))
}

func (r roadMassCommitSpeedDetailsDo) Select(conds ...field.Expr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Select(conds...))
}

func (r roadMassCommitSpeedDetailsDo) Where(conds ...gen.Condition) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Where(conds...))
}

func (r roadMassCommitSpeedDetailsDo) Order(conds ...field.Expr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Order(conds...))
}

func (r roadMassCommitSpeedDetailsDo) Distinct(cols ...field.Expr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Distinct(cols...))
}

func (r roadMassCommitSpeedDetailsDo) Omit(cols ...field.Expr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Omit(cols...))
}

func (r roadMassCommitSpeedDetailsDo) Join(table schema.Tabler, on ...field.Expr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Join(table, on...))
}

func (r roadMassCommitSpeedDetailsDo) LeftJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.LeftJoin(table, on...))
}

func (r roadMassCommitSpeedDetailsDo) RightJoin(table schema.Tabler, on ...field.Expr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.RightJoin(table, on...))
}

func (r roadMassCommitSpeedDetailsDo) Group(cols ...field.Expr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Group(cols...))
}

func (r roadMassCommitSpeedDetailsDo) Having(conds ...gen.Condition) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Having(conds...))
}

func (r roadMassCommitSpeedDetailsDo) Limit(limit int) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Limit(limit))
}

func (r roadMassCommitSpeedDetailsDo) Offset(offset int) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Offset(offset))
}

func (r roadMassCommitSpeedDetailsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Scopes(funcs...))
}

func (r roadMassCommitSpeedDetailsDo) Unscoped() IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Unscoped())
}

func (r roadMassCommitSpeedDetailsDo) Create(values ...*model.RoadMassCommitSpeedDetails) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Create(values)
}

func (r roadMassCommitSpeedDetailsDo) CreateInBatches(values []*model.RoadMassCommitSpeedDetails, batchSize int) error {
	return r.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (r roadMassCommitSpeedDetailsDo) Save(values ...*model.RoadMassCommitSpeedDetails) error {
	if len(values) == 0 {
		return nil
	}
	return r.DO.Save(values)
}

func (r roadMassCommitSpeedDetailsDo) First() (*model.RoadMassCommitSpeedDetails, error) {
	if result, err := r.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitSpeedDetails), nil
	}
}

func (r roadMassCommitSpeedDetailsDo) Take() (*model.RoadMassCommitSpeedDetails, error) {
	if result, err := r.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitSpeedDetails), nil
	}
}

func (r roadMassCommitSpeedDetailsDo) Last() (*model.RoadMassCommitSpeedDetails, error) {
	if result, err := r.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitSpeedDetails), nil
	}
}

func (r roadMassCommitSpeedDetailsDo) Find() ([]*model.RoadMassCommitSpeedDetails, error) {
	result, err := r.DO.Find()
	return result.([]*model.RoadMassCommitSpeedDetails), err
}

func (r roadMassCommitSpeedDetailsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.RoadMassCommitSpeedDetails, err error) {
	buf := make([]*model.RoadMassCommitSpeedDetails, 0, batchSize)
	err = r.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (r roadMassCommitSpeedDetailsDo) FindInBatches(result *[]*model.RoadMassCommitSpeedDetails, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return r.DO.FindInBatches(result, batchSize, fc)
}

func (r roadMassCommitSpeedDetailsDo) Attrs(attrs ...field.AssignExpr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Attrs(attrs...))
}

func (r roadMassCommitSpeedDetailsDo) Assign(attrs ...field.AssignExpr) IRoadMassCommitSpeedDetailsDo {
	return r.withDO(r.DO.Assign(attrs...))
}

func (r roadMassCommitSpeedDetailsDo) Joins(fields ...field.RelationField) IRoadMassCommitSpeedDetailsDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Joins(_f))
	}
	return &r
}

func (r roadMassCommitSpeedDetailsDo) Preload(fields ...field.RelationField) IRoadMassCommitSpeedDetailsDo {
	for _, _f := range fields {
		r = *r.withDO(r.DO.Preload(_f))
	}
	return &r
}

func (r roadMassCommitSpeedDetailsDo) FirstOrInit() (*model.RoadMassCommitSpeedDetails, error) {
	if result, err := r.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitSpeedDetails), nil
	}
}

func (r roadMassCommitSpeedDetailsDo) FirstOrCreate() (*model.RoadMassCommitSpeedDetails, error) {
	if result, err := r.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.RoadMassCommitSpeedDetails), nil
	}
}

func (r roadMassCommitSpeedDetailsDo) FindByPage(offset int, limit int) (result []*model.RoadMassCommitSpeedDetails, count int64, err error) {
	result, err = r.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = r.Offset(-1).Limit(-1).Count()
	return
}

func (r roadMassCommitSpeedDetailsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = r.Count()
	if err != nil {
		return
	}

	err = r.Offset(offset).Limit(limit).Scan(result)
	return
}

func (r roadMassCommitSpeedDetailsDo) Scan(result interface{}) (err error) {
	return r.DO.Scan(result)
}

func (r roadMassCommitSpeedDetailsDo) Delete(models ...*model.RoadMassCommitSpeedDetails) (result gen.ResultInfo, err error) {
	return r.DO.Delete(models)
}

func (r *roadMassCommitSpeedDetailsDo) withDO(do gen.Dao) *roadMassCommitSpeedDetailsDo {
	r.DO = *do.(*gen.DO)
	return r
}
