// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newSettings(db *gorm.DB, opts ...gen.DOOption) settings {
	_settings := settings{}

	_settings.settingsDo.UseDB(db, opts...)
	_settings.settingsDo.UseModel(&model.Settings{})

	tableName := _settings.settingsDo.TableName()
	_settings.ALL = field.NewAsterisk(tableName)
	_settings.ID = field.NewInt(tableName, "id")
	_settings.Code = field.NewString(tableName, "code")
	_settings.Title = field.NewString(tableName, "title")
	_settings.Sort = field.NewInt(tableName, "sort")
	_settings.Disabled = field.NewInt16(tableName, "disabled")
	_settings.CreatedAt = field.NewTime(tableName, "created_at")
	_settings.UpdatedAt = field.NewTime(tableName, "updated_at")
	_settings.DeletedAt = field.NewTime(tableName, "deleted_at")

	_settings.fillFieldMap()

	return _settings
}

type settings struct {
	settingsDo

	ALL       field.Asterisk
	ID        field.Int    // 主键
	Code      field.String // 调用编码
	Title     field.String // 配置名称
	Sort      field.Int    // 显示顺序
	Disabled  field.Int16  // 禁用状态
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Time   // 修改时间
	DeletedAt field.Time   // 删除时间

	fieldMap map[string]field.Expr
}

func (s settings) Table(newTableName string) *settings {
	s.settingsDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s settings) As(alias string) *settings {
	s.settingsDo.DO = *(s.settingsDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *settings) updateTableName(table string) *settings {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt(table, "id")
	s.Code = field.NewString(table, "code")
	s.Title = field.NewString(table, "title")
	s.Sort = field.NewInt(table, "sort")
	s.Disabled = field.NewInt16(table, "disabled")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewTime(table, "updated_at")
	s.DeletedAt = field.NewTime(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *settings) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *settings) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["code"] = s.Code
	s.fieldMap["title"] = s.Title
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["disabled"] = s.Disabled
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s settings) clone(db *gorm.DB) settings {
	s.settingsDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s settings) replaceDB(db *gorm.DB) settings {
	s.settingsDo.ReplaceDB(db)
	return s
}

type settingsDo struct{ gen.DO }

type ISettingsDo interface {
	gen.SubQuery
	Debug() ISettingsDo
	WithContext(ctx context.Context) ISettingsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISettingsDo
	WriteDB() ISettingsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISettingsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISettingsDo
	Not(conds ...gen.Condition) ISettingsDo
	Or(conds ...gen.Condition) ISettingsDo
	Select(conds ...field.Expr) ISettingsDo
	Where(conds ...gen.Condition) ISettingsDo
	Order(conds ...field.Expr) ISettingsDo
	Distinct(cols ...field.Expr) ISettingsDo
	Omit(cols ...field.Expr) ISettingsDo
	Join(table schema.Tabler, on ...field.Expr) ISettingsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISettingsDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISettingsDo
	Group(cols ...field.Expr) ISettingsDo
	Having(conds ...gen.Condition) ISettingsDo
	Limit(limit int) ISettingsDo
	Offset(offset int) ISettingsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISettingsDo
	Unscoped() ISettingsDo
	Create(values ...*model.Settings) error
	CreateInBatches(values []*model.Settings, batchSize int) error
	Save(values ...*model.Settings) error
	First() (*model.Settings, error)
	Take() (*model.Settings, error)
	Last() (*model.Settings, error)
	Find() ([]*model.Settings, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Settings, err error)
	FindInBatches(result *[]*model.Settings, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Settings) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISettingsDo
	Assign(attrs ...field.AssignExpr) ISettingsDo
	Joins(fields ...field.RelationField) ISettingsDo
	Preload(fields ...field.RelationField) ISettingsDo
	FirstOrInit() (*model.Settings, error)
	FirstOrCreate() (*model.Settings, error)
	FindByPage(offset int, limit int) (result []*model.Settings, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISettingsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s settingsDo) Debug() ISettingsDo {
	return s.withDO(s.DO.Debug())
}

func (s settingsDo) WithContext(ctx context.Context) ISettingsDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s settingsDo) ReadDB() ISettingsDo {
	return s.Clauses(dbresolver.Read)
}

func (s settingsDo) WriteDB() ISettingsDo {
	return s.Clauses(dbresolver.Write)
}

func (s settingsDo) Session(config *gorm.Session) ISettingsDo {
	return s.withDO(s.DO.Session(config))
}

func (s settingsDo) Clauses(conds ...clause.Expression) ISettingsDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s settingsDo) Returning(value interface{}, columns ...string) ISettingsDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s settingsDo) Not(conds ...gen.Condition) ISettingsDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s settingsDo) Or(conds ...gen.Condition) ISettingsDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s settingsDo) Select(conds ...field.Expr) ISettingsDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s settingsDo) Where(conds ...gen.Condition) ISettingsDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s settingsDo) Order(conds ...field.Expr) ISettingsDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s settingsDo) Distinct(cols ...field.Expr) ISettingsDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s settingsDo) Omit(cols ...field.Expr) ISettingsDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s settingsDo) Join(table schema.Tabler, on ...field.Expr) ISettingsDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s settingsDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISettingsDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s settingsDo) RightJoin(table schema.Tabler, on ...field.Expr) ISettingsDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s settingsDo) Group(cols ...field.Expr) ISettingsDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s settingsDo) Having(conds ...gen.Condition) ISettingsDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s settingsDo) Limit(limit int) ISettingsDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s settingsDo) Offset(offset int) ISettingsDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s settingsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISettingsDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s settingsDo) Unscoped() ISettingsDo {
	return s.withDO(s.DO.Unscoped())
}

func (s settingsDo) Create(values ...*model.Settings) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s settingsDo) CreateInBatches(values []*model.Settings, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s settingsDo) Save(values ...*model.Settings) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s settingsDo) First() (*model.Settings, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Settings), nil
	}
}

func (s settingsDo) Take() (*model.Settings, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Settings), nil
	}
}

func (s settingsDo) Last() (*model.Settings, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Settings), nil
	}
}

func (s settingsDo) Find() ([]*model.Settings, error) {
	result, err := s.DO.Find()
	return result.([]*model.Settings), err
}

func (s settingsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Settings, err error) {
	buf := make([]*model.Settings, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s settingsDo) FindInBatches(result *[]*model.Settings, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s settingsDo) Attrs(attrs ...field.AssignExpr) ISettingsDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s settingsDo) Assign(attrs ...field.AssignExpr) ISettingsDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s settingsDo) Joins(fields ...field.RelationField) ISettingsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s settingsDo) Preload(fields ...field.RelationField) ISettingsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s settingsDo) FirstOrInit() (*model.Settings, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Settings), nil
	}
}

func (s settingsDo) FirstOrCreate() (*model.Settings, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Settings), nil
	}
}

func (s settingsDo) FindByPage(offset int, limit int) (result []*model.Settings, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s settingsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s settingsDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s settingsDo) Delete(models ...*model.Settings) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *settingsDo) withDO(do gen.Dao) *settingsDo {
	s.DO = *do.(*gen.DO)
	return s
}
