// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newTaskPlaces(db *gorm.DB, opts ...gen.DOOption) taskPlaces {
	_taskPlaces := taskPlaces{}

	_taskPlaces.taskPlacesDo.UseDB(db, opts...)
	_taskPlaces.taskPlacesDo.UseModel(&model.TaskPlaces{})

	tableName := _taskPlaces.taskPlacesDo.TableName()
	_taskPlaces.ALL = field.NewAsterisk(tableName)
	_taskPlaces.TaskID = field.NewInt(tableName, "task_id")
	_taskPlaces.PlaceID = field.NewInt64(tableName, "place_id")
	_taskPlaces.PingCount = field.NewInt16(tableName, "ping_count")
	_taskPlaces.CompleteCount = field.NewInt16(tableName, "complete_count")
	_taskPlaces.CompletedAt = field.NewTime(tableName, "completed_at")
	_taskPlaces.CreatedAt = field.NewTime(tableName, "created_at")
	_taskPlaces.UpdatedAt = field.NewTime(tableName, "updated_at")

	_taskPlaces.fillFieldMap()

	return _taskPlaces
}

type taskPlaces struct {
	taskPlacesDo

	ALL           field.Asterisk
	TaskID        field.Int   // 任务ID
	PlaceID       field.Int64 // 场所ID
	PingCount     field.Int16 // 场所测试次数
	CompleteCount field.Int16 // 完成次数
	CompletedAt   field.Time  // 完成时间
	CreatedAt     field.Time  // 创建时间
	UpdatedAt     field.Time  // 修改时间

	fieldMap map[string]field.Expr
}

func (t taskPlaces) Table(newTableName string) *taskPlaces {
	t.taskPlacesDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t taskPlaces) As(alias string) *taskPlaces {
	t.taskPlacesDo.DO = *(t.taskPlacesDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *taskPlaces) updateTableName(table string) *taskPlaces {
	t.ALL = field.NewAsterisk(table)
	t.TaskID = field.NewInt(table, "task_id")
	t.PlaceID = field.NewInt64(table, "place_id")
	t.PingCount = field.NewInt16(table, "ping_count")
	t.CompleteCount = field.NewInt16(table, "complete_count")
	t.CompletedAt = field.NewTime(table, "completed_at")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")

	t.fillFieldMap()

	return t
}

func (t *taskPlaces) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *taskPlaces) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 7)
	t.fieldMap["task_id"] = t.TaskID
	t.fieldMap["place_id"] = t.PlaceID
	t.fieldMap["ping_count"] = t.PingCount
	t.fieldMap["complete_count"] = t.CompleteCount
	t.fieldMap["completed_at"] = t.CompletedAt
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
}

func (t taskPlaces) clone(db *gorm.DB) taskPlaces {
	t.taskPlacesDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t taskPlaces) replaceDB(db *gorm.DB) taskPlaces {
	t.taskPlacesDo.ReplaceDB(db)
	return t
}

type taskPlacesDo struct{ gen.DO }

type ITaskPlacesDo interface {
	gen.SubQuery
	Debug() ITaskPlacesDo
	WithContext(ctx context.Context) ITaskPlacesDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITaskPlacesDo
	WriteDB() ITaskPlacesDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITaskPlacesDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITaskPlacesDo
	Not(conds ...gen.Condition) ITaskPlacesDo
	Or(conds ...gen.Condition) ITaskPlacesDo
	Select(conds ...field.Expr) ITaskPlacesDo
	Where(conds ...gen.Condition) ITaskPlacesDo
	Order(conds ...field.Expr) ITaskPlacesDo
	Distinct(cols ...field.Expr) ITaskPlacesDo
	Omit(cols ...field.Expr) ITaskPlacesDo
	Join(table schema.Tabler, on ...field.Expr) ITaskPlacesDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITaskPlacesDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITaskPlacesDo
	Group(cols ...field.Expr) ITaskPlacesDo
	Having(conds ...gen.Condition) ITaskPlacesDo
	Limit(limit int) ITaskPlacesDo
	Offset(offset int) ITaskPlacesDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskPlacesDo
	Unscoped() ITaskPlacesDo
	Create(values ...*model.TaskPlaces) error
	CreateInBatches(values []*model.TaskPlaces, batchSize int) error
	Save(values ...*model.TaskPlaces) error
	First() (*model.TaskPlaces, error)
	Take() (*model.TaskPlaces, error)
	Last() (*model.TaskPlaces, error)
	Find() ([]*model.TaskPlaces, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TaskPlaces, err error)
	FindInBatches(result *[]*model.TaskPlaces, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.TaskPlaces) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITaskPlacesDo
	Assign(attrs ...field.AssignExpr) ITaskPlacesDo
	Joins(fields ...field.RelationField) ITaskPlacesDo
	Preload(fields ...field.RelationField) ITaskPlacesDo
	FirstOrInit() (*model.TaskPlaces, error)
	FirstOrCreate() (*model.TaskPlaces, error)
	FindByPage(offset int, limit int) (result []*model.TaskPlaces, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITaskPlacesDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t taskPlacesDo) Debug() ITaskPlacesDo {
	return t.withDO(t.DO.Debug())
}

func (t taskPlacesDo) WithContext(ctx context.Context) ITaskPlacesDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t taskPlacesDo) ReadDB() ITaskPlacesDo {
	return t.Clauses(dbresolver.Read)
}

func (t taskPlacesDo) WriteDB() ITaskPlacesDo {
	return t.Clauses(dbresolver.Write)
}

func (t taskPlacesDo) Session(config *gorm.Session) ITaskPlacesDo {
	return t.withDO(t.DO.Session(config))
}

func (t taskPlacesDo) Clauses(conds ...clause.Expression) ITaskPlacesDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t taskPlacesDo) Returning(value interface{}, columns ...string) ITaskPlacesDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t taskPlacesDo) Not(conds ...gen.Condition) ITaskPlacesDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t taskPlacesDo) Or(conds ...gen.Condition) ITaskPlacesDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t taskPlacesDo) Select(conds ...field.Expr) ITaskPlacesDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t taskPlacesDo) Where(conds ...gen.Condition) ITaskPlacesDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t taskPlacesDo) Order(conds ...field.Expr) ITaskPlacesDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t taskPlacesDo) Distinct(cols ...field.Expr) ITaskPlacesDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t taskPlacesDo) Omit(cols ...field.Expr) ITaskPlacesDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t taskPlacesDo) Join(table schema.Tabler, on ...field.Expr) ITaskPlacesDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t taskPlacesDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITaskPlacesDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t taskPlacesDo) RightJoin(table schema.Tabler, on ...field.Expr) ITaskPlacesDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t taskPlacesDo) Group(cols ...field.Expr) ITaskPlacesDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t taskPlacesDo) Having(conds ...gen.Condition) ITaskPlacesDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t taskPlacesDo) Limit(limit int) ITaskPlacesDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t taskPlacesDo) Offset(offset int) ITaskPlacesDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t taskPlacesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITaskPlacesDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t taskPlacesDo) Unscoped() ITaskPlacesDo {
	return t.withDO(t.DO.Unscoped())
}

func (t taskPlacesDo) Create(values ...*model.TaskPlaces) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t taskPlacesDo) CreateInBatches(values []*model.TaskPlaces, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t taskPlacesDo) Save(values ...*model.TaskPlaces) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t taskPlacesDo) First() (*model.TaskPlaces, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskPlaces), nil
	}
}

func (t taskPlacesDo) Take() (*model.TaskPlaces, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskPlaces), nil
	}
}

func (t taskPlacesDo) Last() (*model.TaskPlaces, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskPlaces), nil
	}
}

func (t taskPlacesDo) Find() ([]*model.TaskPlaces, error) {
	result, err := t.DO.Find()
	return result.([]*model.TaskPlaces), err
}

func (t taskPlacesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TaskPlaces, err error) {
	buf := make([]*model.TaskPlaces, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t taskPlacesDo) FindInBatches(result *[]*model.TaskPlaces, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t taskPlacesDo) Attrs(attrs ...field.AssignExpr) ITaskPlacesDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t taskPlacesDo) Assign(attrs ...field.AssignExpr) ITaskPlacesDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t taskPlacesDo) Joins(fields ...field.RelationField) ITaskPlacesDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t taskPlacesDo) Preload(fields ...field.RelationField) ITaskPlacesDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t taskPlacesDo) FirstOrInit() (*model.TaskPlaces, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskPlaces), nil
	}
}

func (t taskPlacesDo) FirstOrCreate() (*model.TaskPlaces, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TaskPlaces), nil
	}
}

func (t taskPlacesDo) FindByPage(offset int, limit int) (result []*model.TaskPlaces, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t taskPlacesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t taskPlacesDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t taskPlacesDo) Delete(models ...*model.TaskPlaces) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *taskPlacesDo) withDO(do gen.Dao) *taskPlacesDo {
	t.DO = *do.(*gen.DO)
	return t
}
