// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/pgsql/model"
)

func newTasks(db *gorm.DB, opts ...gen.DOOption) tasks {
	_tasks := tasks{}

	_tasks.tasksDo.UseDB(db, opts...)
	_tasks.tasksDo.UseModel(&model.Tasks{})

	tableName := _tasks.tasksDo.TableName()
	_tasks.ALL = field.NewAsterisk(tableName)
	_tasks.ID = field.NewInt(tableName, "id")
	_tasks.ParentID = field.NewInt(tableName, "parent_id")
	_tasks.DepartmentID = field.NewInt(tableName, "department_id")
	_tasks.PlaceListID = field.NewInt(tableName, "place_list_id")
	_tasks.Name = field.NewString(tableName, "name")
	_tasks.StartTime = field.NewTime(tableName, "start_time")
	_tasks.DoneTime = field.NewTime(tableName, "done_time")
	_tasks.HasVideo = field.NewBool(tableName, "has_video")
	_tasks.HasImage = field.NewBool(tableName, "has_image")
	_tasks.CreatedAt = field.NewTime(tableName, "created_at")
	_tasks.UpdatedAt = field.NewTime(tableName, "updated_at")
	_tasks.DeletedAt = field.NewTime(tableName, "deleted_at")

	_tasks.fillFieldMap()

	return _tasks
}

type tasks struct {
	tasksDo

	ALL          field.Asterisk
	ID           field.Int    // 主键
	ParentID     field.Int    // 上级ID
	DepartmentID field.Int    // 所属部门ID
	PlaceListID  field.Int    // 场所清单id
	Name         field.String // 任务名称
	StartTime    field.Time   // 开始时间
	DoneTime     field.Time   // 完成时间
	HasVideo     field.Bool   // 是否上传视频
	HasImage     field.Bool   // 是否上传图片
	CreatedAt    field.Time   // 创建时间
	UpdatedAt    field.Time   // 修改时间
	DeletedAt    field.Time   // 删除时间

	fieldMap map[string]field.Expr
}

func (t tasks) Table(newTableName string) *tasks {
	t.tasksDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t tasks) As(alias string) *tasks {
	t.tasksDo.DO = *(t.tasksDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *tasks) updateTableName(table string) *tasks {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt(table, "id")
	t.ParentID = field.NewInt(table, "parent_id")
	t.DepartmentID = field.NewInt(table, "department_id")
	t.PlaceListID = field.NewInt(table, "place_list_id")
	t.Name = field.NewString(table, "name")
	t.StartTime = field.NewTime(table, "start_time")
	t.DoneTime = field.NewTime(table, "done_time")
	t.HasVideo = field.NewBool(table, "has_video")
	t.HasImage = field.NewBool(table, "has_image")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewTime(table, "deleted_at")

	t.fillFieldMap()

	return t
}

func (t *tasks) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *tasks) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 12)
	t.fieldMap["id"] = t.ID
	t.fieldMap["parent_id"] = t.ParentID
	t.fieldMap["department_id"] = t.DepartmentID
	t.fieldMap["place_list_id"] = t.PlaceListID
	t.fieldMap["name"] = t.Name
	t.fieldMap["start_time"] = t.StartTime
	t.fieldMap["done_time"] = t.DoneTime
	t.fieldMap["has_video"] = t.HasVideo
	t.fieldMap["has_image"] = t.HasImage
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
}

func (t tasks) clone(db *gorm.DB) tasks {
	t.tasksDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t tasks) replaceDB(db *gorm.DB) tasks {
	t.tasksDo.ReplaceDB(db)
	return t
}

type tasksDo struct{ gen.DO }

type ITasksDo interface {
	gen.SubQuery
	Debug() ITasksDo
	WithContext(ctx context.Context) ITasksDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ITasksDo
	WriteDB() ITasksDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ITasksDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ITasksDo
	Not(conds ...gen.Condition) ITasksDo
	Or(conds ...gen.Condition) ITasksDo
	Select(conds ...field.Expr) ITasksDo
	Where(conds ...gen.Condition) ITasksDo
	Order(conds ...field.Expr) ITasksDo
	Distinct(cols ...field.Expr) ITasksDo
	Omit(cols ...field.Expr) ITasksDo
	Join(table schema.Tabler, on ...field.Expr) ITasksDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ITasksDo
	RightJoin(table schema.Tabler, on ...field.Expr) ITasksDo
	Group(cols ...field.Expr) ITasksDo
	Having(conds ...gen.Condition) ITasksDo
	Limit(limit int) ITasksDo
	Offset(offset int) ITasksDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ITasksDo
	Unscoped() ITasksDo
	Create(values ...*model.Tasks) error
	CreateInBatches(values []*model.Tasks, batchSize int) error
	Save(values ...*model.Tasks) error
	First() (*model.Tasks, error)
	Take() (*model.Tasks, error)
	Last() (*model.Tasks, error)
	Find() ([]*model.Tasks, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Tasks, err error)
	FindInBatches(result *[]*model.Tasks, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Tasks) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ITasksDo
	Assign(attrs ...field.AssignExpr) ITasksDo
	Joins(fields ...field.RelationField) ITasksDo
	Preload(fields ...field.RelationField) ITasksDo
	FirstOrInit() (*model.Tasks, error)
	FirstOrCreate() (*model.Tasks, error)
	FindByPage(offset int, limit int) (result []*model.Tasks, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ITasksDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (t tasksDo) Debug() ITasksDo {
	return t.withDO(t.DO.Debug())
}

func (t tasksDo) WithContext(ctx context.Context) ITasksDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t tasksDo) ReadDB() ITasksDo {
	return t.Clauses(dbresolver.Read)
}

func (t tasksDo) WriteDB() ITasksDo {
	return t.Clauses(dbresolver.Write)
}

func (t tasksDo) Session(config *gorm.Session) ITasksDo {
	return t.withDO(t.DO.Session(config))
}

func (t tasksDo) Clauses(conds ...clause.Expression) ITasksDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t tasksDo) Returning(value interface{}, columns ...string) ITasksDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t tasksDo) Not(conds ...gen.Condition) ITasksDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t tasksDo) Or(conds ...gen.Condition) ITasksDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t tasksDo) Select(conds ...field.Expr) ITasksDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t tasksDo) Where(conds ...gen.Condition) ITasksDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t tasksDo) Order(conds ...field.Expr) ITasksDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t tasksDo) Distinct(cols ...field.Expr) ITasksDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t tasksDo) Omit(cols ...field.Expr) ITasksDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t tasksDo) Join(table schema.Tabler, on ...field.Expr) ITasksDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t tasksDo) LeftJoin(table schema.Tabler, on ...field.Expr) ITasksDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t tasksDo) RightJoin(table schema.Tabler, on ...field.Expr) ITasksDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t tasksDo) Group(cols ...field.Expr) ITasksDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t tasksDo) Having(conds ...gen.Condition) ITasksDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t tasksDo) Limit(limit int) ITasksDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t tasksDo) Offset(offset int) ITasksDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t tasksDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ITasksDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t tasksDo) Unscoped() ITasksDo {
	return t.withDO(t.DO.Unscoped())
}

func (t tasksDo) Create(values ...*model.Tasks) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t tasksDo) CreateInBatches(values []*model.Tasks, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t tasksDo) Save(values ...*model.Tasks) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t tasksDo) First() (*model.Tasks, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tasks), nil
	}
}

func (t tasksDo) Take() (*model.Tasks, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tasks), nil
	}
}

func (t tasksDo) Last() (*model.Tasks, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tasks), nil
	}
}

func (t tasksDo) Find() ([]*model.Tasks, error) {
	result, err := t.DO.Find()
	return result.([]*model.Tasks), err
}

func (t tasksDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Tasks, err error) {
	buf := make([]*model.Tasks, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t tasksDo) FindInBatches(result *[]*model.Tasks, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t tasksDo) Attrs(attrs ...field.AssignExpr) ITasksDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t tasksDo) Assign(attrs ...field.AssignExpr) ITasksDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t tasksDo) Joins(fields ...field.RelationField) ITasksDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t tasksDo) Preload(fields ...field.RelationField) ITasksDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t tasksDo) FirstOrInit() (*model.Tasks, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tasks), nil
	}
}

func (t tasksDo) FirstOrCreate() (*model.Tasks, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Tasks), nil
	}
}

func (t tasksDo) FindByPage(offset int, limit int) (result []*model.Tasks, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t tasksDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t tasksDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t tasksDo) Delete(models ...*model.Tasks) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *tasksDo) withDO(do gen.Dao) *tasksDo {
	t.DO = *do.(*gen.DO)
	return t
}
