// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                 = new(Query)
	SafeCompany       *safeCompany
	SafeDictionary    *safeDictionary
	SafeDisposal      *safeDisposal
	SafeEventLogs     *safeEventLogs
	SafeFiling        *safeFiling
	SafeIPAddress     *safeIPAddress
	SafeIPEvent       *safeIPEvent
	SafeIPLevel       *safeIPLevel
	SafeIpaddress     *safeIpaddress
	SafePlatform      *safePlatform
	SafeTaskPlan      *safeTaskPlan
	SafeTaskPlanUts   *safeTaskPlanUts
	SafeTodayAlarm    *safeTodayAlarm
	SafeTodayThreat   *safeTodayThreat
	SafeUts           *safeUts
	SafeUtsAPI        *safeUtsAPI
	SafeUtsDdos       *safeUtsDdos
	SafeUtsDictionary *safeUtsDictionary
	SafeUtsInfo       *safeUtsInfo
	SafeUtsStatus     *safeUtsStatus
	SafeUtsTrafficLog *safeUtsTrafficLog
	SysActionLog      *sysActionLog
	SysAdmin          *sysAdmin
	SysAdminProfile   *sysAdminProfile
	SysAlbum          *sysAlbum
	SysAlbumCategory  *sysAlbumCategory
	SysConfig         *sysConfig
	SysConfigValue    *sysConfigValue
	SysDictionaries   *sysDictionaries
	SysDictionary     *sysDictionary
	SysRegion         *sysRegion
	SysRole           *sysRole
	SysRule           *sysRule
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	SafeCompany = &Q.SafeCompany
	SafeDictionary = &Q.SafeDictionary
	SafeDisposal = &Q.SafeDisposal
	SafeEventLogs = &Q.SafeEventLogs
	SafeFiling = &Q.SafeFiling
	SafeIPAddress = &Q.SafeIPAddress
	SafeIPEvent = &Q.SafeIPEvent
	SafeIPLevel = &Q.SafeIPLevel
	SafeIpaddress = &Q.SafeIpaddress
	SafePlatform = &Q.SafePlatform
	SafeTaskPlan = &Q.SafeTaskPlan
	SafeTaskPlanUts = &Q.SafeTaskPlanUts
	SafeTodayAlarm = &Q.SafeTodayAlarm
	SafeTodayThreat = &Q.SafeTodayThreat
	SafeUts = &Q.SafeUts
	SafeUtsAPI = &Q.SafeUtsAPI
	SafeUtsDdos = &Q.SafeUtsDdos
	SafeUtsDictionary = &Q.SafeUtsDictionary
	SafeUtsInfo = &Q.SafeUtsInfo
	SafeUtsStatus = &Q.SafeUtsStatus
	SafeUtsTrafficLog = &Q.SafeUtsTrafficLog
	SysActionLog = &Q.SysActionLog
	SysAdmin = &Q.SysAdmin
	SysAdminProfile = &Q.SysAdminProfile
	SysAlbum = &Q.SysAlbum
	SysAlbumCategory = &Q.SysAlbumCategory
	SysConfig = &Q.SysConfig
	SysConfigValue = &Q.SysConfigValue
	SysDictionaries = &Q.SysDictionaries
	SysDictionary = &Q.SysDictionary
	SysRegion = &Q.SysRegion
	SysRole = &Q.SysRole
	SysRule = &Q.SysRule
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                db,
		SafeCompany:       newSafeCompany(db, opts...),
		SafeDictionary:    newSafeDictionary(db, opts...),
		SafeDisposal:      newSafeDisposal(db, opts...),
		SafeEventLogs:     newSafeEventLogs(db, opts...),
		SafeFiling:        newSafeFiling(db, opts...),
		SafeIPAddress:     newSafeIPAddress(db, opts...),
		SafeIPEvent:       newSafeIPEvent(db, opts...),
		SafeIPLevel:       newSafeIPLevel(db, opts...),
		SafeIpaddress:     newSafeIpaddress(db, opts...),
		SafePlatform:      newSafePlatform(db, opts...),
		SafeTaskPlan:      newSafeTaskPlan(db, opts...),
		SafeTaskPlanUts:   newSafeTaskPlanUts(db, opts...),
		SafeTodayAlarm:    newSafeTodayAlarm(db, opts...),
		SafeTodayThreat:   newSafeTodayThreat(db, opts...),
		SafeUts:           newSafeUts(db, opts...),
		SafeUtsAPI:        newSafeUtsAPI(db, opts...),
		SafeUtsDdos:       newSafeUtsDdos(db, opts...),
		SafeUtsDictionary: newSafeUtsDictionary(db, opts...),
		SafeUtsInfo:       newSafeUtsInfo(db, opts...),
		SafeUtsStatus:     newSafeUtsStatus(db, opts...),
		SafeUtsTrafficLog: newSafeUtsTrafficLog(db, opts...),
		SysActionLog:      newSysActionLog(db, opts...),
		SysAdmin:          newSysAdmin(db, opts...),
		SysAdminProfile:   newSysAdminProfile(db, opts...),
		SysAlbum:          newSysAlbum(db, opts...),
		SysAlbumCategory:  newSysAlbumCategory(db, opts...),
		SysConfig:         newSysConfig(db, opts...),
		SysConfigValue:    newSysConfigValue(db, opts...),
		SysDictionaries:   newSysDictionaries(db, opts...),
		SysDictionary:     newSysDictionary(db, opts...),
		SysRegion:         newSysRegion(db, opts...),
		SysRole:           newSysRole(db, opts...),
		SysRule:           newSysRule(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	SafeCompany       safeCompany
	SafeDictionary    safeDictionary
	SafeDisposal      safeDisposal
	SafeEventLogs     safeEventLogs
	SafeFiling        safeFiling
	SafeIPAddress     safeIPAddress
	SafeIPEvent       safeIPEvent
	SafeIPLevel       safeIPLevel
	SafeIpaddress     safeIpaddress
	SafePlatform      safePlatform
	SafeTaskPlan      safeTaskPlan
	SafeTaskPlanUts   safeTaskPlanUts
	SafeTodayAlarm    safeTodayAlarm
	SafeTodayThreat   safeTodayThreat
	SafeUts           safeUts
	SafeUtsAPI        safeUtsAPI
	SafeUtsDdos       safeUtsDdos
	SafeUtsDictionary safeUtsDictionary
	SafeUtsInfo       safeUtsInfo
	SafeUtsStatus     safeUtsStatus
	SafeUtsTrafficLog safeUtsTrafficLog
	SysActionLog      sysActionLog
	SysAdmin          sysAdmin
	SysAdminProfile   sysAdminProfile
	SysAlbum          sysAlbum
	SysAlbumCategory  sysAlbumCategory
	SysConfig         sysConfig
	SysConfigValue    sysConfigValue
	SysDictionaries   sysDictionaries
	SysDictionary     sysDictionary
	SysRegion         sysRegion
	SysRole           sysRole
	SysRule           sysRule
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		SafeCompany:       q.SafeCompany.clone(db),
		SafeDictionary:    q.SafeDictionary.clone(db),
		SafeDisposal:      q.SafeDisposal.clone(db),
		SafeEventLogs:     q.SafeEventLogs.clone(db),
		SafeFiling:        q.SafeFiling.clone(db),
		SafeIPAddress:     q.SafeIPAddress.clone(db),
		SafeIPEvent:       q.SafeIPEvent.clone(db),
		SafeIPLevel:       q.SafeIPLevel.clone(db),
		SafeIpaddress:     q.SafeIpaddress.clone(db),
		SafePlatform:      q.SafePlatform.clone(db),
		SafeTaskPlan:      q.SafeTaskPlan.clone(db),
		SafeTaskPlanUts:   q.SafeTaskPlanUts.clone(db),
		SafeTodayAlarm:    q.SafeTodayAlarm.clone(db),
		SafeTodayThreat:   q.SafeTodayThreat.clone(db),
		SafeUts:           q.SafeUts.clone(db),
		SafeUtsAPI:        q.SafeUtsAPI.clone(db),
		SafeUtsDdos:       q.SafeUtsDdos.clone(db),
		SafeUtsDictionary: q.SafeUtsDictionary.clone(db),
		SafeUtsInfo:       q.SafeUtsInfo.clone(db),
		SafeUtsStatus:     q.SafeUtsStatus.clone(db),
		SafeUtsTrafficLog: q.SafeUtsTrafficLog.clone(db),
		SysActionLog:      q.SysActionLog.clone(db),
		SysAdmin:          q.SysAdmin.clone(db),
		SysAdminProfile:   q.SysAdminProfile.clone(db),
		SysAlbum:          q.SysAlbum.clone(db),
		SysAlbumCategory:  q.SysAlbumCategory.clone(db),
		SysConfig:         q.SysConfig.clone(db),
		SysConfigValue:    q.SysConfigValue.clone(db),
		SysDictionaries:   q.SysDictionaries.clone(db),
		SysDictionary:     q.SysDictionary.clone(db),
		SysRegion:         q.SysRegion.clone(db),
		SysRole:           q.SysRole.clone(db),
		SysRule:           q.SysRule.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                db,
		SafeCompany:       q.SafeCompany.replaceDB(db),
		SafeDictionary:    q.SafeDictionary.replaceDB(db),
		SafeDisposal:      q.SafeDisposal.replaceDB(db),
		SafeEventLogs:     q.SafeEventLogs.replaceDB(db),
		SafeFiling:        q.SafeFiling.replaceDB(db),
		SafeIPAddress:     q.SafeIPAddress.replaceDB(db),
		SafeIPEvent:       q.SafeIPEvent.replaceDB(db),
		SafeIPLevel:       q.SafeIPLevel.replaceDB(db),
		SafeIpaddress:     q.SafeIpaddress.replaceDB(db),
		SafePlatform:      q.SafePlatform.replaceDB(db),
		SafeTaskPlan:      q.SafeTaskPlan.replaceDB(db),
		SafeTaskPlanUts:   q.SafeTaskPlanUts.replaceDB(db),
		SafeTodayAlarm:    q.SafeTodayAlarm.replaceDB(db),
		SafeTodayThreat:   q.SafeTodayThreat.replaceDB(db),
		SafeUts:           q.SafeUts.replaceDB(db),
		SafeUtsAPI:        q.SafeUtsAPI.replaceDB(db),
		SafeUtsDdos:       q.SafeUtsDdos.replaceDB(db),
		SafeUtsDictionary: q.SafeUtsDictionary.replaceDB(db),
		SafeUtsInfo:       q.SafeUtsInfo.replaceDB(db),
		SafeUtsStatus:     q.SafeUtsStatus.replaceDB(db),
		SafeUtsTrafficLog: q.SafeUtsTrafficLog.replaceDB(db),
		SysActionLog:      q.SysActionLog.replaceDB(db),
		SysAdmin:          q.SysAdmin.replaceDB(db),
		SysAdminProfile:   q.SysAdminProfile.replaceDB(db),
		SysAlbum:          q.SysAlbum.replaceDB(db),
		SysAlbumCategory:  q.SysAlbumCategory.replaceDB(db),
		SysConfig:         q.SysConfig.replaceDB(db),
		SysConfigValue:    q.SysConfigValue.replaceDB(db),
		SysDictionaries:   q.SysDictionaries.replaceDB(db),
		SysDictionary:     q.SysDictionary.replaceDB(db),
		SysRegion:         q.SysRegion.replaceDB(db),
		SysRole:           q.SysRole.replaceDB(db),
		SysRule:           q.SysRule.replaceDB(db),
	}
}

type queryCtx struct {
	SafeCompany       ISafeCompanyDo
	SafeDictionary    ISafeDictionaryDo
	SafeDisposal      ISafeDisposalDo
	SafeEventLogs     ISafeEventLogsDo
	SafeFiling        ISafeFilingDo
	SafeIPAddress     ISafeIPAddressDo
	SafeIPEvent       ISafeIPEventDo
	SafeIPLevel       ISafeIPLevelDo
	SafeIpaddress     ISafeIpaddressDo
	SafePlatform      ISafePlatformDo
	SafeTaskPlan      ISafeTaskPlanDo
	SafeTaskPlanUts   ISafeTaskPlanUtsDo
	SafeTodayAlarm    ISafeTodayAlarmDo
	SafeTodayThreat   ISafeTodayThreatDo
	SafeUts           ISafeUtsDo
	SafeUtsAPI        ISafeUtsAPIDo
	SafeUtsDdos       ISafeUtsDdosDo
	SafeUtsDictionary ISafeUtsDictionaryDo
	SafeUtsInfo       ISafeUtsInfoDo
	SafeUtsStatus     ISafeUtsStatusDo
	SafeUtsTrafficLog ISafeUtsTrafficLogDo
	SysActionLog      ISysActionLogDo
	SysAdmin          ISysAdminDo
	SysAdminProfile   ISysAdminProfileDo
	SysAlbum          ISysAlbumDo
	SysAlbumCategory  ISysAlbumCategoryDo
	SysConfig         ISysConfigDo
	SysConfigValue    ISysConfigValueDo
	SysDictionaries   ISysDictionariesDo
	SysDictionary     ISysDictionaryDo
	SysRegion         ISysRegionDo
	SysRole           ISysRoleDo
	SysRule           ISysRuleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		SafeCompany:       q.SafeCompany.WithContext(ctx),
		SafeDictionary:    q.SafeDictionary.WithContext(ctx),
		SafeDisposal:      q.SafeDisposal.WithContext(ctx),
		SafeEventLogs:     q.SafeEventLogs.WithContext(ctx),
		SafeFiling:        q.SafeFiling.WithContext(ctx),
		SafeIPAddress:     q.SafeIPAddress.WithContext(ctx),
		SafeIPEvent:       q.SafeIPEvent.WithContext(ctx),
		SafeIPLevel:       q.SafeIPLevel.WithContext(ctx),
		SafeIpaddress:     q.SafeIpaddress.WithContext(ctx),
		SafePlatform:      q.SafePlatform.WithContext(ctx),
		SafeTaskPlan:      q.SafeTaskPlan.WithContext(ctx),
		SafeTaskPlanUts:   q.SafeTaskPlanUts.WithContext(ctx),
		SafeTodayAlarm:    q.SafeTodayAlarm.WithContext(ctx),
		SafeTodayThreat:   q.SafeTodayThreat.WithContext(ctx),
		SafeUts:           q.SafeUts.WithContext(ctx),
		SafeUtsAPI:        q.SafeUtsAPI.WithContext(ctx),
		SafeUtsDdos:       q.SafeUtsDdos.WithContext(ctx),
		SafeUtsDictionary: q.SafeUtsDictionary.WithContext(ctx),
		SafeUtsInfo:       q.SafeUtsInfo.WithContext(ctx),
		SafeUtsStatus:     q.SafeUtsStatus.WithContext(ctx),
		SafeUtsTrafficLog: q.SafeUtsTrafficLog.WithContext(ctx),
		SysActionLog:      q.SysActionLog.WithContext(ctx),
		SysAdmin:          q.SysAdmin.WithContext(ctx),
		SysAdminProfile:   q.SysAdminProfile.WithContext(ctx),
		SysAlbum:          q.SysAlbum.WithContext(ctx),
		SysAlbumCategory:  q.SysAlbumCategory.WithContext(ctx),
		SysConfig:         q.SysConfig.WithContext(ctx),
		SysConfigValue:    q.SysConfigValue.WithContext(ctx),
		SysDictionaries:   q.SysDictionaries.WithContext(ctx),
		SysDictionary:     q.SysDictionary.WithContext(ctx),
		SysRegion:         q.SysRegion.WithContext(ctx),
		SysRole:           q.SysRole.WithContext(ctx),
		SysRule:           q.SysRule.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
