// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSafeEventLogs(db *gorm.DB, opts ...gen.DOOption) safeEventLogs {
	_safeEventLogs := safeEventLogs{}

	_safeEventLogs.safeEventLogsDo.UseDB(db, opts...)
	_safeEventLogs.safeEventLogsDo.UseModel(&model.SafeEventLogs{})

	tableName := _safeEventLogs.safeEventLogsDo.TableName()
	_safeEventLogs.ALL = field.NewAsterisk(tableName)
	_safeEventLogs.ID = field.NewInt64(tableName, "id")
	_safeEventLogs.Date = field.NewTime(tableName, "date")
	_safeEventLogs.EventType = field.NewString(tableName, "event_type")
	_safeEventLogs.PlatformID = field.NewInt64(tableName, "platform_id")
	_safeEventLogs.Total = field.NewInt32(tableName, "total")
	_safeEventLogs.Successed = field.NewInt32(tableName, "successed")
	_safeEventLogs.Failed = field.NewInt32(tableName, "failed")
	_safeEventLogs.CreatedAt = field.NewTime(tableName, "created_at")
	_safeEventLogs.UpdatedAt = field.NewField(tableName, "updated_at")
	_safeEventLogs.DeletedAt = field.NewField(tableName, "deleted_at")

	_safeEventLogs.fillFieldMap()

	return _safeEventLogs
}

type safeEventLogs struct {
	safeEventLogsDo

	ALL        field.Asterisk
	ID         field.Int64  // 主键
	Date       field.Time   // 日期
	EventType  field.String // 所属事件
	PlatformID field.Int64  // 来源平台ID
	Total      field.Int32  // 总计数量
	Successed  field.Int32  // 成功数量
	Failed     field.Int32  // 失败数量
	CreatedAt  field.Time   // 创建时间
	UpdatedAt  field.Field  // 修改时间
	DeletedAt  field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s safeEventLogs) Table(newTableName string) *safeEventLogs {
	s.safeEventLogsDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s safeEventLogs) As(alias string) *safeEventLogs {
	s.safeEventLogsDo.DO = *(s.safeEventLogsDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *safeEventLogs) updateTableName(table string) *safeEventLogs {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Date = field.NewTime(table, "date")
	s.EventType = field.NewString(table, "event_type")
	s.PlatformID = field.NewInt64(table, "platform_id")
	s.Total = field.NewInt32(table, "total")
	s.Successed = field.NewInt32(table, "successed")
	s.Failed = field.NewInt32(table, "failed")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewField(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *safeEventLogs) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *safeEventLogs) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 10)
	s.fieldMap["id"] = s.ID
	s.fieldMap["date"] = s.Date
	s.fieldMap["event_type"] = s.EventType
	s.fieldMap["platform_id"] = s.PlatformID
	s.fieldMap["total"] = s.Total
	s.fieldMap["successed"] = s.Successed
	s.fieldMap["failed"] = s.Failed
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s safeEventLogs) clone(db *gorm.DB) safeEventLogs {
	s.safeEventLogsDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s safeEventLogs) replaceDB(db *gorm.DB) safeEventLogs {
	s.safeEventLogsDo.ReplaceDB(db)
	return s
}

type safeEventLogsDo struct{ gen.DO }

type ISafeEventLogsDo interface {
	gen.SubQuery
	Debug() ISafeEventLogsDo
	WithContext(ctx context.Context) ISafeEventLogsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISafeEventLogsDo
	WriteDB() ISafeEventLogsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISafeEventLogsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISafeEventLogsDo
	Not(conds ...gen.Condition) ISafeEventLogsDo
	Or(conds ...gen.Condition) ISafeEventLogsDo
	Select(conds ...field.Expr) ISafeEventLogsDo
	Where(conds ...gen.Condition) ISafeEventLogsDo
	Order(conds ...field.Expr) ISafeEventLogsDo
	Distinct(cols ...field.Expr) ISafeEventLogsDo
	Omit(cols ...field.Expr) ISafeEventLogsDo
	Join(table schema.Tabler, on ...field.Expr) ISafeEventLogsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISafeEventLogsDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISafeEventLogsDo
	Group(cols ...field.Expr) ISafeEventLogsDo
	Having(conds ...gen.Condition) ISafeEventLogsDo
	Limit(limit int) ISafeEventLogsDo
	Offset(offset int) ISafeEventLogsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeEventLogsDo
	Unscoped() ISafeEventLogsDo
	Create(values ...*model.SafeEventLogs) error
	CreateInBatches(values []*model.SafeEventLogs, batchSize int) error
	Save(values ...*model.SafeEventLogs) error
	First() (*model.SafeEventLogs, error)
	Take() (*model.SafeEventLogs, error)
	Last() (*model.SafeEventLogs, error)
	Find() ([]*model.SafeEventLogs, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeEventLogs, err error)
	FindInBatches(result *[]*model.SafeEventLogs, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SafeEventLogs) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISafeEventLogsDo
	Assign(attrs ...field.AssignExpr) ISafeEventLogsDo
	Joins(fields ...field.RelationField) ISafeEventLogsDo
	Preload(fields ...field.RelationField) ISafeEventLogsDo
	FirstOrInit() (*model.SafeEventLogs, error)
	FirstOrCreate() (*model.SafeEventLogs, error)
	FindByPage(offset int, limit int) (result []*model.SafeEventLogs, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISafeEventLogsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s safeEventLogsDo) Debug() ISafeEventLogsDo {
	return s.withDO(s.DO.Debug())
}

func (s safeEventLogsDo) WithContext(ctx context.Context) ISafeEventLogsDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s safeEventLogsDo) ReadDB() ISafeEventLogsDo {
	return s.Clauses(dbresolver.Read)
}

func (s safeEventLogsDo) WriteDB() ISafeEventLogsDo {
	return s.Clauses(dbresolver.Write)
}

func (s safeEventLogsDo) Session(config *gorm.Session) ISafeEventLogsDo {
	return s.withDO(s.DO.Session(config))
}

func (s safeEventLogsDo) Clauses(conds ...clause.Expression) ISafeEventLogsDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s safeEventLogsDo) Returning(value interface{}, columns ...string) ISafeEventLogsDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s safeEventLogsDo) Not(conds ...gen.Condition) ISafeEventLogsDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s safeEventLogsDo) Or(conds ...gen.Condition) ISafeEventLogsDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s safeEventLogsDo) Select(conds ...field.Expr) ISafeEventLogsDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s safeEventLogsDo) Where(conds ...gen.Condition) ISafeEventLogsDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s safeEventLogsDo) Order(conds ...field.Expr) ISafeEventLogsDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s safeEventLogsDo) Distinct(cols ...field.Expr) ISafeEventLogsDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s safeEventLogsDo) Omit(cols ...field.Expr) ISafeEventLogsDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s safeEventLogsDo) Join(table schema.Tabler, on ...field.Expr) ISafeEventLogsDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s safeEventLogsDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISafeEventLogsDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s safeEventLogsDo) RightJoin(table schema.Tabler, on ...field.Expr) ISafeEventLogsDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s safeEventLogsDo) Group(cols ...field.Expr) ISafeEventLogsDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s safeEventLogsDo) Having(conds ...gen.Condition) ISafeEventLogsDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s safeEventLogsDo) Limit(limit int) ISafeEventLogsDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s safeEventLogsDo) Offset(offset int) ISafeEventLogsDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s safeEventLogsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeEventLogsDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s safeEventLogsDo) Unscoped() ISafeEventLogsDo {
	return s.withDO(s.DO.Unscoped())
}

func (s safeEventLogsDo) Create(values ...*model.SafeEventLogs) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s safeEventLogsDo) CreateInBatches(values []*model.SafeEventLogs, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s safeEventLogsDo) Save(values ...*model.SafeEventLogs) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s safeEventLogsDo) First() (*model.SafeEventLogs, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeEventLogs), nil
	}
}

func (s safeEventLogsDo) Take() (*model.SafeEventLogs, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeEventLogs), nil
	}
}

func (s safeEventLogsDo) Last() (*model.SafeEventLogs, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeEventLogs), nil
	}
}

func (s safeEventLogsDo) Find() ([]*model.SafeEventLogs, error) {
	result, err := s.DO.Find()
	return result.([]*model.SafeEventLogs), err
}

func (s safeEventLogsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeEventLogs, err error) {
	buf := make([]*model.SafeEventLogs, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s safeEventLogsDo) FindInBatches(result *[]*model.SafeEventLogs, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s safeEventLogsDo) Attrs(attrs ...field.AssignExpr) ISafeEventLogsDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s safeEventLogsDo) Assign(attrs ...field.AssignExpr) ISafeEventLogsDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s safeEventLogsDo) Joins(fields ...field.RelationField) ISafeEventLogsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s safeEventLogsDo) Preload(fields ...field.RelationField) ISafeEventLogsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s safeEventLogsDo) FirstOrInit() (*model.SafeEventLogs, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeEventLogs), nil
	}
}

func (s safeEventLogsDo) FirstOrCreate() (*model.SafeEventLogs, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeEventLogs), nil
	}
}

func (s safeEventLogsDo) FindByPage(offset int, limit int) (result []*model.SafeEventLogs, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s safeEventLogsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s safeEventLogsDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s safeEventLogsDo) Delete(models ...*model.SafeEventLogs) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *safeEventLogsDo) withDO(do gen.Dao) *safeEventLogsDo {
	s.DO = *do.(*gen.DO)
	return s
}
