// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSafeUts(db *gorm.DB, opts ...gen.DOOption) safeUts {
	_safeUts := safeUts{}

	_safeUts.safeUtsDo.UseDB(db, opts...)
	_safeUts.safeUtsDo.UseModel(&model.SafeUts{})

	tableName := _safeUts.safeUtsDo.TableName()
	_safeUts.ALL = field.NewAsterisk(tableName)
	_safeUts.ID = field.NewInt32(tableName, "id")
	_safeUts.PlatformID = field.NewInt16(tableName, "platform_id")
	_safeUts.Title = field.NewString(tableName, "title")
	_safeUts.Address = field.NewString(tableName, "address")
	_safeUts.DeviceID = field.NewString(tableName, "device_id")
	_safeUts.KafkaTopic = field.NewString(tableName, "kafka_topic")
	_safeUts.ElasticIndex = field.NewString(tableName, "elastic_index")
	_safeUts.ElasticDetailIndex = field.NewString(tableName, "elastic_detail_index")
	_safeUts.Sort = field.NewInt32(tableName, "sort")
	_safeUts.Disabled = field.NewInt8(tableName, "disabled")
	_safeUts.CreatedAt = field.NewTime(tableName, "created_at")
	_safeUts.UpdatedAt = field.NewField(tableName, "updated_at")
	_safeUts.DeletedAt = field.NewField(tableName, "deleted_at")

	_safeUts.fillFieldMap()

	return _safeUts
}

type safeUts struct {
	safeUtsDo

	ALL                field.Asterisk
	ID                 field.Int32  // 主键
	PlatformID         field.Int16  // 来源平台
	Title              field.String // 探针设备标题
	Address            field.String // IP地址
	DeviceID           field.String // 探针设备ID
	KafkaTopic         field.String // kafka主题
	ElasticIndex       field.String // es索引
	ElasticDetailIndex field.String // 对应详情索引
	Sort               field.Int32  // 探针设备排序
	Disabled           field.Int8   // 禁用状态
	CreatedAt          field.Time   // 创建时间
	UpdatedAt          field.Field  // 修改时间
	DeletedAt          field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s safeUts) Table(newTableName string) *safeUts {
	s.safeUtsDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s safeUts) As(alias string) *safeUts {
	s.safeUtsDo.DO = *(s.safeUtsDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *safeUts) updateTableName(table string) *safeUts {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt32(table, "id")
	s.PlatformID = field.NewInt16(table, "platform_id")
	s.Title = field.NewString(table, "title")
	s.Address = field.NewString(table, "address")
	s.DeviceID = field.NewString(table, "device_id")
	s.KafkaTopic = field.NewString(table, "kafka_topic")
	s.ElasticIndex = field.NewString(table, "elastic_index")
	s.ElasticDetailIndex = field.NewString(table, "elastic_detail_index")
	s.Sort = field.NewInt32(table, "sort")
	s.Disabled = field.NewInt8(table, "disabled")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewField(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *safeUts) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *safeUts) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 13)
	s.fieldMap["id"] = s.ID
	s.fieldMap["platform_id"] = s.PlatformID
	s.fieldMap["title"] = s.Title
	s.fieldMap["address"] = s.Address
	s.fieldMap["device_id"] = s.DeviceID
	s.fieldMap["kafka_topic"] = s.KafkaTopic
	s.fieldMap["elastic_index"] = s.ElasticIndex
	s.fieldMap["elastic_detail_index"] = s.ElasticDetailIndex
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["disabled"] = s.Disabled
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s safeUts) clone(db *gorm.DB) safeUts {
	s.safeUtsDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s safeUts) replaceDB(db *gorm.DB) safeUts {
	s.safeUtsDo.ReplaceDB(db)
	return s
}

type safeUtsDo struct{ gen.DO }

type ISafeUtsDo interface {
	gen.SubQuery
	Debug() ISafeUtsDo
	WithContext(ctx context.Context) ISafeUtsDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISafeUtsDo
	WriteDB() ISafeUtsDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISafeUtsDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISafeUtsDo
	Not(conds ...gen.Condition) ISafeUtsDo
	Or(conds ...gen.Condition) ISafeUtsDo
	Select(conds ...field.Expr) ISafeUtsDo
	Where(conds ...gen.Condition) ISafeUtsDo
	Order(conds ...field.Expr) ISafeUtsDo
	Distinct(cols ...field.Expr) ISafeUtsDo
	Omit(cols ...field.Expr) ISafeUtsDo
	Join(table schema.Tabler, on ...field.Expr) ISafeUtsDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISafeUtsDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISafeUtsDo
	Group(cols ...field.Expr) ISafeUtsDo
	Having(conds ...gen.Condition) ISafeUtsDo
	Limit(limit int) ISafeUtsDo
	Offset(offset int) ISafeUtsDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeUtsDo
	Unscoped() ISafeUtsDo
	Create(values ...*model.SafeUts) error
	CreateInBatches(values []*model.SafeUts, batchSize int) error
	Save(values ...*model.SafeUts) error
	First() (*model.SafeUts, error)
	Take() (*model.SafeUts, error)
	Last() (*model.SafeUts, error)
	Find() ([]*model.SafeUts, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeUts, err error)
	FindInBatches(result *[]*model.SafeUts, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SafeUts) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISafeUtsDo
	Assign(attrs ...field.AssignExpr) ISafeUtsDo
	Joins(fields ...field.RelationField) ISafeUtsDo
	Preload(fields ...field.RelationField) ISafeUtsDo
	FirstOrInit() (*model.SafeUts, error)
	FirstOrCreate() (*model.SafeUts, error)
	FindByPage(offset int, limit int) (result []*model.SafeUts, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISafeUtsDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s safeUtsDo) Debug() ISafeUtsDo {
	return s.withDO(s.DO.Debug())
}

func (s safeUtsDo) WithContext(ctx context.Context) ISafeUtsDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s safeUtsDo) ReadDB() ISafeUtsDo {
	return s.Clauses(dbresolver.Read)
}

func (s safeUtsDo) WriteDB() ISafeUtsDo {
	return s.Clauses(dbresolver.Write)
}

func (s safeUtsDo) Session(config *gorm.Session) ISafeUtsDo {
	return s.withDO(s.DO.Session(config))
}

func (s safeUtsDo) Clauses(conds ...clause.Expression) ISafeUtsDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s safeUtsDo) Returning(value interface{}, columns ...string) ISafeUtsDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s safeUtsDo) Not(conds ...gen.Condition) ISafeUtsDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s safeUtsDo) Or(conds ...gen.Condition) ISafeUtsDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s safeUtsDo) Select(conds ...field.Expr) ISafeUtsDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s safeUtsDo) Where(conds ...gen.Condition) ISafeUtsDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s safeUtsDo) Order(conds ...field.Expr) ISafeUtsDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s safeUtsDo) Distinct(cols ...field.Expr) ISafeUtsDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s safeUtsDo) Omit(cols ...field.Expr) ISafeUtsDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s safeUtsDo) Join(table schema.Tabler, on ...field.Expr) ISafeUtsDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s safeUtsDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISafeUtsDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s safeUtsDo) RightJoin(table schema.Tabler, on ...field.Expr) ISafeUtsDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s safeUtsDo) Group(cols ...field.Expr) ISafeUtsDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s safeUtsDo) Having(conds ...gen.Condition) ISafeUtsDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s safeUtsDo) Limit(limit int) ISafeUtsDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s safeUtsDo) Offset(offset int) ISafeUtsDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s safeUtsDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeUtsDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s safeUtsDo) Unscoped() ISafeUtsDo {
	return s.withDO(s.DO.Unscoped())
}

func (s safeUtsDo) Create(values ...*model.SafeUts) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s safeUtsDo) CreateInBatches(values []*model.SafeUts, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s safeUtsDo) Save(values ...*model.SafeUts) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s safeUtsDo) First() (*model.SafeUts, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeUts), nil
	}
}

func (s safeUtsDo) Take() (*model.SafeUts, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeUts), nil
	}
}

func (s safeUtsDo) Last() (*model.SafeUts, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeUts), nil
	}
}

func (s safeUtsDo) Find() ([]*model.SafeUts, error) {
	result, err := s.DO.Find()
	return result.([]*model.SafeUts), err
}

func (s safeUtsDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeUts, err error) {
	buf := make([]*model.SafeUts, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s safeUtsDo) FindInBatches(result *[]*model.SafeUts, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s safeUtsDo) Attrs(attrs ...field.AssignExpr) ISafeUtsDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s safeUtsDo) Assign(attrs ...field.AssignExpr) ISafeUtsDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s safeUtsDo) Joins(fields ...field.RelationField) ISafeUtsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s safeUtsDo) Preload(fields ...field.RelationField) ISafeUtsDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s safeUtsDo) FirstOrInit() (*model.SafeUts, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeUts), nil
	}
}

func (s safeUtsDo) FirstOrCreate() (*model.SafeUts, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeUts), nil
	}
}

func (s safeUtsDo) FindByPage(offset int, limit int) (result []*model.SafeUts, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s safeUtsDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s safeUtsDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s safeUtsDo) Delete(models ...*model.SafeUts) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *safeUtsDo) withDO(do gen.Dao) *safeUtsDo {
	s.DO = *do.(*gen.DO)
	return s
}
