// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSafeIpaddress(db *gorm.DB, opts ...gen.DOOption) safeIpaddress {
	_safeIpaddress := safeIpaddress{}

	_safeIpaddress.safeIpaddressDo.UseDB(db, opts...)
	_safeIpaddress.safeIpaddressDo.UseModel(&model.SafeIpaddress{})

	tableName := _safeIpaddress.safeIpaddressDo.TableName()
	_safeIpaddress.ALL = field.NewAsterisk(tableName)
	_safeIpaddress.ID = field.NewInt64(tableName, "id")
	_safeIpaddress.CompanyID = field.NewField(tableName, "company_id")
	_safeIpaddress.IPAddress = field.NewString(tableName, "ip_address")
	_safeIpaddress.IPVersion = field.NewInt32(tableName, "ip_version")
	_safeIpaddress.IPType = field.NewInt32(tableName, "ip_type")
	_safeIpaddress.Purpose = field.NewString(tableName, "purpose")
	_safeIpaddress.IsActive = field.NewInt32(tableName, "is_active")
	_safeIpaddress.LastVerifiedAt = field.NewTime(tableName, "last_verified_at")
	_safeIpaddress.VerifiedBy = field.NewField(tableName, "verified_by")
	_safeIpaddress.CreatedAt = field.NewTime(tableName, "created_at")
	_safeIpaddress.UpdatedAt = field.NewField(tableName, "updated_at")
	_safeIpaddress.DeletedAt = field.NewField(tableName, "deleted_at")

	_safeIpaddress.fillFieldMap()

	return _safeIpaddress
}

type safeIpaddress struct {
	safeIpaddressDo

	ALL            field.Asterisk
	ID             field.Int64  // 主键
	CompanyID      field.Field  // 关联company_info.id
	IPAddress      field.String // IP地址（兼容IPv4/IPv6）
	IPVersion      field.Int32  // 4=IPv4, 6=IPv6
	IPType         field.Int32  // 1=官网,2=API,3=办公出口,4=CDN,5=数据库
	Purpose        field.String // 用途说明
	IsActive       field.Int32  // 是否启用
	LastVerifiedAt field.Time   // 最后验证时间
	VerifiedBy     field.Field  // 验证人
	CreatedAt      field.Time   // 创建时间
	UpdatedAt      field.Field  // 修改时间
	DeletedAt      field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s safeIpaddress) Table(newTableName string) *safeIpaddress {
	s.safeIpaddressDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s safeIpaddress) As(alias string) *safeIpaddress {
	s.safeIpaddressDo.DO = *(s.safeIpaddressDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *safeIpaddress) updateTableName(table string) *safeIpaddress {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.CompanyID = field.NewField(table, "company_id")
	s.IPAddress = field.NewString(table, "ip_address")
	s.IPVersion = field.NewInt32(table, "ip_version")
	s.IPType = field.NewInt32(table, "ip_type")
	s.Purpose = field.NewString(table, "purpose")
	s.IsActive = field.NewInt32(table, "is_active")
	s.LastVerifiedAt = field.NewTime(table, "last_verified_at")
	s.VerifiedBy = field.NewField(table, "verified_by")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewField(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *safeIpaddress) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *safeIpaddress) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["company_id"] = s.CompanyID
	s.fieldMap["ip_address"] = s.IPAddress
	s.fieldMap["ip_version"] = s.IPVersion
	s.fieldMap["ip_type"] = s.IPType
	s.fieldMap["purpose"] = s.Purpose
	s.fieldMap["is_active"] = s.IsActive
	s.fieldMap["last_verified_at"] = s.LastVerifiedAt
	s.fieldMap["verified_by"] = s.VerifiedBy
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s safeIpaddress) clone(db *gorm.DB) safeIpaddress {
	s.safeIpaddressDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s safeIpaddress) replaceDB(db *gorm.DB) safeIpaddress {
	s.safeIpaddressDo.ReplaceDB(db)
	return s
}

type safeIpaddressDo struct{ gen.DO }

type ISafeIpaddressDo interface {
	gen.SubQuery
	Debug() ISafeIpaddressDo
	WithContext(ctx context.Context) ISafeIpaddressDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISafeIpaddressDo
	WriteDB() ISafeIpaddressDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISafeIpaddressDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISafeIpaddressDo
	Not(conds ...gen.Condition) ISafeIpaddressDo
	Or(conds ...gen.Condition) ISafeIpaddressDo
	Select(conds ...field.Expr) ISafeIpaddressDo
	Where(conds ...gen.Condition) ISafeIpaddressDo
	Order(conds ...field.Expr) ISafeIpaddressDo
	Distinct(cols ...field.Expr) ISafeIpaddressDo
	Omit(cols ...field.Expr) ISafeIpaddressDo
	Join(table schema.Tabler, on ...field.Expr) ISafeIpaddressDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISafeIpaddressDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISafeIpaddressDo
	Group(cols ...field.Expr) ISafeIpaddressDo
	Having(conds ...gen.Condition) ISafeIpaddressDo
	Limit(limit int) ISafeIpaddressDo
	Offset(offset int) ISafeIpaddressDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeIpaddressDo
	Unscoped() ISafeIpaddressDo
	Create(values ...*model.SafeIpaddress) error
	CreateInBatches(values []*model.SafeIpaddress, batchSize int) error
	Save(values ...*model.SafeIpaddress) error
	First() (*model.SafeIpaddress, error)
	Take() (*model.SafeIpaddress, error)
	Last() (*model.SafeIpaddress, error)
	Find() ([]*model.SafeIpaddress, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeIpaddress, err error)
	FindInBatches(result *[]*model.SafeIpaddress, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SafeIpaddress) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISafeIpaddressDo
	Assign(attrs ...field.AssignExpr) ISafeIpaddressDo
	Joins(fields ...field.RelationField) ISafeIpaddressDo
	Preload(fields ...field.RelationField) ISafeIpaddressDo
	FirstOrInit() (*model.SafeIpaddress, error)
	FirstOrCreate() (*model.SafeIpaddress, error)
	FindByPage(offset int, limit int) (result []*model.SafeIpaddress, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISafeIpaddressDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s safeIpaddressDo) Debug() ISafeIpaddressDo {
	return s.withDO(s.DO.Debug())
}

func (s safeIpaddressDo) WithContext(ctx context.Context) ISafeIpaddressDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s safeIpaddressDo) ReadDB() ISafeIpaddressDo {
	return s.Clauses(dbresolver.Read)
}

func (s safeIpaddressDo) WriteDB() ISafeIpaddressDo {
	return s.Clauses(dbresolver.Write)
}

func (s safeIpaddressDo) Session(config *gorm.Session) ISafeIpaddressDo {
	return s.withDO(s.DO.Session(config))
}

func (s safeIpaddressDo) Clauses(conds ...clause.Expression) ISafeIpaddressDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s safeIpaddressDo) Returning(value interface{}, columns ...string) ISafeIpaddressDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s safeIpaddressDo) Not(conds ...gen.Condition) ISafeIpaddressDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s safeIpaddressDo) Or(conds ...gen.Condition) ISafeIpaddressDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s safeIpaddressDo) Select(conds ...field.Expr) ISafeIpaddressDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s safeIpaddressDo) Where(conds ...gen.Condition) ISafeIpaddressDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s safeIpaddressDo) Order(conds ...field.Expr) ISafeIpaddressDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s safeIpaddressDo) Distinct(cols ...field.Expr) ISafeIpaddressDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s safeIpaddressDo) Omit(cols ...field.Expr) ISafeIpaddressDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s safeIpaddressDo) Join(table schema.Tabler, on ...field.Expr) ISafeIpaddressDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s safeIpaddressDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISafeIpaddressDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s safeIpaddressDo) RightJoin(table schema.Tabler, on ...field.Expr) ISafeIpaddressDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s safeIpaddressDo) Group(cols ...field.Expr) ISafeIpaddressDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s safeIpaddressDo) Having(conds ...gen.Condition) ISafeIpaddressDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s safeIpaddressDo) Limit(limit int) ISafeIpaddressDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s safeIpaddressDo) Offset(offset int) ISafeIpaddressDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s safeIpaddressDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeIpaddressDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s safeIpaddressDo) Unscoped() ISafeIpaddressDo {
	return s.withDO(s.DO.Unscoped())
}

func (s safeIpaddressDo) Create(values ...*model.SafeIpaddress) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s safeIpaddressDo) CreateInBatches(values []*model.SafeIpaddress, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s safeIpaddressDo) Save(values ...*model.SafeIpaddress) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s safeIpaddressDo) First() (*model.SafeIpaddress, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIpaddress), nil
	}
}

func (s safeIpaddressDo) Take() (*model.SafeIpaddress, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIpaddress), nil
	}
}

func (s safeIpaddressDo) Last() (*model.SafeIpaddress, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIpaddress), nil
	}
}

func (s safeIpaddressDo) Find() ([]*model.SafeIpaddress, error) {
	result, err := s.DO.Find()
	return result.([]*model.SafeIpaddress), err
}

func (s safeIpaddressDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeIpaddress, err error) {
	buf := make([]*model.SafeIpaddress, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s safeIpaddressDo) FindInBatches(result *[]*model.SafeIpaddress, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s safeIpaddressDo) Attrs(attrs ...field.AssignExpr) ISafeIpaddressDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s safeIpaddressDo) Assign(attrs ...field.AssignExpr) ISafeIpaddressDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s safeIpaddressDo) Joins(fields ...field.RelationField) ISafeIpaddressDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s safeIpaddressDo) Preload(fields ...field.RelationField) ISafeIpaddressDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s safeIpaddressDo) FirstOrInit() (*model.SafeIpaddress, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIpaddress), nil
	}
}

func (s safeIpaddressDo) FirstOrCreate() (*model.SafeIpaddress, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIpaddress), nil
	}
}

func (s safeIpaddressDo) FindByPage(offset int, limit int) (result []*model.SafeIpaddress, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s safeIpaddressDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s safeIpaddressDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s safeIpaddressDo) Delete(models ...*model.SafeIpaddress) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *safeIpaddressDo) withDO(do gen.Dao) *safeIpaddressDo {
	s.DO = *do.(*gen.DO)
	return s
}
