// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSafeDictionary(db *gorm.DB, opts ...gen.DOOption) safeDictionary {
	_safeDictionary := safeDictionary{}

	_safeDictionary.safeDictionaryDo.UseDB(db, opts...)
	_safeDictionary.safeDictionaryDo.UseModel(&model.SafeDictionary{})

	tableName := _safeDictionary.safeDictionaryDo.TableName()
	_safeDictionary.ALL = field.NewAsterisk(tableName)
	_safeDictionary.ID = field.NewInt64(tableName, "id")
	_safeDictionary.ParentID = field.NewInt64(tableName, "parent_id")
	_safeDictionary.EventType = field.NewString(tableName, "event_type")
	_safeDictionary.EventName = field.NewString(tableName, "event_name")
	_safeDictionary.Disabled = field.NewInt32(tableName, "disabled")
	_safeDictionary.CreatedAt = field.NewTime(tableName, "created_at")
	_safeDictionary.UpdatedAt = field.NewField(tableName, "updated_at")
	_safeDictionary.DeletedAt = field.NewField(tableName, "deleted_at")

	_safeDictionary.fillFieldMap()

	return _safeDictionary
}

type safeDictionary struct {
	safeDictionaryDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键
	ParentID  field.Int64  // 上级告警事件ID
	EventType field.String // 告警事件编码
	EventName field.String // 告警事件名称
	Disabled  field.Int32  // 禁用状态
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Field  // 修改时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s safeDictionary) Table(newTableName string) *safeDictionary {
	s.safeDictionaryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s safeDictionary) As(alias string) *safeDictionary {
	s.safeDictionaryDo.DO = *(s.safeDictionaryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *safeDictionary) updateTableName(table string) *safeDictionary {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.ParentID = field.NewInt64(table, "parent_id")
	s.EventType = field.NewString(table, "event_type")
	s.EventName = field.NewString(table, "event_name")
	s.Disabled = field.NewInt32(table, "disabled")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewField(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *safeDictionary) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *safeDictionary) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["parent_id"] = s.ParentID
	s.fieldMap["event_type"] = s.EventType
	s.fieldMap["event_name"] = s.EventName
	s.fieldMap["disabled"] = s.Disabled
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s safeDictionary) clone(db *gorm.DB) safeDictionary {
	s.safeDictionaryDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s safeDictionary) replaceDB(db *gorm.DB) safeDictionary {
	s.safeDictionaryDo.ReplaceDB(db)
	return s
}

type safeDictionaryDo struct{ gen.DO }

type ISafeDictionaryDo interface {
	gen.SubQuery
	Debug() ISafeDictionaryDo
	WithContext(ctx context.Context) ISafeDictionaryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISafeDictionaryDo
	WriteDB() ISafeDictionaryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISafeDictionaryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISafeDictionaryDo
	Not(conds ...gen.Condition) ISafeDictionaryDo
	Or(conds ...gen.Condition) ISafeDictionaryDo
	Select(conds ...field.Expr) ISafeDictionaryDo
	Where(conds ...gen.Condition) ISafeDictionaryDo
	Order(conds ...field.Expr) ISafeDictionaryDo
	Distinct(cols ...field.Expr) ISafeDictionaryDo
	Omit(cols ...field.Expr) ISafeDictionaryDo
	Join(table schema.Tabler, on ...field.Expr) ISafeDictionaryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISafeDictionaryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISafeDictionaryDo
	Group(cols ...field.Expr) ISafeDictionaryDo
	Having(conds ...gen.Condition) ISafeDictionaryDo
	Limit(limit int) ISafeDictionaryDo
	Offset(offset int) ISafeDictionaryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeDictionaryDo
	Unscoped() ISafeDictionaryDo
	Create(values ...*model.SafeDictionary) error
	CreateInBatches(values []*model.SafeDictionary, batchSize int) error
	Save(values ...*model.SafeDictionary) error
	First() (*model.SafeDictionary, error)
	Take() (*model.SafeDictionary, error)
	Last() (*model.SafeDictionary, error)
	Find() ([]*model.SafeDictionary, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeDictionary, err error)
	FindInBatches(result *[]*model.SafeDictionary, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SafeDictionary) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISafeDictionaryDo
	Assign(attrs ...field.AssignExpr) ISafeDictionaryDo
	Joins(fields ...field.RelationField) ISafeDictionaryDo
	Preload(fields ...field.RelationField) ISafeDictionaryDo
	FirstOrInit() (*model.SafeDictionary, error)
	FirstOrCreate() (*model.SafeDictionary, error)
	FindByPage(offset int, limit int) (result []*model.SafeDictionary, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISafeDictionaryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s safeDictionaryDo) Debug() ISafeDictionaryDo {
	return s.withDO(s.DO.Debug())
}

func (s safeDictionaryDo) WithContext(ctx context.Context) ISafeDictionaryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s safeDictionaryDo) ReadDB() ISafeDictionaryDo {
	return s.Clauses(dbresolver.Read)
}

func (s safeDictionaryDo) WriteDB() ISafeDictionaryDo {
	return s.Clauses(dbresolver.Write)
}

func (s safeDictionaryDo) Session(config *gorm.Session) ISafeDictionaryDo {
	return s.withDO(s.DO.Session(config))
}

func (s safeDictionaryDo) Clauses(conds ...clause.Expression) ISafeDictionaryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s safeDictionaryDo) Returning(value interface{}, columns ...string) ISafeDictionaryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s safeDictionaryDo) Not(conds ...gen.Condition) ISafeDictionaryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s safeDictionaryDo) Or(conds ...gen.Condition) ISafeDictionaryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s safeDictionaryDo) Select(conds ...field.Expr) ISafeDictionaryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s safeDictionaryDo) Where(conds ...gen.Condition) ISafeDictionaryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s safeDictionaryDo) Order(conds ...field.Expr) ISafeDictionaryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s safeDictionaryDo) Distinct(cols ...field.Expr) ISafeDictionaryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s safeDictionaryDo) Omit(cols ...field.Expr) ISafeDictionaryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s safeDictionaryDo) Join(table schema.Tabler, on ...field.Expr) ISafeDictionaryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s safeDictionaryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISafeDictionaryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s safeDictionaryDo) RightJoin(table schema.Tabler, on ...field.Expr) ISafeDictionaryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s safeDictionaryDo) Group(cols ...field.Expr) ISafeDictionaryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s safeDictionaryDo) Having(conds ...gen.Condition) ISafeDictionaryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s safeDictionaryDo) Limit(limit int) ISafeDictionaryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s safeDictionaryDo) Offset(offset int) ISafeDictionaryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s safeDictionaryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeDictionaryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s safeDictionaryDo) Unscoped() ISafeDictionaryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s safeDictionaryDo) Create(values ...*model.SafeDictionary) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s safeDictionaryDo) CreateInBatches(values []*model.SafeDictionary, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s safeDictionaryDo) Save(values ...*model.SafeDictionary) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s safeDictionaryDo) First() (*model.SafeDictionary, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeDictionary), nil
	}
}

func (s safeDictionaryDo) Take() (*model.SafeDictionary, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeDictionary), nil
	}
}

func (s safeDictionaryDo) Last() (*model.SafeDictionary, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeDictionary), nil
	}
}

func (s safeDictionaryDo) Find() ([]*model.SafeDictionary, error) {
	result, err := s.DO.Find()
	return result.([]*model.SafeDictionary), err
}

func (s safeDictionaryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeDictionary, err error) {
	buf := make([]*model.SafeDictionary, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s safeDictionaryDo) FindInBatches(result *[]*model.SafeDictionary, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s safeDictionaryDo) Attrs(attrs ...field.AssignExpr) ISafeDictionaryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s safeDictionaryDo) Assign(attrs ...field.AssignExpr) ISafeDictionaryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s safeDictionaryDo) Joins(fields ...field.RelationField) ISafeDictionaryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s safeDictionaryDo) Preload(fields ...field.RelationField) ISafeDictionaryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s safeDictionaryDo) FirstOrInit() (*model.SafeDictionary, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeDictionary), nil
	}
}

func (s safeDictionaryDo) FirstOrCreate() (*model.SafeDictionary, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeDictionary), nil
	}
}

func (s safeDictionaryDo) FindByPage(offset int, limit int) (result []*model.SafeDictionary, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s safeDictionaryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s safeDictionaryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s safeDictionaryDo) Delete(models ...*model.SafeDictionary) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *safeDictionaryDo) withDO(do gen.Dao) *safeDictionaryDo {
	s.DO = *do.(*gen.DO)
	return s
}
