// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSafeIPLevel(db *gorm.DB, opts ...gen.DOOption) safeIPLevel {
	_safeIPLevel := safeIPLevel{}

	_safeIPLevel.safeIPLevelDo.UseDB(db, opts...)
	_safeIPLevel.safeIPLevelDo.UseModel(&model.SafeIPLevel{})

	tableName := _safeIPLevel.safeIPLevelDo.TableName()
	_safeIPLevel.ALL = field.NewAsterisk(tableName)
	_safeIPLevel.ID = field.NewInt64(tableName, "id")
	_safeIPLevel.AddressID = field.NewInt64(tableName, "address_id")
	_safeIPLevel.Date = field.NewTime(tableName, "date")
	_safeIPLevel.High = field.NewInt32(tableName, "high")
	_safeIPLevel.Medium = field.NewInt32(tableName, "medium")
	_safeIPLevel.Low = field.NewInt32(tableName, "low")
	_safeIPLevel.CreatedAt = field.NewTime(tableName, "created_at")
	_safeIPLevel.UpdatedAt = field.NewField(tableName, "updated_at")

	_safeIPLevel.fillFieldMap()

	return _safeIPLevel
}

type safeIPLevel struct {
	safeIPLevelDo

	ALL       field.Asterisk
	ID        field.Int64 // 主键
	AddressID field.Int64 // IP地址ID
	Date      field.Time  // 日期
	High      field.Int32 // 高
	Medium    field.Int32 // 中
	Low       field.Int32 // 低
	CreatedAt field.Time  // 创建时间
	UpdatedAt field.Field // 修改时间

	fieldMap map[string]field.Expr
}

func (s safeIPLevel) Table(newTableName string) *safeIPLevel {
	s.safeIPLevelDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s safeIPLevel) As(alias string) *safeIPLevel {
	s.safeIPLevelDo.DO = *(s.safeIPLevelDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *safeIPLevel) updateTableName(table string) *safeIPLevel {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.AddressID = field.NewInt64(table, "address_id")
	s.Date = field.NewTime(table, "date")
	s.High = field.NewInt32(table, "high")
	s.Medium = field.NewInt32(table, "medium")
	s.Low = field.NewInt32(table, "low")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewField(table, "updated_at")

	s.fillFieldMap()

	return s
}

func (s *safeIPLevel) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *safeIPLevel) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 8)
	s.fieldMap["id"] = s.ID
	s.fieldMap["address_id"] = s.AddressID
	s.fieldMap["date"] = s.Date
	s.fieldMap["high"] = s.High
	s.fieldMap["medium"] = s.Medium
	s.fieldMap["low"] = s.Low
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
}

func (s safeIPLevel) clone(db *gorm.DB) safeIPLevel {
	s.safeIPLevelDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s safeIPLevel) replaceDB(db *gorm.DB) safeIPLevel {
	s.safeIPLevelDo.ReplaceDB(db)
	return s
}

type safeIPLevelDo struct{ gen.DO }

type ISafeIPLevelDo interface {
	gen.SubQuery
	Debug() ISafeIPLevelDo
	WithContext(ctx context.Context) ISafeIPLevelDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISafeIPLevelDo
	WriteDB() ISafeIPLevelDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISafeIPLevelDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISafeIPLevelDo
	Not(conds ...gen.Condition) ISafeIPLevelDo
	Or(conds ...gen.Condition) ISafeIPLevelDo
	Select(conds ...field.Expr) ISafeIPLevelDo
	Where(conds ...gen.Condition) ISafeIPLevelDo
	Order(conds ...field.Expr) ISafeIPLevelDo
	Distinct(cols ...field.Expr) ISafeIPLevelDo
	Omit(cols ...field.Expr) ISafeIPLevelDo
	Join(table schema.Tabler, on ...field.Expr) ISafeIPLevelDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISafeIPLevelDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISafeIPLevelDo
	Group(cols ...field.Expr) ISafeIPLevelDo
	Having(conds ...gen.Condition) ISafeIPLevelDo
	Limit(limit int) ISafeIPLevelDo
	Offset(offset int) ISafeIPLevelDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeIPLevelDo
	Unscoped() ISafeIPLevelDo
	Create(values ...*model.SafeIPLevel) error
	CreateInBatches(values []*model.SafeIPLevel, batchSize int) error
	Save(values ...*model.SafeIPLevel) error
	First() (*model.SafeIPLevel, error)
	Take() (*model.SafeIPLevel, error)
	Last() (*model.SafeIPLevel, error)
	Find() ([]*model.SafeIPLevel, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeIPLevel, err error)
	FindInBatches(result *[]*model.SafeIPLevel, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SafeIPLevel) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISafeIPLevelDo
	Assign(attrs ...field.AssignExpr) ISafeIPLevelDo
	Joins(fields ...field.RelationField) ISafeIPLevelDo
	Preload(fields ...field.RelationField) ISafeIPLevelDo
	FirstOrInit() (*model.SafeIPLevel, error)
	FirstOrCreate() (*model.SafeIPLevel, error)
	FindByPage(offset int, limit int) (result []*model.SafeIPLevel, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISafeIPLevelDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s safeIPLevelDo) Debug() ISafeIPLevelDo {
	return s.withDO(s.DO.Debug())
}

func (s safeIPLevelDo) WithContext(ctx context.Context) ISafeIPLevelDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s safeIPLevelDo) ReadDB() ISafeIPLevelDo {
	return s.Clauses(dbresolver.Read)
}

func (s safeIPLevelDo) WriteDB() ISafeIPLevelDo {
	return s.Clauses(dbresolver.Write)
}

func (s safeIPLevelDo) Session(config *gorm.Session) ISafeIPLevelDo {
	return s.withDO(s.DO.Session(config))
}

func (s safeIPLevelDo) Clauses(conds ...clause.Expression) ISafeIPLevelDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s safeIPLevelDo) Returning(value interface{}, columns ...string) ISafeIPLevelDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s safeIPLevelDo) Not(conds ...gen.Condition) ISafeIPLevelDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s safeIPLevelDo) Or(conds ...gen.Condition) ISafeIPLevelDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s safeIPLevelDo) Select(conds ...field.Expr) ISafeIPLevelDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s safeIPLevelDo) Where(conds ...gen.Condition) ISafeIPLevelDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s safeIPLevelDo) Order(conds ...field.Expr) ISafeIPLevelDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s safeIPLevelDo) Distinct(cols ...field.Expr) ISafeIPLevelDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s safeIPLevelDo) Omit(cols ...field.Expr) ISafeIPLevelDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s safeIPLevelDo) Join(table schema.Tabler, on ...field.Expr) ISafeIPLevelDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s safeIPLevelDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISafeIPLevelDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s safeIPLevelDo) RightJoin(table schema.Tabler, on ...field.Expr) ISafeIPLevelDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s safeIPLevelDo) Group(cols ...field.Expr) ISafeIPLevelDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s safeIPLevelDo) Having(conds ...gen.Condition) ISafeIPLevelDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s safeIPLevelDo) Limit(limit int) ISafeIPLevelDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s safeIPLevelDo) Offset(offset int) ISafeIPLevelDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s safeIPLevelDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISafeIPLevelDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s safeIPLevelDo) Unscoped() ISafeIPLevelDo {
	return s.withDO(s.DO.Unscoped())
}

func (s safeIPLevelDo) Create(values ...*model.SafeIPLevel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s safeIPLevelDo) CreateInBatches(values []*model.SafeIPLevel, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s safeIPLevelDo) Save(values ...*model.SafeIPLevel) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s safeIPLevelDo) First() (*model.SafeIPLevel, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIPLevel), nil
	}
}

func (s safeIPLevelDo) Take() (*model.SafeIPLevel, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIPLevel), nil
	}
}

func (s safeIPLevelDo) Last() (*model.SafeIPLevel, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIPLevel), nil
	}
}

func (s safeIPLevelDo) Find() ([]*model.SafeIPLevel, error) {
	result, err := s.DO.Find()
	return result.([]*model.SafeIPLevel), err
}

func (s safeIPLevelDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SafeIPLevel, err error) {
	buf := make([]*model.SafeIPLevel, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s safeIPLevelDo) FindInBatches(result *[]*model.SafeIPLevel, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s safeIPLevelDo) Attrs(attrs ...field.AssignExpr) ISafeIPLevelDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s safeIPLevelDo) Assign(attrs ...field.AssignExpr) ISafeIPLevelDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s safeIPLevelDo) Joins(fields ...field.RelationField) ISafeIPLevelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s safeIPLevelDo) Preload(fields ...field.RelationField) ISafeIPLevelDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s safeIPLevelDo) FirstOrInit() (*model.SafeIPLevel, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIPLevel), nil
	}
}

func (s safeIPLevelDo) FirstOrCreate() (*model.SafeIPLevel, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SafeIPLevel), nil
	}
}

func (s safeIPLevelDo) FindByPage(offset int, limit int) (result []*model.SafeIPLevel, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s safeIPLevelDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s safeIPLevelDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s safeIPLevelDo) Delete(models ...*model.SafeIPLevel) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *safeIPLevelDo) withDO(do gen.Dao) *safeIPLevelDo {
	s.DO = *do.(*gen.DO)
	return s
}
