// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSysDictionaries(db *gorm.DB, opts ...gen.DOOption) sysDictionaries {
	_sysDictionaries := sysDictionaries{}

	_sysDictionaries.sysDictionariesDo.UseDB(db, opts...)
	_sysDictionaries.sysDictionariesDo.UseModel(&model.SysDictionaries{})

	tableName := _sysDictionaries.sysDictionariesDo.TableName()
	_sysDictionaries.ALL = field.NewAsterisk(tableName)
	_sysDictionaries.ID = field.NewInt64(tableName, "id")
	_sysDictionaries.DictID = field.NewInt64(tableName, "dict_id")
	_sysDictionaries.Title = field.NewString(tableName, "title")
	_sysDictionaries.Value = field.NewString(tableName, "value")
	_sysDictionaries.Sort = field.NewInt32(tableName, "sort")
	_sysDictionaries.Disabled = field.NewInt32(tableName, "disabled")
	_sysDictionaries.CreatedAt = field.NewTime(tableName, "created_at")
	_sysDictionaries.UpdatedAt = field.NewField(tableName, "updated_at")
	_sysDictionaries.DeletedAt = field.NewField(tableName, "deleted_at")

	_sysDictionaries.fillFieldMap()

	return _sysDictionaries
}

type sysDictionaries struct {
	sysDictionariesDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键
	DictID    field.Int64  // 字典类型id
	Title     field.String // 字典名称
	Value     field.String // 字典内容
	Sort      field.Int32  // 显示顺序
	Disabled  field.Int32  // 禁用状态
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Field  // 修改时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s sysDictionaries) Table(newTableName string) *sysDictionaries {
	s.sysDictionariesDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysDictionaries) As(alias string) *sysDictionaries {
	s.sysDictionariesDo.DO = *(s.sysDictionariesDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysDictionaries) updateTableName(table string) *sysDictionaries {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.DictID = field.NewInt64(table, "dict_id")
	s.Title = field.NewString(table, "title")
	s.Value = field.NewString(table, "value")
	s.Sort = field.NewInt32(table, "sort")
	s.Disabled = field.NewInt32(table, "disabled")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewField(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sysDictionaries) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysDictionaries) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["dict_id"] = s.DictID
	s.fieldMap["title"] = s.Title
	s.fieldMap["value"] = s.Value
	s.fieldMap["sort"] = s.Sort
	s.fieldMap["disabled"] = s.Disabled
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s sysDictionaries) clone(db *gorm.DB) sysDictionaries {
	s.sysDictionariesDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysDictionaries) replaceDB(db *gorm.DB) sysDictionaries {
	s.sysDictionariesDo.ReplaceDB(db)
	return s
}

type sysDictionariesDo struct{ gen.DO }

type ISysDictionariesDo interface {
	gen.SubQuery
	Debug() ISysDictionariesDo
	WithContext(ctx context.Context) ISysDictionariesDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysDictionariesDo
	WriteDB() ISysDictionariesDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysDictionariesDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysDictionariesDo
	Not(conds ...gen.Condition) ISysDictionariesDo
	Or(conds ...gen.Condition) ISysDictionariesDo
	Select(conds ...field.Expr) ISysDictionariesDo
	Where(conds ...gen.Condition) ISysDictionariesDo
	Order(conds ...field.Expr) ISysDictionariesDo
	Distinct(cols ...field.Expr) ISysDictionariesDo
	Omit(cols ...field.Expr) ISysDictionariesDo
	Join(table schema.Tabler, on ...field.Expr) ISysDictionariesDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysDictionariesDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysDictionariesDo
	Group(cols ...field.Expr) ISysDictionariesDo
	Having(conds ...gen.Condition) ISysDictionariesDo
	Limit(limit int) ISysDictionariesDo
	Offset(offset int) ISysDictionariesDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDictionariesDo
	Unscoped() ISysDictionariesDo
	Create(values ...*model.SysDictionaries) error
	CreateInBatches(values []*model.SysDictionaries, batchSize int) error
	Save(values ...*model.SysDictionaries) error
	First() (*model.SysDictionaries, error)
	Take() (*model.SysDictionaries, error)
	Last() (*model.SysDictionaries, error)
	Find() ([]*model.SysDictionaries, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDictionaries, err error)
	FindInBatches(result *[]*model.SysDictionaries, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysDictionaries) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysDictionariesDo
	Assign(attrs ...field.AssignExpr) ISysDictionariesDo
	Joins(fields ...field.RelationField) ISysDictionariesDo
	Preload(fields ...field.RelationField) ISysDictionariesDo
	FirstOrInit() (*model.SysDictionaries, error)
	FirstOrCreate() (*model.SysDictionaries, error)
	FindByPage(offset int, limit int) (result []*model.SysDictionaries, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysDictionariesDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysDictionariesDo) Debug() ISysDictionariesDo {
	return s.withDO(s.DO.Debug())
}

func (s sysDictionariesDo) WithContext(ctx context.Context) ISysDictionariesDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysDictionariesDo) ReadDB() ISysDictionariesDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysDictionariesDo) WriteDB() ISysDictionariesDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysDictionariesDo) Session(config *gorm.Session) ISysDictionariesDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysDictionariesDo) Clauses(conds ...clause.Expression) ISysDictionariesDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysDictionariesDo) Returning(value interface{}, columns ...string) ISysDictionariesDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysDictionariesDo) Not(conds ...gen.Condition) ISysDictionariesDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysDictionariesDo) Or(conds ...gen.Condition) ISysDictionariesDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysDictionariesDo) Select(conds ...field.Expr) ISysDictionariesDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysDictionariesDo) Where(conds ...gen.Condition) ISysDictionariesDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysDictionariesDo) Order(conds ...field.Expr) ISysDictionariesDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysDictionariesDo) Distinct(cols ...field.Expr) ISysDictionariesDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysDictionariesDo) Omit(cols ...field.Expr) ISysDictionariesDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysDictionariesDo) Join(table schema.Tabler, on ...field.Expr) ISysDictionariesDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysDictionariesDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysDictionariesDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysDictionariesDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysDictionariesDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysDictionariesDo) Group(cols ...field.Expr) ISysDictionariesDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysDictionariesDo) Having(conds ...gen.Condition) ISysDictionariesDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysDictionariesDo) Limit(limit int) ISysDictionariesDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysDictionariesDo) Offset(offset int) ISysDictionariesDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysDictionariesDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysDictionariesDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysDictionariesDo) Unscoped() ISysDictionariesDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysDictionariesDo) Create(values ...*model.SysDictionaries) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysDictionariesDo) CreateInBatches(values []*model.SysDictionaries, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysDictionariesDo) Save(values ...*model.SysDictionaries) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysDictionariesDo) First() (*model.SysDictionaries, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictionaries), nil
	}
}

func (s sysDictionariesDo) Take() (*model.SysDictionaries, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictionaries), nil
	}
}

func (s sysDictionariesDo) Last() (*model.SysDictionaries, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictionaries), nil
	}
}

func (s sysDictionariesDo) Find() ([]*model.SysDictionaries, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysDictionaries), err
}

func (s sysDictionariesDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysDictionaries, err error) {
	buf := make([]*model.SysDictionaries, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysDictionariesDo) FindInBatches(result *[]*model.SysDictionaries, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysDictionariesDo) Attrs(attrs ...field.AssignExpr) ISysDictionariesDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysDictionariesDo) Assign(attrs ...field.AssignExpr) ISysDictionariesDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysDictionariesDo) Joins(fields ...field.RelationField) ISysDictionariesDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysDictionariesDo) Preload(fields ...field.RelationField) ISysDictionariesDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysDictionariesDo) FirstOrInit() (*model.SysDictionaries, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictionaries), nil
	}
}

func (s sysDictionariesDo) FirstOrCreate() (*model.SysDictionaries, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysDictionaries), nil
	}
}

func (s sysDictionariesDo) FindByPage(offset int, limit int) (result []*model.SysDictionaries, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysDictionariesDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysDictionariesDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysDictionariesDo) Delete(models ...*model.SysDictionaries) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysDictionariesDo) withDO(do gen.Dao) *sysDictionariesDo {
	s.DO = *do.(*gen.DO)
	return s
}
