// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSysActionLog(db *gorm.DB, opts ...gen.DOOption) sysActionLog {
	_sysActionLog := sysActionLog{}

	_sysActionLog.sysActionLogDo.UseDB(db, opts...)
	_sysActionLog.sysActionLogDo.UseModel(&model.SysActionLog{})

	tableName := _sysActionLog.sysActionLogDo.TableName()
	_sysActionLog.ALL = field.NewAsterisk(tableName)
	_sysActionLog.ID = field.NewInt64(tableName, "id")
	_sysActionLog.Method = field.NewString(tableName, "method")
	_sysActionLog.Path = field.NewString(tableName, "path")
	_sysActionLog.Enctype = field.NewString(tableName, "enctype")
	_sysActionLog.Query = field.NewString(tableName, "query")
	_sysActionLog.Body = field.NewString(tableName, "body")
	_sysActionLog.Remote = field.NewString(tableName, "remote")
	_sysActionLog.UID = field.NewField(tableName, "uid")
	_sysActionLog.CreatedAt = field.NewTime(tableName, "created_at")

	_sysActionLog.fillFieldMap()

	return _sysActionLog
}

type sysActionLog struct {
	sysActionLogDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键
	Method    field.String // 请求方式
	Path      field.String // 请求地址
	Enctype   field.String // 表单类型
	Query     field.String // 请求url参数
	Body      field.String // 请求内容
	Remote    field.String // 远程地址
	UID       field.Field  // 用户id
	CreatedAt field.Time   // 创建时间

	fieldMap map[string]field.Expr
}

func (s sysActionLog) Table(newTableName string) *sysActionLog {
	s.sysActionLogDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysActionLog) As(alias string) *sysActionLog {
	s.sysActionLogDo.DO = *(s.sysActionLogDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysActionLog) updateTableName(table string) *sysActionLog {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Method = field.NewString(table, "method")
	s.Path = field.NewString(table, "path")
	s.Enctype = field.NewString(table, "enctype")
	s.Query = field.NewString(table, "query")
	s.Body = field.NewString(table, "body")
	s.Remote = field.NewString(table, "remote")
	s.UID = field.NewField(table, "uid")
	s.CreatedAt = field.NewTime(table, "created_at")

	s.fillFieldMap()

	return s
}

func (s *sysActionLog) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysActionLog) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 9)
	s.fieldMap["id"] = s.ID
	s.fieldMap["method"] = s.Method
	s.fieldMap["path"] = s.Path
	s.fieldMap["enctype"] = s.Enctype
	s.fieldMap["query"] = s.Query
	s.fieldMap["body"] = s.Body
	s.fieldMap["remote"] = s.Remote
	s.fieldMap["uid"] = s.UID
	s.fieldMap["created_at"] = s.CreatedAt
}

func (s sysActionLog) clone(db *gorm.DB) sysActionLog {
	s.sysActionLogDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysActionLog) replaceDB(db *gorm.DB) sysActionLog {
	s.sysActionLogDo.ReplaceDB(db)
	return s
}

type sysActionLogDo struct{ gen.DO }

type ISysActionLogDo interface {
	gen.SubQuery
	Debug() ISysActionLogDo
	WithContext(ctx context.Context) ISysActionLogDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysActionLogDo
	WriteDB() ISysActionLogDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysActionLogDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysActionLogDo
	Not(conds ...gen.Condition) ISysActionLogDo
	Or(conds ...gen.Condition) ISysActionLogDo
	Select(conds ...field.Expr) ISysActionLogDo
	Where(conds ...gen.Condition) ISysActionLogDo
	Order(conds ...field.Expr) ISysActionLogDo
	Distinct(cols ...field.Expr) ISysActionLogDo
	Omit(cols ...field.Expr) ISysActionLogDo
	Join(table schema.Tabler, on ...field.Expr) ISysActionLogDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysActionLogDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysActionLogDo
	Group(cols ...field.Expr) ISysActionLogDo
	Having(conds ...gen.Condition) ISysActionLogDo
	Limit(limit int) ISysActionLogDo
	Offset(offset int) ISysActionLogDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysActionLogDo
	Unscoped() ISysActionLogDo
	Create(values ...*model.SysActionLog) error
	CreateInBatches(values []*model.SysActionLog, batchSize int) error
	Save(values ...*model.SysActionLog) error
	First() (*model.SysActionLog, error)
	Take() (*model.SysActionLog, error)
	Last() (*model.SysActionLog, error)
	Find() ([]*model.SysActionLog, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysActionLog, err error)
	FindInBatches(result *[]*model.SysActionLog, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysActionLog) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysActionLogDo
	Assign(attrs ...field.AssignExpr) ISysActionLogDo
	Joins(fields ...field.RelationField) ISysActionLogDo
	Preload(fields ...field.RelationField) ISysActionLogDo
	FirstOrInit() (*model.SysActionLog, error)
	FirstOrCreate() (*model.SysActionLog, error)
	FindByPage(offset int, limit int) (result []*model.SysActionLog, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysActionLogDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysActionLogDo) Debug() ISysActionLogDo {
	return s.withDO(s.DO.Debug())
}

func (s sysActionLogDo) WithContext(ctx context.Context) ISysActionLogDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysActionLogDo) ReadDB() ISysActionLogDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysActionLogDo) WriteDB() ISysActionLogDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysActionLogDo) Session(config *gorm.Session) ISysActionLogDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysActionLogDo) Clauses(conds ...clause.Expression) ISysActionLogDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysActionLogDo) Returning(value interface{}, columns ...string) ISysActionLogDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysActionLogDo) Not(conds ...gen.Condition) ISysActionLogDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysActionLogDo) Or(conds ...gen.Condition) ISysActionLogDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysActionLogDo) Select(conds ...field.Expr) ISysActionLogDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysActionLogDo) Where(conds ...gen.Condition) ISysActionLogDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysActionLogDo) Order(conds ...field.Expr) ISysActionLogDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysActionLogDo) Distinct(cols ...field.Expr) ISysActionLogDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysActionLogDo) Omit(cols ...field.Expr) ISysActionLogDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysActionLogDo) Join(table schema.Tabler, on ...field.Expr) ISysActionLogDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysActionLogDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysActionLogDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysActionLogDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysActionLogDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysActionLogDo) Group(cols ...field.Expr) ISysActionLogDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysActionLogDo) Having(conds ...gen.Condition) ISysActionLogDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysActionLogDo) Limit(limit int) ISysActionLogDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysActionLogDo) Offset(offset int) ISysActionLogDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysActionLogDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysActionLogDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysActionLogDo) Unscoped() ISysActionLogDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysActionLogDo) Create(values ...*model.SysActionLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysActionLogDo) CreateInBatches(values []*model.SysActionLog, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysActionLogDo) Save(values ...*model.SysActionLog) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysActionLogDo) First() (*model.SysActionLog, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysActionLog), nil
	}
}

func (s sysActionLogDo) Take() (*model.SysActionLog, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysActionLog), nil
	}
}

func (s sysActionLogDo) Last() (*model.SysActionLog, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysActionLog), nil
	}
}

func (s sysActionLogDo) Find() ([]*model.SysActionLog, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysActionLog), err
}

func (s sysActionLogDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysActionLog, err error) {
	buf := make([]*model.SysActionLog, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysActionLogDo) FindInBatches(result *[]*model.SysActionLog, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysActionLogDo) Attrs(attrs ...field.AssignExpr) ISysActionLogDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysActionLogDo) Assign(attrs ...field.AssignExpr) ISysActionLogDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysActionLogDo) Joins(fields ...field.RelationField) ISysActionLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysActionLogDo) Preload(fields ...field.RelationField) ISysActionLogDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysActionLogDo) FirstOrInit() (*model.SysActionLog, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysActionLog), nil
	}
}

func (s sysActionLogDo) FirstOrCreate() (*model.SysActionLog, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysActionLog), nil
	}
}

func (s sysActionLogDo) FindByPage(offset int, limit int) (result []*model.SysActionLog, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysActionLogDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysActionLogDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysActionLogDo) Delete(models ...*model.SysActionLog) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysActionLogDo) withDO(do gen.Dao) *sysActionLogDo {
	s.DO = *do.(*gen.DO)
	return s
}
