// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSysAlbumCategory(db *gorm.DB, opts ...gen.DOOption) sysAlbumCategory {
	_sysAlbumCategory := sysAlbumCategory{}

	_sysAlbumCategory.sysAlbumCategoryDo.UseDB(db, opts...)
	_sysAlbumCategory.sysAlbumCategoryDo.UseModel(&model.SysAlbumCategory{})

	tableName := _sysAlbumCategory.sysAlbumCategoryDo.TableName()
	_sysAlbumCategory.ALL = field.NewAsterisk(tableName)
	_sysAlbumCategory.ID = field.NewInt64(tableName, "id")
	_sysAlbumCategory.Pid = field.NewInt64(tableName, "pid")
	_sysAlbumCategory.Type = field.NewInt32(tableName, "type")
	_sysAlbumCategory.Name = field.NewString(tableName, "name")
	_sysAlbumCategory.CreatedAt = field.NewTime(tableName, "created_at")
	_sysAlbumCategory.UpdatedAt = field.NewField(tableName, "updated_at")
	_sysAlbumCategory.DeletedAt = field.NewField(tableName, "deleted_at")

	_sysAlbumCategory.fillFieldMap()

	return _sysAlbumCategory
}

type sysAlbumCategory struct {
	sysAlbumCategoryDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键ID
	Pid       field.Int64  // 父级ID
	Type      field.Int32  // 类型: [10=图片, 20=视频]
	Name      field.String // 分类名称
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Field  // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s sysAlbumCategory) Table(newTableName string) *sysAlbumCategory {
	s.sysAlbumCategoryDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysAlbumCategory) As(alias string) *sysAlbumCategory {
	s.sysAlbumCategoryDo.DO = *(s.sysAlbumCategoryDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysAlbumCategory) updateTableName(table string) *sysAlbumCategory {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Pid = field.NewInt64(table, "pid")
	s.Type = field.NewInt32(table, "type")
	s.Name = field.NewString(table, "name")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewField(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sysAlbumCategory) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysAlbumCategory) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 7)
	s.fieldMap["id"] = s.ID
	s.fieldMap["pid"] = s.Pid
	s.fieldMap["type"] = s.Type
	s.fieldMap["name"] = s.Name
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s sysAlbumCategory) clone(db *gorm.DB) sysAlbumCategory {
	s.sysAlbumCategoryDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysAlbumCategory) replaceDB(db *gorm.DB) sysAlbumCategory {
	s.sysAlbumCategoryDo.ReplaceDB(db)
	return s
}

type sysAlbumCategoryDo struct{ gen.DO }

type ISysAlbumCategoryDo interface {
	gen.SubQuery
	Debug() ISysAlbumCategoryDo
	WithContext(ctx context.Context) ISysAlbumCategoryDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysAlbumCategoryDo
	WriteDB() ISysAlbumCategoryDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysAlbumCategoryDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysAlbumCategoryDo
	Not(conds ...gen.Condition) ISysAlbumCategoryDo
	Or(conds ...gen.Condition) ISysAlbumCategoryDo
	Select(conds ...field.Expr) ISysAlbumCategoryDo
	Where(conds ...gen.Condition) ISysAlbumCategoryDo
	Order(conds ...field.Expr) ISysAlbumCategoryDo
	Distinct(cols ...field.Expr) ISysAlbumCategoryDo
	Omit(cols ...field.Expr) ISysAlbumCategoryDo
	Join(table schema.Tabler, on ...field.Expr) ISysAlbumCategoryDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysAlbumCategoryDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysAlbumCategoryDo
	Group(cols ...field.Expr) ISysAlbumCategoryDo
	Having(conds ...gen.Condition) ISysAlbumCategoryDo
	Limit(limit int) ISysAlbumCategoryDo
	Offset(offset int) ISysAlbumCategoryDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAlbumCategoryDo
	Unscoped() ISysAlbumCategoryDo
	Create(values ...*model.SysAlbumCategory) error
	CreateInBatches(values []*model.SysAlbumCategory, batchSize int) error
	Save(values ...*model.SysAlbumCategory) error
	First() (*model.SysAlbumCategory, error)
	Take() (*model.SysAlbumCategory, error)
	Last() (*model.SysAlbumCategory, error)
	Find() ([]*model.SysAlbumCategory, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAlbumCategory, err error)
	FindInBatches(result *[]*model.SysAlbumCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysAlbumCategory) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysAlbumCategoryDo
	Assign(attrs ...field.AssignExpr) ISysAlbumCategoryDo
	Joins(fields ...field.RelationField) ISysAlbumCategoryDo
	Preload(fields ...field.RelationField) ISysAlbumCategoryDo
	FirstOrInit() (*model.SysAlbumCategory, error)
	FirstOrCreate() (*model.SysAlbumCategory, error)
	FindByPage(offset int, limit int) (result []*model.SysAlbumCategory, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysAlbumCategoryDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysAlbumCategoryDo) Debug() ISysAlbumCategoryDo {
	return s.withDO(s.DO.Debug())
}

func (s sysAlbumCategoryDo) WithContext(ctx context.Context) ISysAlbumCategoryDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysAlbumCategoryDo) ReadDB() ISysAlbumCategoryDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysAlbumCategoryDo) WriteDB() ISysAlbumCategoryDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysAlbumCategoryDo) Session(config *gorm.Session) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysAlbumCategoryDo) Clauses(conds ...clause.Expression) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysAlbumCategoryDo) Returning(value interface{}, columns ...string) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysAlbumCategoryDo) Not(conds ...gen.Condition) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysAlbumCategoryDo) Or(conds ...gen.Condition) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysAlbumCategoryDo) Select(conds ...field.Expr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysAlbumCategoryDo) Where(conds ...gen.Condition) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysAlbumCategoryDo) Order(conds ...field.Expr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysAlbumCategoryDo) Distinct(cols ...field.Expr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysAlbumCategoryDo) Omit(cols ...field.Expr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysAlbumCategoryDo) Join(table schema.Tabler, on ...field.Expr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysAlbumCategoryDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysAlbumCategoryDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysAlbumCategoryDo) Group(cols ...field.Expr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysAlbumCategoryDo) Having(conds ...gen.Condition) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysAlbumCategoryDo) Limit(limit int) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysAlbumCategoryDo) Offset(offset int) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysAlbumCategoryDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysAlbumCategoryDo) Unscoped() ISysAlbumCategoryDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysAlbumCategoryDo) Create(values ...*model.SysAlbumCategory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysAlbumCategoryDo) CreateInBatches(values []*model.SysAlbumCategory, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysAlbumCategoryDo) Save(values ...*model.SysAlbumCategory) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysAlbumCategoryDo) First() (*model.SysAlbumCategory, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbumCategory), nil
	}
}

func (s sysAlbumCategoryDo) Take() (*model.SysAlbumCategory, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbumCategory), nil
	}
}

func (s sysAlbumCategoryDo) Last() (*model.SysAlbumCategory, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbumCategory), nil
	}
}

func (s sysAlbumCategoryDo) Find() ([]*model.SysAlbumCategory, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysAlbumCategory), err
}

func (s sysAlbumCategoryDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAlbumCategory, err error) {
	buf := make([]*model.SysAlbumCategory, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysAlbumCategoryDo) FindInBatches(result *[]*model.SysAlbumCategory, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysAlbumCategoryDo) Attrs(attrs ...field.AssignExpr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysAlbumCategoryDo) Assign(attrs ...field.AssignExpr) ISysAlbumCategoryDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysAlbumCategoryDo) Joins(fields ...field.RelationField) ISysAlbumCategoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysAlbumCategoryDo) Preload(fields ...field.RelationField) ISysAlbumCategoryDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysAlbumCategoryDo) FirstOrInit() (*model.SysAlbumCategory, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbumCategory), nil
	}
}

func (s sysAlbumCategoryDo) FirstOrCreate() (*model.SysAlbumCategory, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbumCategory), nil
	}
}

func (s sysAlbumCategoryDo) FindByPage(offset int, limit int) (result []*model.SysAlbumCategory, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysAlbumCategoryDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysAlbumCategoryDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysAlbumCategoryDo) Delete(models ...*model.SysAlbumCategory) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysAlbumCategoryDo) withDO(do gen.Dao) *sysAlbumCategoryDo {
	s.DO = *do.(*gen.DO)
	return s
}
