// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSysRegion(db *gorm.DB, opts ...gen.DOOption) sysRegion {
	_sysRegion := sysRegion{}

	_sysRegion.sysRegionDo.UseDB(db, opts...)
	_sysRegion.sysRegionDo.UseModel(&model.SysRegion{})

	tableName := _sysRegion.sysRegionDo.TableName()
	_sysRegion.ALL = field.NewAsterisk(tableName)
	_sysRegion.Code = field.NewInt32(tableName, "code")
	_sysRegion.Name = field.NewString(tableName, "name")
	_sysRegion.ParentCode = field.NewInt32(tableName, "parent_code")
	_sysRegion.Level = field.NewInt32(tableName, "level")

	_sysRegion.fillFieldMap()

	return _sysRegion
}

type sysRegion struct {
	sysRegionDo

	ALL        field.Asterisk
	Code       field.Int32  // 城市编码
	Name       field.String // 城市名称
	ParentCode field.Int32  // 上级城市
	Level      field.Int32  // 城市等级

	fieldMap map[string]field.Expr
}

func (s sysRegion) Table(newTableName string) *sysRegion {
	s.sysRegionDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysRegion) As(alias string) *sysRegion {
	s.sysRegionDo.DO = *(s.sysRegionDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysRegion) updateTableName(table string) *sysRegion {
	s.ALL = field.NewAsterisk(table)
	s.Code = field.NewInt32(table, "code")
	s.Name = field.NewString(table, "name")
	s.ParentCode = field.NewInt32(table, "parent_code")
	s.Level = field.NewInt32(table, "level")

	s.fillFieldMap()

	return s
}

func (s *sysRegion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysRegion) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 4)
	s.fieldMap["code"] = s.Code
	s.fieldMap["name"] = s.Name
	s.fieldMap["parent_code"] = s.ParentCode
	s.fieldMap["level"] = s.Level
}

func (s sysRegion) clone(db *gorm.DB) sysRegion {
	s.sysRegionDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysRegion) replaceDB(db *gorm.DB) sysRegion {
	s.sysRegionDo.ReplaceDB(db)
	return s
}

type sysRegionDo struct{ gen.DO }

type ISysRegionDo interface {
	gen.SubQuery
	Debug() ISysRegionDo
	WithContext(ctx context.Context) ISysRegionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysRegionDo
	WriteDB() ISysRegionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysRegionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysRegionDo
	Not(conds ...gen.Condition) ISysRegionDo
	Or(conds ...gen.Condition) ISysRegionDo
	Select(conds ...field.Expr) ISysRegionDo
	Where(conds ...gen.Condition) ISysRegionDo
	Order(conds ...field.Expr) ISysRegionDo
	Distinct(cols ...field.Expr) ISysRegionDo
	Omit(cols ...field.Expr) ISysRegionDo
	Join(table schema.Tabler, on ...field.Expr) ISysRegionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysRegionDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysRegionDo
	Group(cols ...field.Expr) ISysRegionDo
	Having(conds ...gen.Condition) ISysRegionDo
	Limit(limit int) ISysRegionDo
	Offset(offset int) ISysRegionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRegionDo
	Unscoped() ISysRegionDo
	Create(values ...*model.SysRegion) error
	CreateInBatches(values []*model.SysRegion, batchSize int) error
	Save(values ...*model.SysRegion) error
	First() (*model.SysRegion, error)
	Take() (*model.SysRegion, error)
	Last() (*model.SysRegion, error)
	Find() ([]*model.SysRegion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRegion, err error)
	FindInBatches(result *[]*model.SysRegion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysRegion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysRegionDo
	Assign(attrs ...field.AssignExpr) ISysRegionDo
	Joins(fields ...field.RelationField) ISysRegionDo
	Preload(fields ...field.RelationField) ISysRegionDo
	FirstOrInit() (*model.SysRegion, error)
	FirstOrCreate() (*model.SysRegion, error)
	FindByPage(offset int, limit int) (result []*model.SysRegion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysRegionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysRegionDo) Debug() ISysRegionDo {
	return s.withDO(s.DO.Debug())
}

func (s sysRegionDo) WithContext(ctx context.Context) ISysRegionDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysRegionDo) ReadDB() ISysRegionDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysRegionDo) WriteDB() ISysRegionDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysRegionDo) Session(config *gorm.Session) ISysRegionDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysRegionDo) Clauses(conds ...clause.Expression) ISysRegionDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysRegionDo) Returning(value interface{}, columns ...string) ISysRegionDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysRegionDo) Not(conds ...gen.Condition) ISysRegionDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysRegionDo) Or(conds ...gen.Condition) ISysRegionDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysRegionDo) Select(conds ...field.Expr) ISysRegionDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysRegionDo) Where(conds ...gen.Condition) ISysRegionDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysRegionDo) Order(conds ...field.Expr) ISysRegionDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysRegionDo) Distinct(cols ...field.Expr) ISysRegionDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysRegionDo) Omit(cols ...field.Expr) ISysRegionDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysRegionDo) Join(table schema.Tabler, on ...field.Expr) ISysRegionDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysRegionDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysRegionDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysRegionDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysRegionDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysRegionDo) Group(cols ...field.Expr) ISysRegionDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysRegionDo) Having(conds ...gen.Condition) ISysRegionDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysRegionDo) Limit(limit int) ISysRegionDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysRegionDo) Offset(offset int) ISysRegionDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysRegionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysRegionDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysRegionDo) Unscoped() ISysRegionDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysRegionDo) Create(values ...*model.SysRegion) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysRegionDo) CreateInBatches(values []*model.SysRegion, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysRegionDo) Save(values ...*model.SysRegion) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysRegionDo) First() (*model.SysRegion, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRegion), nil
	}
}

func (s sysRegionDo) Take() (*model.SysRegion, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRegion), nil
	}
}

func (s sysRegionDo) Last() (*model.SysRegion, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRegion), nil
	}
}

func (s sysRegionDo) Find() ([]*model.SysRegion, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysRegion), err
}

func (s sysRegionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysRegion, err error) {
	buf := make([]*model.SysRegion, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysRegionDo) FindInBatches(result *[]*model.SysRegion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysRegionDo) Attrs(attrs ...field.AssignExpr) ISysRegionDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysRegionDo) Assign(attrs ...field.AssignExpr) ISysRegionDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysRegionDo) Joins(fields ...field.RelationField) ISysRegionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysRegionDo) Preload(fields ...field.RelationField) ISysRegionDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysRegionDo) FirstOrInit() (*model.SysRegion, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRegion), nil
	}
}

func (s sysRegionDo) FirstOrCreate() (*model.SysRegion, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysRegion), nil
	}
}

func (s sysRegionDo) FindByPage(offset int, limit int) (result []*model.SysRegion, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysRegionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysRegionDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysRegionDo) Delete(models ...*model.SysRegion) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysRegionDo) withDO(do gen.Dao) *sysRegionDo {
	s.DO = *do.(*gen.DO)
	return s
}
