// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"generated/generated-test/dm/model"
)

func newSysAlbum(db *gorm.DB, opts ...gen.DOOption) sysAlbum {
	_sysAlbum := sysAlbum{}

	_sysAlbum.sysAlbumDo.UseDB(db, opts...)
	_sysAlbum.sysAlbumDo.UseModel(&model.SysAlbum{})

	tableName := _sysAlbum.sysAlbumDo.TableName()
	_sysAlbum.ALL = field.NewAsterisk(tableName)
	_sysAlbum.ID = field.NewInt64(tableName, "id")
	_sysAlbum.Cid = field.NewInt64(tableName, "cid")
	_sysAlbum.Aid = field.NewInt64(tableName, "aid")
	_sysAlbum.UID = field.NewInt64(tableName, "uid")
	_sysAlbum.Type = field.NewInt32(tableName, "type")
	_sysAlbum.Name = field.NewString(tableName, "name")
	_sysAlbum.URI = field.NewString(tableName, "uri")
	_sysAlbum.Ext = field.NewString(tableName, "ext")
	_sysAlbum.Size = field.NewInt64(tableName, "size")
	_sysAlbum.CreatedAt = field.NewTime(tableName, "created_at")
	_sysAlbum.UpdatedAt = field.NewField(tableName, "updated_at")
	_sysAlbum.DeletedAt = field.NewField(tableName, "deleted_at")

	_sysAlbum.fillFieldMap()

	return _sysAlbum
}

type sysAlbum struct {
	sysAlbumDo

	ALL       field.Asterisk
	ID        field.Int64  // 主键ID
	Cid       field.Int64  // 类目ID
	Aid       field.Int64  // 管理员ID
	UID       field.Int64  // 用户ID
	Type      field.Int32  // 文件类型: [10=图片, 20=视频]
	Name      field.String // 文件名称
	URI       field.String // 文件路径
	Ext       field.String // 文件扩展
	Size      field.Int64  // 文件大小
	CreatedAt field.Time   // 创建时间
	UpdatedAt field.Field  // 更新时间
	DeletedAt field.Field  // 删除时间

	fieldMap map[string]field.Expr
}

func (s sysAlbum) Table(newTableName string) *sysAlbum {
	s.sysAlbumDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s sysAlbum) As(alias string) *sysAlbum {
	s.sysAlbumDo.DO = *(s.sysAlbumDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *sysAlbum) updateTableName(table string) *sysAlbum {
	s.ALL = field.NewAsterisk(table)
	s.ID = field.NewInt64(table, "id")
	s.Cid = field.NewInt64(table, "cid")
	s.Aid = field.NewInt64(table, "aid")
	s.UID = field.NewInt64(table, "uid")
	s.Type = field.NewInt32(table, "type")
	s.Name = field.NewString(table, "name")
	s.URI = field.NewString(table, "uri")
	s.Ext = field.NewString(table, "ext")
	s.Size = field.NewInt64(table, "size")
	s.CreatedAt = field.NewTime(table, "created_at")
	s.UpdatedAt = field.NewField(table, "updated_at")
	s.DeletedAt = field.NewField(table, "deleted_at")

	s.fillFieldMap()

	return s
}

func (s *sysAlbum) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *sysAlbum) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 12)
	s.fieldMap["id"] = s.ID
	s.fieldMap["cid"] = s.Cid
	s.fieldMap["aid"] = s.Aid
	s.fieldMap["uid"] = s.UID
	s.fieldMap["type"] = s.Type
	s.fieldMap["name"] = s.Name
	s.fieldMap["uri"] = s.URI
	s.fieldMap["ext"] = s.Ext
	s.fieldMap["size"] = s.Size
	s.fieldMap["created_at"] = s.CreatedAt
	s.fieldMap["updated_at"] = s.UpdatedAt
	s.fieldMap["deleted_at"] = s.DeletedAt
}

func (s sysAlbum) clone(db *gorm.DB) sysAlbum {
	s.sysAlbumDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s sysAlbum) replaceDB(db *gorm.DB) sysAlbum {
	s.sysAlbumDo.ReplaceDB(db)
	return s
}

type sysAlbumDo struct{ gen.DO }

type ISysAlbumDo interface {
	gen.SubQuery
	Debug() ISysAlbumDo
	WithContext(ctx context.Context) ISysAlbumDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ISysAlbumDo
	WriteDB() ISysAlbumDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ISysAlbumDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ISysAlbumDo
	Not(conds ...gen.Condition) ISysAlbumDo
	Or(conds ...gen.Condition) ISysAlbumDo
	Select(conds ...field.Expr) ISysAlbumDo
	Where(conds ...gen.Condition) ISysAlbumDo
	Order(conds ...field.Expr) ISysAlbumDo
	Distinct(cols ...field.Expr) ISysAlbumDo
	Omit(cols ...field.Expr) ISysAlbumDo
	Join(table schema.Tabler, on ...field.Expr) ISysAlbumDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ISysAlbumDo
	RightJoin(table schema.Tabler, on ...field.Expr) ISysAlbumDo
	Group(cols ...field.Expr) ISysAlbumDo
	Having(conds ...gen.Condition) ISysAlbumDo
	Limit(limit int) ISysAlbumDo
	Offset(offset int) ISysAlbumDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAlbumDo
	Unscoped() ISysAlbumDo
	Create(values ...*model.SysAlbum) error
	CreateInBatches(values []*model.SysAlbum, batchSize int) error
	Save(values ...*model.SysAlbum) error
	First() (*model.SysAlbum, error)
	Take() (*model.SysAlbum, error)
	Last() (*model.SysAlbum, error)
	Find() ([]*model.SysAlbum, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAlbum, err error)
	FindInBatches(result *[]*model.SysAlbum, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.SysAlbum) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ISysAlbumDo
	Assign(attrs ...field.AssignExpr) ISysAlbumDo
	Joins(fields ...field.RelationField) ISysAlbumDo
	Preload(fields ...field.RelationField) ISysAlbumDo
	FirstOrInit() (*model.SysAlbum, error)
	FirstOrCreate() (*model.SysAlbum, error)
	FindByPage(offset int, limit int) (result []*model.SysAlbum, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ISysAlbumDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (s sysAlbumDo) Debug() ISysAlbumDo {
	return s.withDO(s.DO.Debug())
}

func (s sysAlbumDo) WithContext(ctx context.Context) ISysAlbumDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s sysAlbumDo) ReadDB() ISysAlbumDo {
	return s.Clauses(dbresolver.Read)
}

func (s sysAlbumDo) WriteDB() ISysAlbumDo {
	return s.Clauses(dbresolver.Write)
}

func (s sysAlbumDo) Session(config *gorm.Session) ISysAlbumDo {
	return s.withDO(s.DO.Session(config))
}

func (s sysAlbumDo) Clauses(conds ...clause.Expression) ISysAlbumDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s sysAlbumDo) Returning(value interface{}, columns ...string) ISysAlbumDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s sysAlbumDo) Not(conds ...gen.Condition) ISysAlbumDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s sysAlbumDo) Or(conds ...gen.Condition) ISysAlbumDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s sysAlbumDo) Select(conds ...field.Expr) ISysAlbumDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s sysAlbumDo) Where(conds ...gen.Condition) ISysAlbumDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s sysAlbumDo) Order(conds ...field.Expr) ISysAlbumDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s sysAlbumDo) Distinct(cols ...field.Expr) ISysAlbumDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s sysAlbumDo) Omit(cols ...field.Expr) ISysAlbumDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s sysAlbumDo) Join(table schema.Tabler, on ...field.Expr) ISysAlbumDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s sysAlbumDo) LeftJoin(table schema.Tabler, on ...field.Expr) ISysAlbumDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s sysAlbumDo) RightJoin(table schema.Tabler, on ...field.Expr) ISysAlbumDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s sysAlbumDo) Group(cols ...field.Expr) ISysAlbumDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s sysAlbumDo) Having(conds ...gen.Condition) ISysAlbumDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s sysAlbumDo) Limit(limit int) ISysAlbumDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s sysAlbumDo) Offset(offset int) ISysAlbumDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s sysAlbumDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ISysAlbumDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s sysAlbumDo) Unscoped() ISysAlbumDo {
	return s.withDO(s.DO.Unscoped())
}

func (s sysAlbumDo) Create(values ...*model.SysAlbum) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s sysAlbumDo) CreateInBatches(values []*model.SysAlbum, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s sysAlbumDo) Save(values ...*model.SysAlbum) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s sysAlbumDo) First() (*model.SysAlbum, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbum), nil
	}
}

func (s sysAlbumDo) Take() (*model.SysAlbum, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbum), nil
	}
}

func (s sysAlbumDo) Last() (*model.SysAlbum, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbum), nil
	}
}

func (s sysAlbumDo) Find() ([]*model.SysAlbum, error) {
	result, err := s.DO.Find()
	return result.([]*model.SysAlbum), err
}

func (s sysAlbumDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SysAlbum, err error) {
	buf := make([]*model.SysAlbum, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s sysAlbumDo) FindInBatches(result *[]*model.SysAlbum, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s sysAlbumDo) Attrs(attrs ...field.AssignExpr) ISysAlbumDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s sysAlbumDo) Assign(attrs ...field.AssignExpr) ISysAlbumDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s sysAlbumDo) Joins(fields ...field.RelationField) ISysAlbumDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s sysAlbumDo) Preload(fields ...field.RelationField) ISysAlbumDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s sysAlbumDo) FirstOrInit() (*model.SysAlbum, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbum), nil
	}
}

func (s sysAlbumDo) FirstOrCreate() (*model.SysAlbum, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SysAlbum), nil
	}
}

func (s sysAlbumDo) FindByPage(offset int, limit int) (result []*model.SysAlbum, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s sysAlbumDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s sysAlbumDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s sysAlbumDo) Delete(models ...*model.SysAlbum) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *sysAlbumDo) withDO(do gen.Dao) *sysAlbumDo {
	s.DO = *do.(*gen.DO)
	return s
}
